/*

Copyright (c) 2008 Mars Semiconductor Corp.

Module Name:

    uiapi.h

Abstract:

    The application interface of user interface.

Environment:

        ARM RealView Developer Suite

Revision History:

    2005/08/26  David Tsai  Create

*/

#ifndef __UIACT_MR6790E_H__
#define __UIACT_MR6790E_H__

/* Constant definition */

#define UI_PLAYBACK_SPEED_LEVEL     10

enum
{
    UI_MENU_DELETE_YES = 0,
    UI_MENU_DELETE_NO,
};

enum 
{
    UI_MENU_VIDEO_QUALITY_HIGH = 0,
    UI_MENU_VIDEO_QUALITY_MEDIUM,
    UI_MENU_VIDEO_QUALITY_LOW,
};

enum 
{
    UI_MENU_VIDEO_FRAMERATE_30 = 0,
    UI_MENU_VIDEO_FRAMERATE_15,
    UI_MENU_VIDEO_FRAMERATE_5,
    UI_MENU_VIDEO_FRAMERATE_10,
};

enum
{
    UI_MENU_SETTING_RESOLUTION_HD=0,
    UI_MENU_SETTING_RESOLUTION_VGA,
	UI_MENU_SETTING_RESOLUTION_QVGA,
	UI_MENU_SETTING_RESOLUTION_D1_480V,
	UI_MENU_SETTING_RESOLUTION_D1_576V,
	UI_MENU_SETTING_RESOLUTION_352x240
};
enum
{
    UI_MENU_VIDEO_OVERWRITESTR_ALL = 0,
    UI_MENU_VIDEO_OVERWRITESTR_TIMEONLY,
    UI_MENU_VIDEO_OVERWRITESTR_NONE,
};
enum
{
    UI_MENU_SETTING_OVERWRITE_YES = 0,
    UI_MENU_SETTING_OVERWRITE_NO,
};

enum 
{
    UI_MENU_SETTING_SECTION_20SEC = 0,
    UI_MENU_SETTING_SECTION_1MIN,
    UI_MENU_SETTING_SECTION_5MIN,
    UI_MENU_SETTING_SECTION_10MIN,
    UI_MENU_SETTING_SECTION_15MIN,
    UI_MENU_SETTING_SECTION_30MIN,
#if (HW_BOARD_OPTION == MR6730_AFN )
    UI_MENU_SETTING_SECTION_60MIN,    
    UI_MENU_SETTING_SECTION_120MIN,
#endif 
};

enum
{
    UI_MENU_SETTING_CHANNEL_1 = 0,
    UI_MENU_SETTING_CHANNEL_2,
};

enum
{
    UI_MENU_REC_MODE_MANUAL = 0,
    UI_MENU_REC_MODE_MOTION,
    UI_MENU_REC_MODE_PARKING,
    UI_MENU_REC_MODE_DRIVING
};

enum
{
    UI_MENU_FORMAT_YES= 0,
    UI_MENU_FORMAT_NO

};

enum
{
    UI_MENU_TV = 0,
    UI_MENU_PANEL,
};

enum
{
    UI_AUDIO_RESOLUTION_8BIT = 0,
    UI_AUDIO_RESOLUTION_16BIT,
};

enum
{
    UI_AUDIO_SAMPLING_8K = 0,
    UI_AUDIO_SAMPLING_16K,
    UI_AUDIO_SAMPLING_32K,
    UI_AUDIO_SAMPLING_44K,
    UI_AUDIO_SAMPLING_48K,
};

enum
{
    UI_MENU_SETTING_MOTION_SENSITIVITY_H = 0,
    UI_MENU_SETTING_MOTION_SENSITIVITY_M,
    UI_MENU_SETTING_MOTION_SENSITIVITY_L,
};

enum
{
    UI_MENU_CHANNEL_ADD= 0,
    UI_MENU_CHANNEL_SUB,
    UI_MENU_CHANNEL_1,
    UI_MENU_CHANNEL_2,
    UI_MENU_CHANNEL_3,
    UI_MENU_CHANNEL_4,
    UI_MENU_CHANNEL_SCAN
};

enum
{
    UI_MENU_RF_QUAD= 0,
    UI_MENU_RF_FULL,
    UI_MENU_RF_DUAL,
    UI_MENU_RF_ENTER_PLAYBACK,
    UI_MENU_RF_ENTER_SETUP,
    UI_MENU_RF_ENTER_MASKAREA
};

enum
{
    UI_MENU_CH1= 0,
    UI_MENU_CH2,
    UI_MENU_CH3,
    UI_MENU_CH4,

};

enum
{
    UI_MENU_NTSC =0,
    UI_MENU_PAL,
};

enum
{
    UI_MENU_SETTING_LANGUAGE_ENGLISH = 0,
    UI_MENU_SETTING_LANGUAGE_TCHINESE,
	UI_MENU_SETTING_LANGUAGE_SCHINESE,
};

enum
{
    UI_MENU_STATIC_IP =0,
    UI_MENU_DYNAMIC_IP,
};

enum
{
    UI_MENU_TX_MOTION_OFF =0,
    UI_MENU_TX_MOTION_ON,
};

enum 
{
    UI_MENU_SETTING_CAMERA_OFF =0,
	UI_MENU_SETTING_CAMERA_ON,
};

enum 
{
    UI_MENU_SETTING_BUZZER_OFF =0,
	UI_MENU_SETTING_BUZZER_ON,
};

enum 
{
    UI_MENU_SETTING_PIR_OFF =0,
	UI_MENU_SETTING_PIR_ON,
};

#if (HW_BOARD_OPTION  == MR8120_TX_RDI_CL692)
enum 
{
    UI_MENU_SETTING_LS_DUR_OFF =0,
    UI_MENU_SETTING_LS_DUR_1MIN,
    UI_MENU_SETTING_LS_DUR_3MIN,
    UI_MENU_SETTING_LS_DUR_10MIN,
};

enum 
{
    UI_MENU_SETTING_LS_DIMMER_25 =0,
    UI_MENU_SETTING_LS_DIMMER_50,
    UI_MENU_SETTING_LS_DIMMER_75,
    UI_MENU_SETTING_LS_DIMMER_100,
};
#endif


enum
{
    UI_MENU_SETIDX_MELODY_OFF = 0,
    UI_MENU_SETIDX_MELODY_1,
    UI_MENU_SETIDX_MELODY_2,
    UI_MENU_SETIDX_MELODY_3,
    UI_MENU_SETIDX_MELODY_4,
    UI_MENU_SETIDX_MELODY_ALL,
};

enum
{
    UI_MENU_SETIDX_LIGHT_OFF = 0,
    UI_MENU_SETIDX_LIGHT_ON,

};

#define UI_MENU_SETTING_TV_OUT_NTSC  SYS_TV_OUT_NTSC //Lucian: 統一定義 for whole system
#define UI_MENU_SETTING_TV_OUT_PAL   SYS_TV_OUT_PAL
#define UI_MENU_SETTING_PANEL_OUT    2

#if(Sensor_OPTION == Sensor_MI_5M)
#define UI_MENU_IMAGE_SIZE_4000x3000        0x00
#define UI_MENU_IMAGE_SIZE_2560x1920        0x01
#define UI_MENU_IMAGE_SIZE_1920x1440        0x02
#define UI_MENU_IMAGE_SIZE_1600x1200        0x03
#define UI_MENU_IMAGE_SIZE_800x600          0x04
#define UI_MENU_IMAGE_SIZE_640x480          0x05

#elif(Sensor_OPTION == Sensor_MI_2M)
#define UI_MENU_IMAGE_SIZE_1600x1200        0x00
#define UI_MENU_IMAGE_SIZE_800x600          0x01
#define UI_MENU_IMAGE_SIZE_640x480          0x02

#elif( (Sensor_OPTION == Sensor_OV7725_VGA) || (Sensor_OPTION == Sensor_OV7725_YUV601) || (Sensor_OPTION ==Sensor_OV7740_YUV601) || (Sensor_OPTION == Sensor_OV7740_RAW) || (Sensor_OPTION == Sensor_MI9V136_YUV601) || (Sensor_OPTION == Sensor_PC1089_YUV601) )
#define UI_MENU_IMAGE_SIZE_640x480      0x00

#elif( (Sensor_OPTION == Sensor_MI1320_YUV601) || (Sensor_OPTION == Sensor_MI1320_RAW) || (Sensor_OPTION == Sensor_OV2643_YUV601) || (Sensor_OPTION == Sensor_MT9M131_YUV601) || (Sensor_OPTION == Sensor_HM5065_YUV601) || (Sensor_OPTION == Sensor_HM1375_YUV601) || (Sensor_OPTION == Sensor_NT99141_YUV601) || (Sensor_OPTION == Sensor_NT99340_YUV601) || (Sensor_OPTION == Sensor_PO3100K_YUV601) )
#define UI_MENU_IMAGE_SIZE_640x480      0x00

#elif(Sensor_OPTION == Sensor_CCIR656)
#define UI_MENU_IMAGE_SIZE_640x480          0x00

#elif(Sensor_OPTION == Sensor_CCIR601)
#define UI_MENU_IMAGE_SIZE_640x480          0x00
#endif



extern  u8 Current_Alarm_Period;
#endif

