#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ --no_debug --dwarf2 -O3
CARM_SRCS	= 		  .\src\fs_info.c .\src\api_in.c .\src\api_misc.c \
		  .\src\api_out.c .\src\api_dir.c .\src\clibmisc.c \
		  .\src\storage.c .\src\fat_out.c .\src\fat_dir.c \
		  .\src\fat_in.c .\src\fat_ioct.c .\src\fat_misc.c \
		  .\src\fat_open.c .\src\fat_data.c .\src\lb_misc.c \
		  .\src\fs_x_ucos_ii.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\fs_info.o Release\api_in.o \
		  Release\api_misc.o Release\api_out.o \
		  Release\api_dir.o Release\clibmisc.o \
		  Release\storage.o Release\fat_out.o \
		  Release\fat_dir.o Release\fat_in.o \
		  Release\fat_ioct.o Release\fat_misc.o \
		  Release\fat_open.o Release\fat_data.o \
		  Release\lb_misc.o Release\fs_x_ucos_ii.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= fs_release_Release.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Release\..\..\lib\release\fs_release.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 8
#   Selected list: ..\smc\inc\smcwc.h 
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) ..\fs\inc\fs_fat.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) ..\inc\\memorypool.h 
___INC__SMCAPI_H=..\inc\\smcapi.h $(___INC__GENERAL_H) 
___INC__I2CAPI_H=..\inc\\i2capi.h ..\inc\\rtcapi.h 
___INC__SIUAPI_H=..\inc\\siuapi.h 
# DEPEND: end include files

Release\fs_info.o: .\src\fs_info.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\fs_info.c \
	 $(CARM) -o Release\fs_info.o
Release\api_in.o: .\src\api_in.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\api_in.c \
	 $(CARM) -o Release\api_in.o
Release\api_misc.o: .\src\api_misc.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h  inc\\api_int.h inc\\fs_fat.h \
	 inc\\fs_clib.h ..\inc\\general.h ..\inc\\awbdef.h ..\inc\\osapi.h \
	 ..\inc\\memorypool.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\api_misc.c \
	 $(CARM) -o Release\api_misc.o
Release\api_out.o: .\src\api_out.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\api_out.c \
	 $(CARM) -o Release\api_out.o
Release\api_dir.o: .\src\api_dir.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h inc\\api_int.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\api_dir.c \
	 $(CARM) -o Release\api_dir.o
Release\clibmisc.o: .\src\clibmisc.c $(___INC__FSAPI_H)  inc\\fs_clib.h \
	 ..\inc\\dmaapi.h ..\inc\\general.h ..\inc\\awbdef.h \
	 ..\inc\\osapi.h ..\inc\\memorypool.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\clibmisc.c \
	 $(CARM) -o Release\clibmisc.o
Release\storage.o: .\src\storage.c $(___INC__FSAPI_H) inc\\fs_clib.h \
	 ..\inc\\ramdiskapi.h ..\inc\\sdcapi.h $(___INC__SMCAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\storage.c \
	 $(CARM) -o Release\storage.o
Release\fat_out.o: .\src\fat_out.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h  inc\\fs_fat.h inc\\fs_clib.h \
	 ..\inc\\board.h $(___INC__I2CAPI_H) ..\inc\\general.h \
	 ..\inc\\awbdef.h ..\inc\\osapi.h ..\inc\\memorypool.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\fat_out.c \
	 $(CARM) -o Release\fat_out.o
Release\fat_dir.o: .\src\fat_dir.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h inc\\fs_fat.h inc\\fs_clib.h \
	 $(___INC__SMCAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\fat_dir.c \
	 $(CARM) -o Release\fat_dir.o
Release\fat_in.o: .\src\fat_in.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h inc\\fs_fat.h inc\\fs_clib.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\fat_in.c \
	 $(CARM) -o Release\fat_in.o
Release\fat_ioct.o: .\src\fat_ioct.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h inc\\fs_fat.h inc\\fs_clib.h \
	 $(___INC__SMCAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\fat_ioct.c \
	 $(CARM) -o Release\fat_ioct.o
Release\fat_misc.o: .\src\fat_misc.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h  inc\\fs_fat.h inc\\fs_clib.h \
	 ..\inc\\general.h ..\inc\\awbdef.h ..\inc\\osapi.h \
	 ..\inc\\memorypool.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\fat_misc.c \
	 $(CARM) -o Release\fat_misc.o
Release\fat_open.o: .\src\fat_open.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h inc\\fs_fat.h inc\\fs_clib.h \
	 $(___INC__SMCAPI_H) $(___INC__I2CAPI_H) ..\inc\\sysapi.h \
	 $(___INC__SIUAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\fat_open.c \
	 $(CARM) -o Release\fat_open.o
Release\fat_data.o: .\src\fat_data.c $(___INC__FSAPI_H) inc\\fs_fat.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\fat_data.c \
	 $(CARM) -o Release\fat_data.o
Release\lb_misc.o: .\src\lb_misc.c $(___INC__FSAPI_H) inc\\fs_fsl.h \
	 inc\\fs_int.h inc\\fs_os.h  inc\\fs_fat.h inc\\fs_clib.h \
	 ..\inc\\general.h ..\inc\\awbdef.h ..\inc\\osapi.h \
	 ..\inc\\memorypool.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\lb_misc.c \
	 $(CARM) -o Release\lb_misc.o
Release\fs_x_ucos_ii.o: .\src\fs_x_ucos_ii.c $(___INC__FSAPI_H) \
	 inc\\fs_os.h  inc\\fs_clib.h ..\inc\\general.h ..\inc\\awbdef.h \
	 ..\inc\\osapi.h ..\inc\\memorypool.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\fs_x_ucos_ii.c $(CARM) -o Release\fs_x_ucos_ii.o
