#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\ -I..\ucos_ii\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ -DSTANDALONE --no_debug --dwarf2 -O3
CARM_SRCS	= 		  .\src\retarget.c .\src\initshadow.c .\src\general.c \
		  .\src\submain.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\retarget.o Release\initshadow.o \
		  Release\general.o Release\submain.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	= -i..\ucos_ii\inc\ -i..\inc\ -i.\inc\ -pd "USE_SCATTER_SYMS SETL {TRUE}" --dwarf2
AARM_SRCS	= 		  .\src\initstmem.s .\src\initsysctrl.s \
		  .\src\embed_uish.s .\src\init.s .\src\vectors.s \
		  .\src\initmmu.s .\src\initcache.s .\src\ttb.s \
		  .\src\initsdram.s 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 		  Release\initstmem.o Release\initsysctrl.o \
		  Release\embed_uish.o Release\init.o \
		  Release\vectors.o Release\initmmu.o \
		  Release\initcache.o Release\ttb.o \
		  Release\initsdram.o 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=  --symdefs ..\exe\pa9001_release.sym --info sizes --info totals --entry START_0 --scatter scatter.txt --keep init*.o

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=

# LIBS are system libraries as name
LIBS		=   ..\lib\release\cf_release  ..\lib\release\mars_timer_release.lib  \
	 ..\lib\release\mars_dma_release.lib  \
	 ..\lib\release\mars_int_release.lib  \
	 ..\lib\release\mars_system_release.lib  \
	 ..\lib\release\debug_release.lib  ..\lib\release\isp_release.lib  \
	 ..\lib\release\avi_release.lib  ..\lib\release\asf_release.lib  \
	 ..\lib\release\mp4_release.lib  ..\lib\release\sys_release.lib  \
	 ..\lib\release\dpof_release.lib  ..\lib\release\dcf_release.lib  \
	 ..\lib\release\spi_release.lib  ..\lib\release\ui_release.lib  \
	 ..\lib\release\hiu_release.lib  ..\lib\release\adc_release.lib  \
	 ..\lib\release\iis_release.lib  ..\lib\release\smc_release.lib  \
	 ..\lib\release\rtc_release.lib  ..\lib\release\gpio_release.lib  \
	 ..\lib\release\timer_release.lib  ..\lib\release\idu_release.lib  \
	 ..\lib\release\isu_release.lib  ..\lib\release\ipu_release.lib  \
	 ..\lib\release\main_release.lib  \
	 ..\lib\release\ramdisk_release.lib  ..\lib\release\fs_release.lib  \
	 ..\lib\release\shell_release.lib  ..\lib\release\usb_release.lib  \
	 ..\lib\release\siu_release.lib  ..\lib\release\mpeg4_release.lib  \
	 ..\lib\release\jpeg_release.lib  ..\lib\release\i2c_release.lib  \
	 ..\lib\release\uart_release.lib  ..\lib\release\sdc_release.lib  \
	 ..\lib\release\ucos_ii_release.lib 

CC		= cl$(TARGET)
LINKER		= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armlink 
LIBRARIAN	=
MAKENAME	= board_release_Release.mk
PRINT		= pr
PROGRAM		= Release\..\..\exe\pa9001_release.axf
BUILD_LIB	= none.lib
POST_BUILD	=
ALL_DEP		= $(PROGRAM) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	= dependency.lib
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

	+fromelf ..\exe\pa9001_release.axf --bin --output ..\exe\pa900r.bin
#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 3
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\project.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) ..\inc\\memorypool.h 
# DEPEND: end include files

Release\retarget.o: .\src\retarget.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\retarget.c \
	 $(CARM) -o Release\retarget.o
Release\initshadow.o: .\src\initshadow.c $(___INC__GENERAL_H) ..\inc\\board.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\initshadow.c \
	 $(CARM) -o Release\initshadow.o
Release\general.o: .\src\general.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\general.c \
	 $(CARM) -o Release\general.o
Release\submain.o: .\src\submain.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\submain.c \
	 $(CARM) -o Release\submain.o
Release\initstmem.o: .\src\initstmem.s ..\inc\sysopt.inc
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o \
	 Release\initstmem.o .\src\initstmem.s
Release\initsysctrl.o: .\src\initsysctrl.s ..\inc\sysopt.inc
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o \
	 Release\initsysctrl.o .\src\initsysctrl.s
Release\embed_uish.o: .\src\embed_uish.s
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o \
	 Release\embed_uish.o .\src\embed_uish.s
Release\init.o: .\src\init.s ..\inc\sysopt.inc
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o \
	 Release\init.o .\src\init.s
Release\vectors.o: .\src\vectors.s
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o \
	 Release\vectors.o .\src\vectors.s
Release\initmmu.o: .\src\initmmu.s
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o \
	 Release\initmmu.o .\src\initmmu.s
Release\initcache.o: .\src\initcache.s
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o \
	 Release\initcache.o .\src\initcache.s
Release\ttb.o: .\src\ttb.s
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o \
	 Release\ttb.o .\src\ttb.s
Release\initsdram.o: .\src\initsdram.s
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o \
	 Release\initsdram.o .\src\initsdram.s
dependency.lib :	$(LIBS)  
	@+echo ---library dependency---
