#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I.\include\tutk_p2p -I.\include\netif -I.\include\lwip \
	 -I.\include\arch -I.\gpi\inc\ -I..\inc\ -I..\inc\os\ -I.\include\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I.\include\tutk_p2p -I.\include\netif -I.\include\lwip -I.\include\arch -I.\gpi\inc\ -I..\inc\ -I..\inc\os\ -I.\include\ --no_debug --dwarf2 --pointer_alignment=4 -O3
CARM_SRCS	= 		  .\rtsp\handler_rtsp.c .\rtsp\rtsp_method.c \
		  .\rtsp\rtcp.c .\rtsp\sdp.c .\rtsp\rtp.c \
		  tutk_P2P\P2P_server.c .\netif\ppp\md5.c \
		  .\netif\FTMAC110.C .\core\dns_clinet.c LwIPEntry.c \
		  .\core\dhcp.c .\core\inet.c .\core\mem.c \
		  .\core\memp.c .\core\netif.c .\core\pbuf.c \
		  .\core\raw.c .\core\stats.c .\core\sys.c \
		  .\core\tcp.c .\core\tcp_in.c .\core\tcp_out.c \
		  .\core\udp.c .\core\snmp\msg_out.c \
		  .\core\snmp\asn1_dec.c .\core\snmp\asn1_enc.c \
		  .\core\snmp\mib2.c .\core\snmp\mib_structs.c \
		  .\core\snmp\msg_in.c .\arch\sys_arch.c \
		  .\api\tcpip.c .\api\api_lib.c .\api\api_msg.c \
		  .\api\err.c .\api\sockets.c .\netif\etharp.c \
		  .\netif\ethernetif.c .\netif\loopif.c \
		  .\netif\slipif.c .\tools\converter.c \
		  .\tools\search.c .\tools\stringExtAPI.c \
		  .\http\handler_http.c .\core\ipv4\icmp.c \
		  .\core\ipv4\ip.c .\core\ipv4\ip_addr.c \
		  .\core\ipv4\ip_frag.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\handler_rtsp.o Release\rtsp_method.o \
		  Release\rtcp.o Release\sdp.o Release\rtp.o \
		  Release\P2P_server.o Release\md5.o \
		  Release\FTMAC110.o Release\dns_clinet.o \
		  Release\LwIPEntry.o Release\dhcp.o Release\inet.o \
		  Release\mem.o Release\memp.o Release\netif.o \
		  Release\pbuf.o Release\raw.o Release\stats.o \
		  Release\sys.o Release\tcp.o Release\tcp_in.o \
		  Release\tcp_out.o Release\udp.o Release\msg_out.o \
		  Release\asn1_dec.o Release\asn1_enc.o \
		  Release\mib2.o Release\mib_structs.o \
		  Release\msg_in.o Release\sys_arch.o Release\tcpip.o \
		  Release\api_lib.o Release\api_msg.o Release\err.o \
		  Release\sockets.o Release\etharp.o \
		  Release\ethernetif.o Release\loopif.o \
		  Release\slipif.o Release\converter.o \
		  Release\search.o Release\stringExtAPI.o \
		  Release\handler_http.o Release\icmp.o Release\ip.o \
		  Release\ip_addr.o Release\ip_frag.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= Lwip_Release.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\Lwip.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 58
#   Selected list: ..\lwip\include\lwip\tcpip.h ..\lwip\include\lwip\api.h \
	 ..\lwip\include\lwip\net.h ..\lwip\include\lwip\rtp.h \
	 ..\lwip\include\lwip\rtsp.h ..\lwip\include\lwip\dns_clinet.h \
	 ..\lwip\tools\stringextapi.h ..\lwip\tools\search.h \
	 ..\lwip\tools\converter.h ..\lwip\include\lwip\net.h \
	 ..\lwip\include\lwip\rtp.h ..\lwip\include\lwip\rtsp.h \
	 ..\lwip\include\lwip\sdp.h ..\lwip\include\lwip\api.h \
	 ..\lwip\include\lwip\net.h ..\lwip\include\lwip\rtp.h \
	 ..\lwip\include\lwip\rtsp.h ..\lwip\include\lwip\rtcp.h \
	 ..\lwip\include\lwip\rtp.h ..\lwip\include\lwip\rtsp.h \
	 ..\lwip\include\lwip\sdp.h ..\lwip\include\lwip\tcpip.h \
	 ..\lwip\include\lwip\api.h ..\lwip\tools\stringextapi.h \
	 ..\lwip\tools\search.h ..\lwip\tools\converter.h \
	 ..\lwip\include\lwip\dns_clinet.h .\lwip\lwipsys.h .\lwip\def.h \
	 .\arch\cc.h .\arch\sys_arch.h ..\gpi\inc\net.h ..\gpi\inc\gpi.h \
	 ..\lwip\include\lwip\tcpip.h ..\lwip\include\lwip\api.h \
	 ..\lwip\include\lwip\dns_clinet.h ..\lwip\tools\stringextapi.h \
	 ..\lwip\tools\search.h ..\lwip\tools\converter.h 
___INC_OS__UCOS_II_H=..\inc\os\\ucos_ii.h ..\inc\os\\os_cfg.h 
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\application.h \
	 ..\inc\\project.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h 
INCLUDE__LWIP_OPT_H=include\\lwip\opt.h include\\arch\lwipopts.h \
	 include\\lwip\debug.h 
INCLUDE__LWIP_LWIPSYS_H=include\\lwip\lwipsys.h include\\arch\sys_arch.h 
INCLUDE__LWIP_IP_H=include\\lwip\ip.h include\\lwip\arch.h \
	 include\\lwip\def.h 
INCLUDE__LWIP_RAW_H=include\\lwip\raw.h include\\lwip\inet.h 
INCLUDE__LWIP_TCP_H=include\\lwip\tcp.h include\\lwip\icmp.h 
INCLUDE_LWIP_API_H=include\lwip\api.h $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\pbuf.h $(INCLUDE__LWIP_LWIPSYS_H) \
	 $(INCLUDE__LWIP_IP_H) $(INCLUDE__LWIP_RAW_H) include\\lwip\udp.h \
	 $(INCLUDE__LWIP_TCP_H) include\\lwip\err.h 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\uikey.h 
___INC__FSAPI_H=..\inc\\fsapi.h 
___INC__ASFAPI_H=..\inc\\asfapi.h $(___INC__FSAPI_H) 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GLOBALVARIABLE_H=..\inc\\globalvariable.h $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\task.h ..\inc\\mp4api.h \
	 $(___INC__ASFAPI_H) ..\inc\\aviapi.h ..\inc\\mpeg4api.h \
	 ..\inc\\isuapi.h ..\inc\\iduapi.h ..\inc\\gpioapi.h \
	 $(___INC__SIUAPI_H) ..\inc\\sysapi.h $(___INC__OSAPI_H) \
	 ..\inc\\rtcapi.h ..\inc\\i2capi.h $(___INC__UIAPI_H) \
	 ..\inc\\memorypool.h ..\inc\\iisapi.h 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__TIMERAPI_H=..\inc\\timerapi.h $(___INC__GENERAL_H) 
___UI_INC_UI_H=..\ui\inc\ui.h $(___INC__FSAPI_H) ..\inc\\rtcapi.h \
	 $(___INC__UIAPI_H) 
___UI_INC_UI_PROJECT_H=..\ui\inc\ui_project.h ..\inc\\motiondetect_api.h \
	 ..\inc\\rtcapi.h 
INCLUDE__LWIP_API_H=include\\lwip\api.h include\\lwip\pbuf.h \
	 $(INCLUDE__LWIP_LWIPSYS_H) $(INCLUDE__LWIP_IP_H) \
	 $(INCLUDE__LWIP_RAW_H) include\\lwip\udp.h $(INCLUDE__LWIP_TCP_H) \
	 include\\lwip\err.h 
INCLUDE__LWIP_STATS_H=include\\lwip\stats.h include\\lwip\memp.h 
INCLUDE__LWIP_TCPIP_H=include\\lwip\tcpip.h include\\lwip\api_msg.h 
INCLUDE__LWIP_NETIF_H=include\\lwip\netif.h include\\lwip\dhcp.h 
NETIF_PPP_PPP_H=netif\ppp\ppp.h $(INCLUDE__LWIP_OPT_H) include\\lwip\sio.h \
	 $(INCLUDE__LWIP_API_H) include\\lwip\sockets.h \
	 $(INCLUDE__LWIP_STATS_H) include\\lwip\mem.h \
	 $(INCLUDE__LWIP_TCPIP_H) $(INCLUDE__LWIP_NETIF_H) 
INCLUDE_NETIF_FTMAC110_H=include\netif\ftmac110.h $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\gpioapi.h ..\inc\\sysapi.h 
INCLUDE__NETIF_ETHARP_H=include\\netif\etharp.h include\\lwip\pbuf.h \
	 include\\lwip\ip_addr.h $(INCLUDE__LWIP_NETIF_H) \
	 $(INCLUDE__LWIP_IP_H) include\\arch\bpstruct.h \
	 include\\arch\epstruct.h 
INCLUDE__LWIP_SNMP_H=include\\lwip\snmp.h $(INCLUDE__LWIP_NETIF_H) \
	 include\\lwip\udp.h 
INCLUDE__ARCH_CC_H=include\\arch\cc.h include\arch\cpu.h \
	 ..\inc\os\\os_cpu.h $(___INC_OS__UCOS_II_H) 
INCLUDE__LWIP_SNMP_ASN1_H=include\\lwip\snmp_asn1.h $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__ARCH_CC_H) include\\lwip\err.h include\\lwip\pbuf.h \
	 $(INCLUDE__LWIP_SNMP_H) 
INCLUDE__LWIP_SNMP_STRUCTS_H=include\\lwip\snmp_structs.h 
INCLUDE__LWIP_SNMP_MSG_H=include\\lwip\snmp_msg.h $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__ARCH_CC_H) $(INCLUDE__LWIP_SNMP_H) \
	 $(INCLUDE__LWIP_SNMP_STRUCTS_H) 
INCLUDE__LWIP_IP_FRAG_H=include\\lwip\ip_frag.h $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\err.h include\\lwip\pbuf.h $(INCLUDE__LWIP_NETIF_H) \
	 include\\lwip\ip_addr.h 
INCLUDE__NETIF_FTMAC110_H=include\\netif\ftmac110.h $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\gpioapi.h ..\inc\\sysapi.h 
INCLUDE__NETIF_LOOPIF_H=include\\netif\loopif.h $(INCLUDE__LWIP_NETIF_H) 
INCLUDE__NETIF_SLIPIF_H=include\\netif\slipif.h $(INCLUDE__LWIP_NETIF_H) 
# DEPEND: end include files

Release\handler_rtsp.o: .\rtsp\handler_rtsp.c $(___INC_OS__UCOS_II_H) \
	 $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\rtsp\handler_rtsp.c $(CARM) -o Release\handler_rtsp.o
Release\rtsp_method.o: .\rtsp\rtsp_method.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\rtsp\rtsp_method.c $(CARM) -o Release\rtsp_method.o
Release\rtcp.o: .\rtsp\rtcp.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\rtsp\rtcp.c \
	 $(CARM) -o Release\rtcp.o
Release\sdp.o: .\rtsp\sdp.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\rtsp\sdp.c \
	 $(CARM) -o Release\sdp.o
Release\rtp.o: .\rtsp\rtp.c $(___INC__GENERAL_H) include\lwip\rtp.h \
	 $(INCLUDE_LWIP_API_H) include\lwip\net.h ..\inc\\rfiuapi.h \
	 $(___INC__UIAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\rtsp\rtp.c \
	 $(CARM) -o Release\rtp.o
Release\P2P_server.o: tutk_P2P\P2P_server.c ..\inc\\rfiuapi.h \
	 ..\inc\\tutkiotcapi.h ..\inc\\tutkavapi.h \
	 include\tutk_p2p\avframeinfo.h include\tutk_p2p\avioctrldefs.h \
	 ..\inc\\gpiapi.h ..\inc\\lwipapi.h $(___INC__GLOBALVARIABLE_H) \
	 $(___INC__DCFAPI_H)  ..\inc\\p2pserver_api.h ..\inc\\ispapi.h   \
	 ..\inc\\timerapi.h ..\ui\inc\ui.h ..\ui\inc\ui_project.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 tutk_P2P\P2P_server.c $(CARM) -o Release\P2P_server.o
Release\md5.o: .\netif\ppp\md5.c $(NETIF_PPP_PPP_H) netif\ppp\md5.h \
	 netif\ppp\pppdebug.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\netif\ppp\md5.c \
	 $(CARM) -o Release\md5.o
Release\FTMAC110.o: .\netif\FTMAC110.C $(___INC__OSAPI_H) ..\inc\\task.h \
	 $(INCLUDE_NETIF_FTMAC110_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\netif\FTMAC110.C \
	 $(CARM) -o Release\FTMAC110.o
Release\dns_clinet.o: .\core\dns_clinet.c $(___INC_OS__UCOS_II_H) \
	 ..\inc\os\\os_cpu.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\dns_clinet.c $(CARM) -o Release\dns_clinet.o
Release\LwIPEntry.o: LwIPEntry.c $(___INC__GENERAL_H) \
	 $(INCLUDE__LWIP_OPT_H) include\\lwip\pbuf.h \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\mem.h $(___INC__UIAPI_H) \
	 ..\inc\\gpiapi.h ..\inc\\rtcapi.h ..\inc\\p2pserver_api.h \
	 include\\lwip\memp.h $(INCLUDE__LWIP_TCPIP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c LwIPEntry.c \
	 $(CARM) -o Release\LwIPEntry.o
Release\dhcp.o: .\core\dhcp.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\inet.h \
	 include\\lwip\udp.h include\\lwip\mem.h $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__NETIF_ETHARP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\dhcp.c \
	 $(CARM) -o Release\dhcp.o
Release\inet.o: .\core\inet.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\arch.h \
	 include\\lwip\def.h include\\lwip\inet.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\inet.c \
	 $(CARM) -o Release\inet.o
Release\mem.o: .\core\mem.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\arch.h \
	 include\\lwip\def.h include\\lwip\mem.h $(INCLUDE__LWIP_STATS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\mem.c \
	 $(CARM) -o Release\mem.o
Release\memp.o: .\core\memp.c $(INCLUDE__LWIP_OPT_H) $(INCLUDE__LWIP_API_H) \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_TCPIP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\memp.c \
	 $(CARM) -o Release\memp.o
Release\netif.o: .\core\netif.c include\\lwip\def.h include\\lwip\ip_addr.h \
	 $(INCLUDE__LWIP_TCP_H) $(INCLUDE__LWIP_SNMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\netif.c \
	 $(CARM) -o Release\netif.o
Release\pbuf.o: .\core\pbuf.c $(INCLUDE__LWIP_OPT_H) include\\lwip\pbuf.h \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\def.h include\\lwip\mem.h \
	 $(INCLUDE__LWIP_STATS_H) include\\arch\perf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\pbuf.c \
	 $(CARM) -o Release\pbuf.o
Release\raw.o: .\core\raw.c include\\lwip\def.h include\\lwip\ip_addr.h \
	 $(INCLUDE__LWIP_RAW_H) $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__LWIP_SNMP_H) include\\arch\perf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\raw.c \
	 $(CARM) -o Release\raw.o
Release\stats.o: .\core\stats.c $(INCLUDE__LWIP_OPT_H) include\\lwip\def.h \
	 include\\lwip\mem.h $(INCLUDE__LWIP_STATS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\stats.c \
	 $(CARM) -o Release\stats.o
Release\sys.o: .\core\sys.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\def.h include\\lwip\memp.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\sys.c \
	 $(CARM) -o Release\sys.o
Release\tcp.o: .\core\tcp.c include\\lwip\def.h $(INCLUDE__LWIP_TCP_H) \
	 include\\lwip\mem.h include\\lwip\memp.h $(INCLUDE__LWIP_SNMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\tcp.c \
	 $(CARM) -o Release\tcp.o
Release\tcp_in.o: .\core\tcp_in.c include\\lwip\def.h \
	 include\\lwip\ip_addr.h include\\lwip\inet.h \
	 $(INCLUDE__LWIP_TCP_H) include\\lwip\mem.h \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H) include\\arch\perf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\tcp_in.c \
	 $(CARM) -o Release\tcp_in.o
Release\tcp_out.o: .\core\tcp_out.c $(INCLUDE__LWIP_LWIPSYS_H) \
	 include\\lwip\def.h include\\lwip\ip_addr.h include\\lwip\inet.h \
	 $(INCLUDE__LWIP_TCP_H) include\\lwip\mem.h \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\tcp_out.c \
	 $(CARM) -o Release\tcp_out.o
Release\udp.o: .\core\udp.c include\\lwip\def.h include\\lwip\ip_addr.h \
	 include\\lwip\inet.h include\\lwip\icmp.h $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__LWIP_SNMP_H) include\\arch\perf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\udp.c \
	 $(CARM) -o Release\udp.o
Release\msg_out.o: .\core\snmp\msg_out.c $(INCLUDE__LWIP_SNMP_ASN1_H)  \
	 include\\lwip\snmp_msg.h include\\lwip\snmp_structs.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\msg_out.c $(CARM) -o Release\msg_out.o
Release\asn1_dec.o: .\core\snmp\asn1_dec.c $(INCLUDE__LWIP_SNMP_ASN1_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\asn1_dec.c $(CARM) -o Release\asn1_dec.o
Release\asn1_enc.o: .\core\snmp\asn1_enc.c $(INCLUDE__LWIP_SNMP_ASN1_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\asn1_enc.c $(CARM) -o Release\asn1_enc.o
Release\mib2.o: .\core\snmp\mib2.c $(INCLUDE__LWIP_TCP_H) \
	 $(INCLUDE__NETIF_ETHARP_H)  $(INCLUDE__LWIP_SNMP_STRUCTS_H)  \
	 ..\inc\os\\ucos_ii.h ..\inc\os\\os_cpu.h include\\lwip\opt.h \
	 include\\arch\cc.h include\arch\cpu.h include\\lwip\err.h \
	 include\\lwip\snmp.h include\\lwip\snmp_asn1.h \
	 include\\lwip\ip_frag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\snmp\mib2.c \
	 $(CARM) -o Release\mib2.o
Release\mib_structs.o: .\core\snmp\mib_structs.c $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\mem.h $(INCLUDE__LWIP_SNMP_STRUCTS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\mib_structs.c $(CARM) -o Release\mib_structs.o
Release\msg_in.o: .\core\snmp\msg_in.c include\\lwip\ip_addr.h \
	 include\\lwip\mem.h $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__LWIP_SNMP_ASN1_H)  include\\lwip\snmp_msg.h \
	 include\\lwip\snmp_structs.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\msg_in.c $(CARM) -o Release\msg_in.o
Release\sys_arch.o: .\arch\sys_arch.c $(___INC_OS__UCOS_II_H) ..\inc\\task.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\arch\sys_arch.c \
	 $(CARM) -o Release\sys_arch.o
Release\tcpip.o: .\api\tcpip.c $(INCLUDE__LWIP_LWIPSYS_H) \
	 $(INCLUDE__LWIP_IP_H) include\\lwip\udp.h $(INCLUDE__LWIP_TCP_H) \
	 include\\lwip\memp.h $(INCLUDE__LWIP_TCPIP_H) \
	 $(INCLUDE__LWIP_IP_FRAG_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\tcpip.c \
	 $(CARM) -o Release\tcpip.o
Release\api_lib.o: .\api\api_lib.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_API_H) include\\lwip\memp.h include\\lwip\api_msg.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\api_lib.c \
	 $(CARM) -o Release\api_lib.o
Release\api_msg.o: .\api\api_msg.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\arch.h \
	 include\\lwip\memp.h $(INCLUDE__LWIP_TCPIP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\api_msg.c \
	 $(CARM) -o Release\api_msg.o
Release\err.o: .\api\err.c include\\lwip\err.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\err.c \
	 $(CARM) -o Release\err.o
Release\sockets.o: .\api\sockets.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_API_H) include\\lwip\sockets.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\sockets.c \
	 $(CARM) -o Release\sockets.o
Release\etharp.o: .\netif\etharp.c $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\inet.h $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__NETIF_ETHARP_H)  include\\lwip\udp.h include\\lwip\snmp.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\netif\etharp.c \
	 $(CARM) -o Release\etharp.o
Release\ethernetif.o: .\netif\ethernetif.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__ARCH_CC_H) $(INCLUDE__LWIP_LWIPSYS_H) \
	 include\\lwip\mem.h ..\inc\\task.h $(INCLUDE__NETIF_ETHARP_H) \
	 include\\netif\dm9000.h $(INCLUDE__NETIF_FTMAC110_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\netif\ethernetif.c $(CARM) -o Release\ethernetif.o
Release\loopif.o: .\netif\loopif.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_IP_H) $(INCLUDE__LWIP_TCP_H) include\\lwip\mem.h \
	 $(INCLUDE__NETIF_LOOPIF_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\netif\loopif.c \
	 $(CARM) -o Release\loopif.o
Release\slipif.o: .\netif\slipif.c $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\pbuf.h $(INCLUDE__LWIP_LWIPSYS_H) \
	 include\\lwip\def.h include\\lwip\sio.h $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__NETIF_SLIPIF_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\netif\slipif.c \
	 $(CARM) -o Release\slipif.o
Release\converter.o: .\tools\converter.c $(___INC_OS__UCOS_II_H) \
	 tools\converter.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tools\converter.c $(CARM) -o Release\converter.o
Release\search.o: .\tools\search.c $(___INC_OS__UCOS_II_H) tools\search.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\tools\search.c \
	 $(CARM) -o Release\search.o
Release\stringExtAPI.o: .\tools\stringExtAPI.c $(___INC_OS__UCOS_II_H) \
	 tools\stringextapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tools\stringExtAPI.c $(CARM) -o Release\stringExtAPI.o
Release\handler_http.o: .\http\handler_http.c $(___INC_OS__UCOS_II_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\http\handler_http.c $(CARM) -o Release\handler_http.o
Release\icmp.o: .\core\ipv4\icmp.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_IP_H) include\\lwip\inet.h include\\lwip\icmp.h \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\ipv4\icmp.c \
	 $(CARM) -o Release\icmp.o
Release\ip.o: .\core\ipv4\ip.c $(INCLUDE__LWIP_IP_H) $(INCLUDE__LWIP_RAW_H) \
	 $(INCLUDE__LWIP_TCP_H) include\\lwip\mem.h \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H) \
	 include\\arch\perf.h  include\\lwip\opt.h include\\lwip\pbuf.h \
	 include\\lwip\ip_addr.h include\\lwip\err.h include\\lwip\ip_frag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\ipv4\ip.c \
	 $(CARM) -o Release\ip.o
Release\ip_addr.o: .\core\ipv4\ip_addr.c include\\lwip\ip_addr.h \
	 include\\lwip\inet.h $(INCLUDE__LWIP_NETIF_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\ipv4\ip_addr.c $(CARM) -o Release\ip_addr.o
Release\ip_frag.o: .\core\ipv4\ip_frag.c $(INCLUDE__LWIP_IP_H) \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H)  \
	 include\\lwip\opt.h include\\lwip\pbuf.h include\\lwip\ip_addr.h \
	 include\\lwip\err.h include\\lwip\ip_frag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\ipv4\ip_frag.c $(CARM) -o Release\ip_frag.o
