#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I.\inc -I..\common\inc -I..\..\inc

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I.\inc -I..\common\inc -I..\..\inc -g --dwarf2 -O1
CARM_SRCS	= 		  .\src\MultiChannelH264.c .\src\header.c \
		  .\src\nalu.c .\src\nal.c .\src\vlc.c \
		  .\src\parset.c .\src\H264.c .\src\H264RateControl.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  DebugRel\MultiChannelH264.o DebugRel\header.o \
		  DebugRel\nalu.o DebugRel\nal.o DebugRel\vlc.o \
		  DebugRel\parset.o DebugRel\H264.o \
		  DebugRel\H264RateControl.o 

CARM_CPP	=  -g --dwarf2 --cpp -O1
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2 -O1
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp -O1
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= H264_DebugRel.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\..\lib\H264.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 10
______INC_SYSOPT_H=..\..\inc\sysopt.h ..\..\inc\sysoptdef.h \
	 ..\..\inc\application.h ..\..\inc\project.h 
______INC_OSAPI_H=..\..\inc\osapi.h 
______INC_MEMORYPOOL_H=..\..\inc\memorypool.h ..\..\inc\iduapi.h \
	 ..\..\inc\mpeg4api.h ..\..\inc\iisapi.h 
______INC_GENERAL_H=..\..\inc\general.h $(______INC_SYSOPT_H) \
	 ..\..\inc\awbdef.h $(______INC_OSAPI_H) $(______INC_MEMORYPOOL_H) 
______INC_VIDEOCODECAPI_H=..\..\inc\videocodecapi.h ..\..\inc\mpeg4api.h 
___COMMON_INC_VIDEOCODEC_COMMON_H=..\common\inc\videocodec_common.h \
	 $(______INC_VIDEOCODECAPI_H) 
INC_NALU_H=inc\nalu.h inc\nalucommon.h 
______INC_H264API_H=..\..\inc\h264api.h $(______INC_VIDEOCODECAPI_H) 
______INC_FSAPI_H=..\..\inc\fsapi.h $(______INC_SYSOPT_H) 
______INC_DCFAPI_H=..\..\inc\dcfapi.h ..\..\inc\sdcapi.h 
INC_PARSET_H=inc\parset.h inc\h264.h inc\parsetcommon.h inc\nalucommon.h \
	 $(______INC_H264API_H) 
INC_HEADER_H=inc\header.h inc\nalucommon.h 
______INC_ASFAPI_H=..\..\inc\asfapi.h $(______INC_FSAPI_H) \
	 ..\..\asf\inc\asf.h 
INC_NAL_H=inc\nal.h inc\vlc.h 
# DEPEND: end include files

DebugRel\MultiChannelH264.o: .\src\MultiChannelH264.c \
	 $(______INC_GENERAL_H) ..\..\inc\board.h ..\..\inc\task.h  \
	 $(INC_NALU_H) inc\h264reg.h $(______INC_DCFAPI_H)  inc\vlc.h  \
	 ..\..\inc\isuapi.h $(______INC_ASFAPI_H) ..\..\inc\sysapi.h \
	 ..\..\inc\rfiuapi.h ..\..\inc\ciuapi.h \
	 ..\common\inc\videocodec_common.h ..\..\inc\videocodecapi.h \
	 inc\h264.h ..\..\inc\h264api.h inc\parset.h inc\parsetcommon.h \
	 inc\header.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\MultiChannelH264.c $(CARM) -o DebugRel\MultiChannelH264.o
DebugRel\header.o: .\src\header.c $(______INC_GENERAL_H) inc\parsetcommon.h \
	 inc\vlc.h $(INC_HEADER_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\header.c \
	 $(CARM) -o DebugRel\header.o
DebugRel\nalu.o: .\src\nalu.c $(______INC_GENERAL_H) ..\..\inc\board.h \
	 $(INC_NALU_H) $(______INC_H264API_H) $(INC_NAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\nalu.c \
	 $(CARM) -o DebugRel\nalu.o
DebugRel\nal.o: .\src\nal.c $(______INC_GENERAL_H) $(INC_NALU_H) inc\vlc.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\nal.c \
	 $(CARM) -o DebugRel\nal.o
DebugRel\vlc.o: .\src\vlc.c $(______INC_GENERAL_H) ..\..\inc\board.h \
	 $(______INC_H264API_H) inc\vlc.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\vlc.c \
	 $(CARM) -o DebugRel\vlc.o
DebugRel\parset.o: .\src\parset.c $(______INC_GENERAL_H) ..\..\inc\board.h \
	 $(INC_NALU_H)  $(INC_NAL_H) ..\..\idu\inc\idureg.h inc\h264.h \
	 ..\..\inc\h264api.h inc\parset.h inc\parsetcommon.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\parset.c \
	 $(CARM) -o DebugRel\parset.o
DebugRel\H264.o: .\src\H264.c $(______INC_GENERAL_H) ..\..\inc\board.h \
	 ..\..\inc\task.h  $(INC_NALU_H) inc\h264reg.h \
	 $(______INC_DCFAPI_H)  inc\vlc.h  ..\..\inc\isuapi.h \
	 $(______INC_ASFAPI_H) ..\..\inc\sysapi.h ..\..\inc\rfiuapi.h \
	 ..\..\inc\ciuapi.h ..\common\inc\videocodec_common.h \
	 ..\..\inc\videocodecapi.h inc\h264.h ..\..\inc\h264api.h \
	 inc\parset.h inc\parsetcommon.h inc\header.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\H264.c \
	 $(CARM) -o DebugRel\H264.o
DebugRel\H264RateControl.o: .\src\H264RateControl.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\H264RateControl.c $(CARM) -o DebugRel\H264RateControl.o
