#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ --no_debug --dwarf2 -O3
CARM_SRCS	= 		  .\src\exif.c .\src\dcffs.c .\src\dcf.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\exif.o Release\dcffs.o Release\dcf.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= dcf_Release.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\dcf.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 36
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\project.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__MEMORYPOOL_H=..\inc\\memorypool.h ..\inc\\iduapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) $(___INC__MEMORYPOOL_H) 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__SMCAPI_H=..\inc\\smcapi.h $(___INC__GENERAL_H) 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\task.h ..\inc\\rtcapi.h \
	 ..\inc\\uikey.h 
# DEPEND: end include files

Release\exif.o: .\src\exif.c $(___INC__GENERAL_H) ..\inc\\board.h  \
	 ..\inc\\rtcapi.h $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\isuapi.h ..\inc\\ipuapi.h $(___INC__SIUAPI_H) \
	 ..\inc\\sysapi.h ..\inc\\fsapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\exif.c \
	 $(CARM) -o Release\exif.o
Release\dcffs.o: .\src\dcffs.c $(___INC__GENERAL_H) ..\inc\\board.h  \
	 ..\inc\\rtcapi.h $(___INC__DCFAPI_H) $(___INC__SIUAPI_H) \
	 ..\inc\\sysapi.h ..\inc\\gpioapi.h ..\inc\\iisapi.h ..\inc\\fsapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\dcffs.c \
	 $(CARM) -o Release\dcffs.o
Release\dcf.o: .\src\dcf.c ..\inc\\board.h $(___INC__FSAPI_H) \
	 $(___INC__DCFAPI_H) ..\inc\\sysapi.h ..\inc\\gpioapi.h \
	 ..\inc\\ramdiskapi.h $(___INC__SMCAPI_H) ..\inc\\spiapi.h \
	 $(___INC__UIAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\dcf.c \
	 $(CARM) -o Release\dcf.o
