#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ -g --dwarf2
CARM_SRCS	= 		  .\src\usbvc.c .\src\usb_Hostintevt.c \
		  .\src\usb_Host.c .\src\usb_Device_msc.c \
		  .\src\usb_Device.c .\src\usbmsccb.c \
		  .\src\usbapiex.c .\src\usbmscfs.c .\src\usbclass.c \
		  .\src\usbdesc.c .\src\usbmsc.c .\src\usbintevt.c \
		  .\src\usbdev.c .\src\usbcb.c .\src\usbapievt.c \
		  .\src\usb.c .\src\usb_Host_EHCI.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Debug\usbvc.o Debug\usb_Hostintevt.o \
		  Debug\usb_Host.o Debug\usb_Device_msc.o \
		  Debug\usb_Device.o Debug\usbmsccb.o \
		  Debug\usbapiex.o Debug\usbmscfs.o Debug\usbclass.o \
		  Debug\usbdesc.o Debug\usbmsc.o Debug\usbintevt.o \
		  Debug\usbdev.o Debug\usbcb.o Debug\usbapievt.o \
		  Debug\usb.o Debug\usb_Host_EHCI.o 

CARM_CPP	=  -g --dwarf2 --cpp
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= usb_Debug.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\usb.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 7
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\application.h \
	 ..\inc\\project.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__MEMORYPOOL_H=..\inc\\memorypool.h ..\inc\\iduapi.h \
	 ..\inc\\mpeg4api.h ..\inc\\iisapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) $(___INC__MEMORYPOOL_H) 
INC__USBVC_H=inc\\usbvc.h inc\\usb_dev_pcam_alt0.h inc\\usb_dev_pcam_alt1.h \
	 inc\\usb_dev_pcam_alt2.h inc\\usb_dev_pcam_alt3.h \
	 inc\\usb_dev_pcam_alt4.h inc\\usb_dev_pcam_alt5.h \
	 inc\\usb_dev_pcam_alt6.h inc\\usb_dev_pcam_alt7.h \
	 inc\\usb_dev_pcam_alt8.h 
___INC__SYSAPI_H=..\inc\\sysapi.h 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\task.h ..\inc\\uikey.h \
	 ..\inc\\rfiuapi.h 
INC__USBDESC_H=inc\\usbdesc.h inc\\usbmsc.h 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) 
# DEPEND: end include files

Debug\usbvc.o: .\src\usbvc.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h $(INC__USBVC_H) inc\\usbreg.h \
	 inc\\usbdev.h inc\\usbapievt.h inc\\usbintevt.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbvc.c \
	 $(CARM) -o Debug\usbvc.o
Debug\usb_Hostintevt.o: .\src\usb_Hostintevt.c $(___INC__GENERAL_H) \
	 ..\inc\\task.h ..\inc\\board.h inc\\usbhost.h inc\\usbhost_msc.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\usb_Hostintevt.c $(CARM) -o Debug\usb_Hostintevt.o
Debug\usb_Host.o: .\src\usb_Host.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usbhost.h inc\\usbhost_msc.h \
	 inc\\usb_host_event.h ..\inc\\gpioapi.h ..\inc\\sdcapi.h \
	 $(___INC__SYSAPI_H) inc\\ehic.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usb_Host.c \
	 $(CARM) -o Debug\usb_Host.o
Debug\usb_Device_msc.o: .\src\usb_Device_msc.c $(___INC__GENERAL_H) \
	 ..\inc\\task.h ..\inc\\board.h inc\\usb_device.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\usb_Device_msc.c $(CARM) -o Debug\usb_Device_msc.o
Debug\usb_Device.o: .\src\usb_Device.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h inc\\usbreg.h inc\\usbapievt.h \
	 ..\inc\\gpioapi.h ..\inc\\sdcapi.h $(___INC__SYSAPI_H) \
	 inc\\usb_device.h inc\\usbotgreg.h inc\\usbhostintevt.h \
	 ..\inc\\usbapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usb_Device.c \
	 $(CARM) -o Debug\usb_Device.o
Debug\usbmsccb.o: .\src\usbmsccb.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h inc\\usbdev.h inc\\usbapiex.h \
	 inc\\usbcb.h inc\\usbmsc.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbmsccb.c \
	 $(CARM) -o Debug\usbmsccb.o
Debug\usbapiex.o: .\src\usbapiex.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h inc\\usbreg.h inc\\usbdev.h \
	 inc\\usbapievt.h inc\\usbapiex.h inc\\usbcb.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbapiex.c \
	 $(CARM) -o Debug\usbapiex.o
Debug\usbmscfs.o: .\src\usbmscfs.c $(___INC__GENERAL_H) ..\inc\\board.h \
	 inc\\usb.h ..\inc\\sdcapi.h $(___INC__SYSAPI_H) ..\inc\\usbapi.h \
	 inc\\usbmsc.h $(___INC__UIAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbmscfs.c \
	 $(CARM) -o Debug\usbmscfs.o
Debug\usbclass.o: .\src\usbclass.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h $(INC__USBVC_H) inc\\usbdev.h \
	 $(INC__USBDESC_H) inc\\usbclass.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbclass.c \
	 $(CARM) -o Debug\usbclass.o
Debug\usbdesc.o: .\src\usbdesc.c $(___INC__GENERAL_H) inc\\usb.h \
	 $(INC__USBVC_H) $(INC__USBDESC_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbdesc.c \
	 $(CARM) -o Debug\usbdesc.o
Debug\usbmsc.o: .\src\usbmsc.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h inc\\usbreg.h inc\\usbdev.h \
	 ..\inc\\usbapi.h inc\\usbapiex.h inc\\usbmsc.h inc\\scsi.h  \
	 ..\inc\\fsapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbmsc.c \
	 $(CARM) -o Debug\usbmsc.o
Debug\usbintevt.o: .\src\usbintevt.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h inc\\usbreg.h inc\\usbdev.h \
	 inc\\usbintevt.h ..\inc\\usbapi.h inc\\usbcb.h $(INC__USBDESC_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbintevt.c \
	 $(CARM) -o Debug\usbintevt.o
Debug\usbdev.o: .\src\usbdev.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h inc\\usbreg.h inc\\usbdev.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbdev.c \
	 $(CARM) -o Debug\usbdev.o
Debug\usbcb.o: .\src\usbcb.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h inc\\usbreg.h inc\\usbdev.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbcb.c \
	 $(CARM) -o Debug\usbcb.o
Debug\usbapievt.o: .\src\usbapievt.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h inc\\usbreg.h inc\\usbdev.h \
	 inc\\usbapievt.h inc\\usbcb.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usbapievt.c \
	 $(CARM) -o Debug\usbapievt.o
Debug\usb.o: .\src\usb.c $(___INC__GENERAL_H) ..\inc\\task.h \
	 ..\inc\\board.h inc\\usb.h inc\\usbreg.h inc\\usbdev.h \
	 inc\\usbapievt.h inc\\usbintevt.h ..\inc\\gpioapi.h \
	 ..\inc\\sdcapi.h $(___INC__SYSAPI_H) ..\inc\\usbapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\usb.c \
	 $(CARM) -o Debug\usb.o
Debug\usb_Host_EHCI.o: .\src\usb_Host_EHCI.c $(___INC__GENERAL_H) \
	 ..\inc\\task.h ..\inc\\board.h inc\\usbhost.h inc\\ehic.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\usb_Host_EHCI.c $(CARM) -o Debug\usb_Host_EHCI.o
