/*

Copyright (c) 2008 Mars Semiconductor Corp.

Module Name:

    uiapi.h

Abstract:

    The application interface of user interface.

Environment:

        ARM RealView Developer Suite

Revision History:

    2005/08/26  David Tsai  Create

*/

#ifndef __UIACT_MR6790E_H__
#define __UIACT_MR6790E_H__

/* Constant definition */

#define UI_PLAYBACK_SPEED_LEVEL     10

enum
{
    UI_MENU_DELETE_YES = 0,
    UI_MENU_DELETE_NO,
};

enum 
{
    UI_MENU_VIDEO_QUALITY_HIGH = 0,
    UI_MENU_VIDEO_QUALITY_MEDIUM,
    UI_MENU_VIDEO_QUALITY_LOW,
};

enum 
{
    UI_MENU_VIDEO_FRAMERATE_30 = 0,
    UI_MENU_VIDEO_FRAMERATE_15,
    UI_MENU_VIDEO_FRAMERATE_5,
    UI_MENU_VIDEO_FRAMERATE_10,
};

enum
{
    UI_MENU_SETTING_RESOLUTION_1920x1088=0,
    UI_MENU_SETTING_RESOLUTION_HD,
    UI_MENU_SETTING_RESOLUTION_QHD,
	UI_MENU_SETTING_RESOLUTION_QVGA,
	UI_MENU_SETTING_RESOLUTION_D1,
};
enum
{
    UI_MENU_VIDEO_OVERWRITESTR_ALL = 0,
    UI_MENU_VIDEO_OVERWRITESTR_TIMEONLY,
    UI_MENU_VIDEO_OVERWRITESTR_NONE,
};
enum
{
    UI_MENU_SETTING_OVERWRITE_YES = 0,
    UI_MENU_SETTING_OVERWRITE_NO,
};

enum 
{
    UI_MENU_SETTING_SECTION_5MIN = 0,
    UI_MENU_SETTING_SECTION_10MIN,
    UI_MENU_SETTING_SECTION_15MIN,
};

enum
{
    UI_MENU_SETTING_CHANNEL_1 = 0,
    UI_MENU_SETTING_CHANNEL_2,
};

enum
{    
    UI_MENU_REC_MODE_MANUAL =0 ,
    UI_MENU_REC_MODE_MOTION,    
    UI_MENU_REC_MODE_SCHEDULE,        
    UI_MENU_REC_MODE_NONE,

};

enum
{
    UI_MENU_FORMAT_YES= 0,
    UI_MENU_FORMAT_NO

};

enum
{
    UI_MENU_TV = 0,
    UI_MENU_PANEL,
    UI_MENU_SET_PANEL,
};

enum
{
    UI_AUDIO_RESOLUTION_8BIT = 0,
    UI_AUDIO_RESOLUTION_16BIT,
};

enum
{
    UI_AUDIO_SAMPLING_8K = 0,
    UI_AUDIO_SAMPLING_16K,
    UI_AUDIO_SAMPLING_32K,
    UI_AUDIO_SAMPLING_44K,
    UI_AUDIO_SAMPLING_48K,
};

enum
{
    UI_MENU_SETTING_MOTION_SENSITIVITY_H = 0,
    UI_MENU_SETTING_MOTION_SENSITIVITY_M,
    UI_MENU_SETTING_MOTION_SENSITIVITY_L,
};

enum
{
    UI_MENU_CHANNEL_ADD= 0,
    UI_MENU_CHANNEL_SUB,
    UI_MENU_CHANNEL_1,
    UI_MENU_CHANNEL_2,
    UI_MENU_CHANNEL_3,
    UI_MENU_CHANNEL_4,
    UI_MENU_CHANNEL_SCAN
};

enum
{
    UI_MENU_RF_QUAD= 0,
    UI_MENU_RF_FULL,
    UI_MENU_RF_DUAL,
    UI_MENU_RF_ENTER_PLAYBACK,
    UI_MENU_RF_ENTER_SETUP,
    UI_MENU_RF_ENTER_MASKAREA
};

enum
{
    UI_MENU_CH1= 0,
    UI_MENU_CH2,
    UI_MENU_CH3,
    UI_MENU_CH4,

};

enum
{
    UI_MENU_NTSC =0,
    UI_MENU_PAL,
    UI_MENU_PANEL_OUT,
};

enum
{
    UI_MENU_SETTING_LANGUAGE_ENGLISH = 0,
    UI_MENU_SETTING_LANGUAGE_SPANISH,
#if(UI_OTHER_LANGUAGE == 1)
    UI_MENU_SETTING_LANGUAGE_JAPANSE,
#elif(UI_OTHER_LANGUAGE == 2)
    UI_MENU_SETTING_LANGUAGE_FRANCE,
    UI_MENU_SETTING_LANGUAGE_GERMANY,
    UI_MENU_SETTING_LANGUAGE_ITALY,
#endif
	
};

enum
{
    UI_MENU_DYNAMIC_IP=0,
    UI_MENU_STATIC_IP,
};

enum
{
    UI_MENU_TX_MOTION_OFF =0,
    UI_MENU_TX_MOTION_ON,
};

enum 
{
    UI_MENU_SETTING_CAMERA_OFF =0,
	UI_MENU_SETTING_CAMERA_ON,
};

enum 
{
    UI_MENU_SETTING_FLICKER_50HZ =0,
	UI_MENU_SETTING_FLICKER_60HZ,
};

enum 
{
    UI_MENU_SETTING_SENSITIVITY_HIGHT =0,
	UI_MENU_SETTING_SENSITIVITY_MID,
	UI_MENU_SETTING_SENSITIVITY_LOW,
	UI_MENU_SETTING_SENSITIVITY_OFF,
};


enum
{
    UI_MENU_SWITCH_OFF =0,
    UI_MENU_SWITCH_ON,
};

enum 
{
    UI_MENU_SETTING_BRIGHTNESS_LV1 =0,
	UI_MENU_SETTING_BRIGHTNESS_LV2 ,
	UI_MENU_SETTING_BRIGHTNESS_LV3 ,
	UI_MENU_SETTING_BRIGHTNESS_LV4 ,
	UI_MENU_SETTING_BRIGHTNESS_LV5 ,
	UI_MENU_SETTING_BRIGHTNESS_LV6 ,
	UI_MENU_SETTING_BRIGHTNESS_LV7 ,
	UI_MENU_SETTING_BRIGHTNESS_LV8 ,
};


enum
{
    UI_MENU_SCHEDULE_OFF =0,
    UI_MENU_SCHEDULE_REC,
};

enum
{
    UI_MENU_UPDATE_YES = 0,
    UI_MENU_UPDATE_NO,
};

enum
{
    UI_MENU_DEFAULT_YES = 0,
    UI_MENU_DEFAULT_NO,
};
enum
{
    UI_MENU_NTPTIME_OFF = 0,
    UI_MENU_NTPTIME_ON,
};
enum
{
    UI_MENU_ALARM_YES = 0,
    UI_MENU_ALARM_NO,
};
enum 
{
    UI_MENU_VOL_LV0 =0,
    UI_MENU_VOL_LV1,
    UI_MENU_VOL_LV2,
    UI_MENU_VOL_LV3,
    UI_MENU_VOL_LV4,
    UI_MENU_VOL_LV5,
    UI_MENU_VOL_LV6,
    UI_MENU_VOL_LV7,
    UI_MENU_VOL_LV8,
    UI_MENU_VOL_LV9,
    

};

enum
{
    UI_MENU_ALERT_MEOLDY_1 =0,
    UI_MENU_ALERT_MEOLDY_2,
    UI_MENU_ALERT_MEOLDY_3,
    UI_MENU_ALERT_MEOLDY_NONE,     
};

enum
{
    UI_MENU_ALERT_VOL_1=0,
    UI_MENU_ALERT_VOL_2,
    UI_MENU_ALERT_VOL_3,
    UI_MENU_ALERT_VOL_NONE,
};


enum
{
    UI_MENU_ALERT_PERIOD_15s =0,
    UI_MENU_ALERT_PERIOD_30s,
    UI_MENU_ALERT_PERIOD_60s,

};
enum
{
    UI_MENU_POWER_SAVING_3min =0,
    UI_MENU_POWER_SAVING_10min,
    UI_MENU_POWER_SAVING_OFF,

};


enum
{
    UI_MENU_LOADING_20_PCT =0,
    UI_MENU_LOADING_40_PCT,
    UI_MENU_LOADING_60_PCT,
    UI_MENU_LOADING_80_PCT,
    UI_MENU_LOADING_100_PCT,
    UI_MENU_LOADING_SUCCESS,
    UI_MENU_LOADING_FAIL,
    UI_MENU_UPDATE_NO_FILE,

};


enum
{
    UI_REC_TYPE_MANUAL=0,
    UI_REC_TYPE_MOTION,
    UI_REC_TYPE_SCHEDULE,
    UI_REC_TYPE_PIR,
    UI_REC_TYPE_NONE,
};

enum
{
    UI_ALERT_TYPE_MOTION=0,
    UI_ALERT_TYPE_UNLINK,
    UI_ALERT_TYPE_BATLOW,
    UI_ALERT_TYPE_NONE,
    UI_ALERT_TYPE_BATLOW_NONE,
};


enum
{
    UI_BEEP_NONE=0,
    UI_BEEP_CHANGE,
    UI_BEEP_CYCLE,
    UI_BEEP_GET_TYPE,
};

enum
{
    UI_MENU_SENSOR_FLICKER_60HZ = 0,
    UI_MENU_SENSOR_FLICKER_50HZ,
};

enum
{
    UI_MENU_CAMERA_ALARM_OFF = 0,
    UI_MENU_CAMERA_ALARM_ON,
};

enum
{
    UI_MENU_SETIDX_NTP_YES = 0,
    UI_MENU_SETIDX_NTP_NO,
};

enum
{
    UI_MENU_LOADING_1 =0,
    UI_MENU_LOADING_2,
    UI_MENU_LOADING_3,
    UI_MENU_LOADING_4,
    UI_MENU_LOADING_5,
    UI_MENU_LOADING_6,
};

#define UI_MENU_SETTING_TV_OUT_NTSC  SYS_TV_OUT_NTSC //Lucian: 統一定義 for whole system
#define UI_MENU_SETTING_TV_OUT_PAL   SYS_TV_OUT_PAL
#define UI_MENU_SETTING_PANEL_OUT    2

#if(Sensor_OPTION == Sensor_MI_5M)
#define UI_MENU_IMAGE_SIZE_4000x3000        0x00
#define UI_MENU_IMAGE_SIZE_2560x1920        0x01
#define UI_MENU_IMAGE_SIZE_1920x1440        0x02
#define UI_MENU_IMAGE_SIZE_1600x1200        0x03
#define UI_MENU_IMAGE_SIZE_800x600          0x04
#define UI_MENU_IMAGE_SIZE_640x480          0x05

#elif(Sensor_OPTION == Sensor_MI_2M)
#define UI_MENU_IMAGE_SIZE_1600x1200        0x00
#define UI_MENU_IMAGE_SIZE_800x600          0x01
#define UI_MENU_IMAGE_SIZE_640x480          0x02

#elif( (Sensor_OPTION == Sensor_OV7725_VGA) || (Sensor_OPTION == Sensor_OV7725_YUV601) || (Sensor_OPTION ==Sensor_OV7740_YUV601) || (Sensor_OPTION == Sensor_OV7740_RAW) || (Sensor_OPTION == Sensor_MI9V136_YUV601) || (Sensor_OPTION == Sensor_PC1089_YUV601) )
#define UI_MENU_IMAGE_SIZE_640x480      0x00

#elif( (Sensor_OPTION == Sensor_MI1320_YUV601) || (Sensor_OPTION == Sensor_MI1320_RAW) || (Sensor_OPTION == Sensor_OV2643_YUV601) || (Sensor_OPTION == Sensor_MT9M131_YUV601) || (Sensor_OPTION == Sensor_HM1375_YUV601) )
#define UI_MENU_IMAGE_SIZE_640x480      0x00

#elif(Sensor_OPTION == Sensor_CCIR656)
#define UI_MENU_IMAGE_SIZE_640x480          0x00

#elif(Sensor_OPTION == Sensor_CCIR601)
#define UI_MENU_IMAGE_SIZE_640x480          0x00
#endif

#define UI_ALERT_STATUS_BATTERY_LOW            0x01
#define UI_ALERT_STATUS_MOTION                 0x02
#define UI_ALERT_STATUS_UNLINK                 0x04



extern  u8 Current_Alarm_Period;

#if UI_LIGHT_SUPPORT
enum
{
    UI_MENU_SETIDX_LS_DUR_OFF = 0,
    UI_MENU_SETIDX_LS_DUR_1MIN,
    UI_MENU_SETIDX_LS_DUR_3MIN,
    UI_MENU_SETIDX_LS_DUR_10MIN,
};
enum
{
    UI_MENU_SETIDX_LS_DIMR_025 = 0,
    UI_MENU_SETIDX_LS_DIMR_050,
    UI_MENU_SETIDX_LS_DIMR_075,
    UI_MENU_SETIDX_LS_DIMR_100,
};
#endif


#endif

