#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc -I..\..\inc

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc -I..\..\inc -g --dwarf2
CARM_SRCS	= 		  .\src\SDK_record.c .\src\SDK_playback.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Debug\SDK_record.o Debug\SDK_playback.o 

CARM_CPP	=  -g --dwarf2 --cpp
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= SDK_Debug.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\SDK.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 15
___INC_SYSOPT_H=..\inc\sysopt.h ..\inc\sysoptdef.h ..\inc\application.h \
	 ..\inc\project.h 
___INC_GENERAL_H=..\inc\general.h $(___INC_SYSOPT_H) ..\inc\awbdef.h 
___LWIP_INCLUDE_TUTK_P2P_MR8200DEF_HOMEAUTOMATION_H= \
	..\lwip\include\tutk_p2p\mr8200def_homeautomation.h 
___INC_SYSAPI_H=..\inc\sysapi.h \
	 $(___LWIP_INCLUDE_TUTK_P2P_MR8200DEF_HOMEAUTOMATION_H) 
___INC_FSAPI_H=..\inc\fsapi.h 
___INC_ASFAPI_H=..\inc\asfapi.h $(___INC_FSAPI_H) ..\asf\inc\asf.h 
___INC_ADCAPI_H=..\inc\adcapi.h ..\adc\inc\adcreg.h 
___INC_DCFAPI_H=..\inc\dcfapi.h ..\inc\sdcapi.h 
___INC_SIUAPI_H=..\inc\siuapi.h ..\inc\motiondetect_api.h 
___INC_OSAPI_H=..\inc\osapi.h 
___INC_UIAPI_H=..\inc\uiapi.h ..\inc\uikey.h 
___INC_H264API_H=..\inc\h264api.h ..\inc\videocodecapi.h 
___VIDEOCODEC_H264_INC_PARSET_H=..\videocodec\h264\inc\parset.h 
___INC_GLOBALVARIABLE_H=..\inc\globalvariable.h $(___INC_GENERAL_H) \
	 ..\inc\board.h ..\inc\task.h ..\inc\mp4api.h $(___INC_ASFAPI_H) \
	 ..\inc\aviapi.h ..\inc\mpeg4api.h ..\videocodec\mpeg4\inc\mpeg4.h \
	 ..\videocodec\mpeg4\inc\mpeg4reg.h ..\inc\isuapi.h ..\inc\iduapi.h \
	 ..\inc\gpioapi.h $(___INC_SIUAPI_H) $(___INC_SYSAPI_H) \
	 $(___INC_OSAPI_H) ..\inc\rtcapi.h \
	 ..\videocodec\mpeg4\inc\mp4ratecontrol.h ..\inc\i2capi.h \
	 $(___INC_UIAPI_H) ..\inc\memorypool.h ..\inc\iisapi.h \
	 $(___INC_H264API_H) $(___VIDEOCODEC_H264_INC_PARSET_H) 
# DEPEND: end include files

Debug\SDK_record.o: .\src\SDK_record.c $(___INC_ADCAPI_H) \
	 $(___INC_DCFAPI_H) $(___INC_GLOBALVARIABLE_H) ..\inc\sdk_recordapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\SDK_record.c \
	 $(CARM) -o Debug\SDK_record.o
Debug\SDK_playback.o: .\src\SDK_playback.c $(___INC_ADCAPI_H) \
	 $(___INC_DCFAPI_H) $(___INC_GLOBALVARIABLE_H) \
	 ..\inc\sdk_playbackapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\SDK_playback.c $(CARM) -o Debug\SDK_playback.o
