#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I.\inc\ -I..\..\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I.\inc\ -I..\..\inc\ --no_debug --dwarf2 -O3
CARM_SRCS	= 		  .\src\MultiChannelMPEG4.c .\src\Mp4RateControl.c \
		  .\src\mpeg4.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\MultiChannelMPEG4.o Release\Mp4RateControl.o \
		  Release\mpeg4.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= mpeg4_Release.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Release\..\..\..\lib\mpeg4.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 36
#   Selected list: ..\idu\inc\idureg.h 
______INC__SYSOPT_H=..\..\inc\\sysopt.h ..\..\inc\\sysoptdef.h \
	 ..\..\inc\\project.h 
______INC__GENERAL_H=..\..\inc\\general.h $(______INC__SYSOPT_H) \
	 ..\..\inc\\awbdef.h 
______INC__FSAPI_H=..\..\inc\\fsapi.h 
______INC__ASFAPI_H=..\..\inc\\asfapi.h $(______INC__FSAPI_H) 
______INC__SIUAPI_H=..\..\inc\\siuapi.h ..\..\inc\\motiondetect_api.h 
______INC__UIAPI_H=..\..\inc\\uiapi.h ..\..\inc\\uikey.h 
______INC__OSAPI_H=..\..\inc\\osapi.h 
______INC__GLOBALVARIABLE_H=..\..\inc\\globalvariable.h \
	 $(______INC__GENERAL_H) ..\..\inc\\board.h ..\..\inc\\task.h \
	 ..\..\inc\\mp4api.h $(______INC__ASFAPI_H) ..\..\inc\\aviapi.h \
	 ..\..\inc\\mpeg4api.h ..\..\inc\\isuapi.h ..\..\inc\\iduapi.h \
	 ..\..\inc\\gpioapi.h $(______INC__SIUAPI_H) ..\..\inc\\sysapi.h \
	 $(______INC__OSAPI_H) ..\..\inc\\rtcapi.h ..\..\inc\\i2capi.h \
	 $(______INC__UIAPI_H) ..\..\inc\\memorypool.h ..\..\inc\\iisapi.h 
# DEPEND: end include files

Release\MultiChannelMPEG4.o: .\src\MultiChannelMPEG4.c inc\\mpeg4.h \
	 inc\\mpeg4reg.h inc\\mp4ratecontrol.h ..\..\inc\\ciuapi.h \
	 $(______INC__GLOBALVARIABLE_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\MultiChannelMPEG4.c $(CARM) -o Release\MultiChannelMPEG4.o
Release\Mp4RateControl.o: .\src\Mp4RateControl.c $(______INC__GENERAL_H) \
	 inc\\mp4ratecontrol.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\Mp4RateControl.c $(CARM) -o Release\Mp4RateControl.o
Release\mpeg4.o: .\src\mpeg4.c $(______INC__GENERAL_H) \
	 $(______INC__OSAPI_H) ..\..\inc\\board.h ..\..\inc\\task.h \
	 ..\..\inc\\mp4api.h $(______INC__ASFAPI_H) ..\..\inc\\aviapi.h \
	 inc\\mpeg4.h inc\\mpeg4reg.h ..\..\inc\\mpeg4api.h \
	 ..\..\inc\\isuapi.h ..\..\inc\\gpioapi.h $(______INC__SIUAPI_H) \
	 ..\..\inc\\sysapi.h ..\..\inc\\rtcapi.h inc\\mp4ratecontrol.h \
	 ..\..\inc\\i2capi.h $(______INC__UIAPI_H) ..\..\inc\\ciuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\mpeg4.c \
	 $(CARM) -o Release\mpeg4.o
