#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ -g --dwarf2
CARM_SRCS	= 		  src\MotionDetect_API.c src\siu_OV7740_YUV.c \
		  src\siu_OV7725_YUV.c src\siu_MI1320.c \
		  src\siu_MotionDetect.c src\siu_CCIR656.c \
		  src\siu_OV7725.c src\AWB.c src\siu_AF_ZOOM.c \
		  src\siumem.c src\siu_5M.c src\siu_2M.c \
		  .\src\compdefectpix.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Debug\MotionDetect_API.o Debug\siu_OV7740_YUV.o \
		  Debug\siu_OV7725_YUV.o Debug\siu_MI1320.o \
		  Debug\siu_MotionDetect.o Debug\siu_CCIR656.o \
		  Debug\siu_OV7725.o Debug\AWB.o Debug\siu_AF_ZOOM.o \
		  Debug\siumem.o Debug\siu_5M.o Debug\siu_2M.o \
		  Debug\compdefectpix.o 

CARM_CPP	=  -g --dwarf2 --cpp
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= siu_release_Debug.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Release\..\..\lib\release\siu_release.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 40
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) ..\inc\\memorypool.h 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__I2CAPI_H=..\inc\\i2capi.h ..\inc\\rtcapi.h 
___INC__ISUAPI_H=..\inc\\isuapi.h 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) ..\fs\inc\fs_fat.h 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\task.h ..\inc\\rtcapi.h 
___INC__IISAPI_H=..\inc\\iisapi.h 
___INC__TIMERAPI_H=..\inc\\timerapi.h 
___INC__ASFAPI_H=..\inc\\asfapi.h $(___INC__FSAPI_H) 
___INC__SMCAPI_H=..\inc\\smcapi.h $(___INC__GENERAL_H) 
# DEPEND: end include files

Debug\MotionDetect_API.o: src\MotionDetect_API.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\sysapi.h $(___INC__SIUAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\MotionDetect_API.c $(CARM) -o Debug\MotionDetect_API.o
Debug\siu_OV7740_YUV.o: src\siu_OV7740_YUV.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\sysapi.h $(___INC__SIUAPI_H) inc\\siu.h \
	 inc\\siureg.h ..\inc\\sensorapi.h $(___INC__I2CAPI_H) \
	 ..\inc\\ipuapi.h $(___INC__ISUAPI_H)  $(___INC__DCFAPI_H) \
	 ..\inc\\jpegapi.h ..\asf\inc\asf.h ..\inc\\gpioapi.h  \
	 $(___INC__IISAPI_H) $(___INC__TIMERAPI_H) ..\inc\\task.h \
	 ..\inc\\fsapi.h ..\fs\inc\fs_fat.h ..\inc\\uiapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_OV7740_YUV.c $(CARM) -o Debug\siu_OV7740_YUV.o
Debug\siu_OV7725_YUV.o: src\siu_OV7725_YUV.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\sysapi.h $(___INC__SIUAPI_H) inc\\siu.h \
	 inc\\siureg.h ..\inc\\sensorapi.h $(___INC__I2CAPI_H) \
	 ..\inc\\ipuapi.h $(___INC__ISUAPI_H)  $(___INC__DCFAPI_H) \
	 ..\inc\\jpegapi.h ..\asf\inc\asf.h ..\inc\\gpioapi.h  \
	 $(___INC__IISAPI_H) $(___INC__TIMERAPI_H) ..\inc\\task.h \
	 ..\inc\\fsapi.h ..\fs\inc\fs_fat.h ..\inc\\uiapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_OV7725_YUV.c $(CARM) -o Debug\siu_OV7725_YUV.o
Debug\siu_MI1320.o: src\siu_MI1320.c $(___INC__GENERAL_H) ..\inc\\board.h \
	 ..\inc\\sysapi.h $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h \
	 ..\inc\\sensorapi.h $(___INC__I2CAPI_H) ..\inc\\ipuapi.h \
	 $(___INC__ISUAPI_H)  $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\asf\inc\asf.h ..\inc\\gpioapi.h  $(___INC__IISAPI_H) \
	 $(___INC__TIMERAPI_H) ..\inc\\task.h ..\inc\\fsapi.h \
	 ..\fs\inc\fs_fat.h ..\inc\\uiapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_MI1320.c \
	 $(CARM) -o Debug\siu_MI1320.o
Debug\siu_MotionDetect.o: src\siu_MotionDetect.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\sysapi.h $(___INC__SIUAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_MotionDetect.c $(CARM) -o Debug\siu_MotionDetect.o
Debug\siu_CCIR656.o: src\siu_CCIR656.c $(___INC__GENERAL_H) ..\inc\\board.h \
	 ..\inc\\sysapi.h $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h \
	 ..\inc\\sensorapi.h $(___INC__I2CAPI_H) ..\inc\\ipuapi.h \
	 $(___INC__ISUAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\asf\inc\asf.h ..\inc\\gpioapi.h  $(___INC__IISAPI_H) \
	 $(___INC__TIMERAPI_H) $(___INC__ASFAPI_H) ..\inc\\task.h \
	 ..\inc\\uiapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_CCIR656.c \
	 $(CARM) -o Debug\siu_CCIR656.o
Debug\siu_OV7725.o: src\siu_OV7725.c $(___INC__GENERAL_H) ..\inc\\board.h \
	 ..\inc\\sysapi.h $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h \
	 ..\inc\\sensorapi.h $(___INC__I2CAPI_H) ..\inc\\ipuapi.h \
	 $(___INC__ISUAPI_H)  $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\asf\inc\asf.h ..\inc\\gpioapi.h  $(___INC__IISAPI_H) \
	 $(___INC__TIMERAPI_H) ..\inc\\task.h ..\inc\\fsapi.h \
	 ..\fs\inc\fs_fat.h ..\inc\\uiapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_OV7725.c \
	 $(CARM) -o Debug\siu_OV7725.o
Debug\AWB.o: src\AWB.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\AWB.c $(CARM) \
	 -o Debug\AWB.o
Debug\siu_AF_ZOOM.o: src\siu_AF_ZOOM.c $(___INC__GENERAL_H) ..\inc\\board.h \
	 ..\inc\\gpioapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_AF_ZOOM.c \
	 $(CARM) -o Debug\siu_AF_ZOOM.o
Debug\siumem.o: src\siumem.c $(___INC__GENERAL_H) ..\inc\\sensorapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siumem.c \
	 $(CARM) -o Debug\siumem.o
Debug\siu_5M.o: src\siu_5M.c $(___INC__GENERAL_H) ..\inc\\board.h \
	 ..\inc\\sysapi.h $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h \
	 ..\inc\\sensorapi.h $(___INC__I2CAPI_H) ..\inc\\ipuapi.h \
	 $(___INC__ISUAPI_H)  $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\asf\inc\asf.h ..\inc\\gpioapi.h  $(___INC__IISAPI_H) \
	 $(___INC__TIMERAPI_H) ..\isu\inc\isureg.h ..\inc\\task.h \
	 ..\inc\\fsapi.h ..\fs\inc\fs_fat.h ..\inc\\uiapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_5M.c \
	 $(CARM) -o Debug\siu_5M.o
Debug\siu_2M.o: src\siu_2M.c $(___INC__GENERAL_H) ..\inc\\board.h \
	 $(___INC__SIUAPI_H) ..\inc\\task.h inc\\siu.h inc\\siureg.h \
	 ..\inc\\sensorapi.h $(___INC__I2CAPI_H) ..\inc\\ipuapi.h \
	 $(___INC__ISUAPI_H)  $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\asf\inc\asf.h ..\inc\\fsapi.h ..\fs\inc\fs_fat.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_2M.c \
	 $(CARM) -o Debug\siu_2M.o
Debug\compdefectpix.o: .\src\compdefectpix.c $(___INC__SIUAPI_H) inc\\siu.h \
	 $(___INC__SMCAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\compdefectpix.c $(CARM) -o Debug\compdefectpix.o
