#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ --no_debug --dwarf2 -O3
CARM_SRCS	= 		  src\siu_NONE.c src\siu_PO3100K_YUV.c \
		  src\siu_NT99141_YUV.c src\siu_HM1375_YUV.c \
		  src\siu_MT9M131_YUV.c src\siu_OV2643_YUV.c \
		  src\siu_OV7740_RAW.c src\MotionDetect_API.c \
		  src\siu_MI1320_Raw.c src\siu_OV7740_YUV.c \
		  src\siu_OV7725_YUV.c src\siu_MI1320.c \
		  src\siu_MotionDetect.c src\siu_CCIR656.c \
		  src\siu_OV7725.c src\AWB.c src\siu_AF_ZOOM.c \
		  src\siumem.c src\siu_5M.c src\siu_2M.c \
		  .\src\compdefectpix.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\siu_NONE.o Release\siu_PO3100K_YUV.o \
		  Release\siu_NT99141_YUV.o Release\siu_HM1375_YUV.o \
		  Release\siu_MT9M131_YUV.o Release\siu_OV2643_YUV.o \
		  Release\siu_OV7740_RAW.o Release\MotionDetect_API.o \
		  Release\siu_MI1320_Raw.o Release\siu_OV7740_YUV.o \
		  Release\siu_OV7725_YUV.o Release\siu_MI1320.o \
		  Release\siu_MotionDetect.o Release\siu_CCIR656.o \
		  Release\siu_OV7725.o Release\AWB.o \
		  Release\siu_AF_ZOOM.o Release\siumem.o \
		  Release\siu_5M.o Release\siu_2M.o \
		  Release\compdefectpix.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= siu_Release.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\siu.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 12
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\application.h \
	 ..\inc\\project.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__MEMORYPOOL_H=..\inc\\memorypool.h ..\inc\\iduapi.h \
	 ..\inc\\mpeg4api.h ..\inc\\iisapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) $(___INC__MEMORYPOOL_H) 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__I2CAPI_H=..\inc\\i2capi.h ..\inc\\rtcapi.h 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__SYSAPI_H=..\inc\\sysapi.h 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\task.h ..\inc\\uikey.h \
	 ..\inc\\rfiuapi.h 
___INC__TIMERAPI_H=..\inc\\timerapi.h $(___INC__GENERAL_H) 
___INC__ASFAPI_H=..\inc\\asfapi.h $(___INC__FSAPI_H) 
___INC__LOGFILEAPI_H=..\inc\\logfileapi.h ..\inc\\task.h ..\inc\\isuapi.h 
___INC__SMCAPI_H=..\inc\\smcapi.h $(___INC__GENERAL_H) 
# DEPEND: end include files

Release\siu_NONE.o: src\siu_NONE.c ..\inc\\board.h $(___INC__SIUAPI_H) \
	 inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h $(___INC__I2CAPI_H) \
	 ..\inc\\ipuapi.h ..\inc\\isuapi.h $(___INC__FSAPI_H) \
	 $(___INC__DCFAPI_H) ..\inc\\jpegapi.h ..\inc\\gpioapi.h \
	 $(___INC__SYSAPI_H) $(___INC__UIAPI_H) $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_NONE.c \
	 $(CARM) -o Release\siu_NONE.o
Release\siu_PO3100K_YUV.o: src\siu_PO3100K_YUV.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h ..\inc\\isuapi.h \
	 $(___INC__FSAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\gpioapi.h $(___INC__SYSAPI_H) $(___INC__UIAPI_H) \
	 $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_PO3100K_YUV.c $(CARM) -o Release\siu_PO3100K_YUV.o
Release\siu_NT99141_YUV.o: src\siu_NT99141_YUV.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h ..\inc\\isuapi.h \
	 $(___INC__FSAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\gpioapi.h $(___INC__SYSAPI_H) $(___INC__UIAPI_H) \
	 $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_NT99141_YUV.c $(CARM) -o Release\siu_NT99141_YUV.o
Release\siu_HM1375_YUV.o: src\siu_HM1375_YUV.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h ..\inc\\isuapi.h \
	 $(___INC__FSAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\gpioapi.h $(___INC__SYSAPI_H) $(___INC__UIAPI_H) \
	 $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_HM1375_YUV.c $(CARM) -o Release\siu_HM1375_YUV.o
Release\siu_MT9M131_YUV.o: src\siu_MT9M131_YUV.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h ..\inc\\isuapi.h \
	 $(___INC__FSAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\gpioapi.h $(___INC__SYSAPI_H) $(___INC__UIAPI_H) \
	 $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_MT9M131_YUV.c $(CARM) -o Release\siu_MT9M131_YUV.o
Release\siu_OV2643_YUV.o: src\siu_OV2643_YUV.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h ..\inc\\isuapi.h \
	 $(___INC__FSAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\gpioapi.h $(___INC__SYSAPI_H) $(___INC__UIAPI_H) \
	 $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_OV2643_YUV.c $(CARM) -o Release\siu_OV2643_YUV.o
Release\siu_OV7740_RAW.o: src\siu_OV7740_RAW.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h ..\inc\\isuapi.h \
	 $(___INC__FSAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\gpioapi.h $(___INC__SYSAPI_H) $(___INC__UIAPI_H) \
	 $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_OV7740_RAW.c $(CARM) -o Release\siu_OV7740_RAW.o
Release\MotionDetect_API.o: src\MotionDetect_API.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h $(___INC__SIUAPI_H) $(___INC__SYSAPI_H) \
	 $(___INC__ASFAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\MotionDetect_API.c $(CARM) -o Release\MotionDetect_API.o
Release\siu_MI1320_Raw.o: src\siu_MI1320_Raw.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h ..\inc\\isuapi.h \
	 $(___INC__FSAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\gpioapi.h $(___INC__SYSAPI_H) $(___INC__UIAPI_H) \
	 $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_MI1320_Raw.c $(CARM) -o Release\siu_MI1320_Raw.o
Release\siu_OV7740_YUV.o: src\siu_OV7740_YUV.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h ..\inc\\isuapi.h \
	 $(___INC__FSAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\gpioapi.h $(___INC__SYSAPI_H) $(___INC__UIAPI_H) \
	 $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_OV7740_YUV.c $(CARM) -o Release\siu_OV7740_YUV.o
Release\siu_OV7725_YUV.o: src\siu_OV7725_YUV.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h ..\inc\\isuapi.h \
	 $(___INC__FSAPI_H) $(___INC__DCFAPI_H) ..\inc\\jpegapi.h \
	 ..\inc\\gpioapi.h $(___INC__SYSAPI_H) $(___INC__UIAPI_H) \
	 $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_OV7725_YUV.c $(CARM) -o Release\siu_OV7725_YUV.o
Release\siu_MI1320.o: src\siu_MI1320.c ..\inc\\board.h $(___INC__SIUAPI_H) \
	 inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h $(___INC__I2CAPI_H) \
	 ..\inc\\ipuapi.h ..\inc\\isuapi.h $(___INC__FSAPI_H) \
	 $(___INC__DCFAPI_H) ..\inc\\jpegapi.h ..\inc\\gpioapi.h \
	 $(___INC__SYSAPI_H) $(___INC__UIAPI_H) $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_MI1320.c \
	 $(CARM) -o Release\siu_MI1320.o
Release\siu_MotionDetect.o: src\siu_MotionDetect.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h $(___INC__SIUAPI_H) $(___INC__SYSAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 src\siu_MotionDetect.c $(CARM) -o Release\siu_MotionDetect.o
Release\siu_CCIR656.o: src\siu_CCIR656.c ..\inc\\board.h \
	 $(___INC__SIUAPI_H) inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h \
	 $(___INC__I2CAPI_H) ..\inc\\ipuapi.h $(___INC__DCFAPI_H) \
	 ..\inc\\jpegapi.h ..\inc\\gpioapi.h $(___INC__SYSAPI_H) \
	 $(___INC__UIAPI_H) $(___INC__TIMERAPI_H) $(___INC__ASFAPI_H)  \
	 ..\inc\\isuapi.h ..\inc\\logfileapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_CCIR656.c \
	 $(CARM) -o Release\siu_CCIR656.o
Release\siu_OV7725.o: src\siu_OV7725.c ..\inc\\board.h $(___INC__SIUAPI_H) \
	 inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h $(___INC__I2CAPI_H) \
	 ..\inc\\ipuapi.h ..\inc\\isuapi.h $(___INC__FSAPI_H) \
	 $(___INC__DCFAPI_H) ..\inc\\jpegapi.h ..\inc\\gpioapi.h \
	 $(___INC__SYSAPI_H) $(___INC__UIAPI_H) $(___INC__TIMERAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_OV7725.c \
	 $(CARM) -o Release\siu_OV7725.o
Release\AWB.o: src\AWB.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\AWB.c $(CARM) \
	 -o Release\AWB.o
Release\siu_AF_ZOOM.o: src\siu_AF_ZOOM.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\gpioapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_AF_ZOOM.c \
	 $(CARM) -o Release\siu_AF_ZOOM.o
Release\siumem.o: src\siumem.c $(___INC__GENERAL_H) ..\inc\\sensorapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siumem.c \
	 $(CARM) -o Release\siumem.o
Release\siu_5M.o: src\siu_5M.c ..\inc\\board.h $(___INC__SIUAPI_H) \
	 inc\\siu.h inc\\siureg.h ..\inc\\sensorapi.h $(___INC__I2CAPI_H) \
	 ..\inc\\ipuapi.h ..\inc\\isuapi.h $(___INC__FSAPI_H) \
	 $(___INC__DCFAPI_H) ..\inc\\jpegapi.h ..\inc\\gpioapi.h \
	 $(___INC__SYSAPI_H) $(___INC__UIAPI_H) $(___INC__TIMERAPI_H) \
	 ..\isu\inc\isureg.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_5M.c \
	 $(CARM) -o Release\siu_5M.o
Release\siu_2M.o: src\siu_2M.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c src\siu_2M.c \
	 $(CARM) -o Release\siu_2M.o
Release\compdefectpix.o: .\src\compdefectpix.c $(___INC__SIUAPI_H) \
	 inc\\siu.h $(___INC__SMCAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\compdefectpix.c $(CARM) -o Release\compdefectpix.o
