#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ -g --dwarf2 -O1
CARM_SRCS	= 		  .\src\mov.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  DebugRel\mov.o 

CARM_CPP	=  -g --dwarf2 --cpp -O1
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2 -O1
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp -O1
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= mov_DebugRel.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Release\..\..\lib\mov.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 15
#   Selected list: ..\asf\inc\asf.h 
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h \
	 ..\inc\\project\ev_board_hiu.h \
	 ..\inc\\project\isp_pa9002d_sys_256p.h \
	 ..\inc\\project\altera_fpga.h ..\inc\\project\salix_sdv.h \
	 ..\inc\\project\hx_dh500.h ..\inc\\project\mmr6720_ebell.h \
	 ..\inc\\project\yuxin_dvrbox.h ..\inc\\project\cwell_dvrbox.h \
	 ..\inc\\project\rdi_carmrec.h ..\inc\\project\mars_dvrbox.h \
	 ..\inc\\project\skybest_dvrbox.h ..\inc\\project\jsw_dvrbox.h \
	 ..\inc\\project\alm_dvrbox.h ..\inc\\project\act611_dvrbox.h \
	 ..\inc\\project\mustek_dvrbox.h ..\inc\\project\winnin_irdvr.h \
	 ..\inc\\project\dty_irdvr.h ..\inc\\project\aurum_dvrbox.h \
	 ..\inc\\project\elegant_kfcdvr.h ..\inc\\project\gos_dvrbox.h \
	 ..\inc\\project\ver100_cardvr.h ..\inc\\project\siyuan_cvr.h \
	 ..\inc\\project\roule_doorphone.h ..\inc\\project\ultmost_sdv.h \
	 ..\inc\\project\shuoying_sdv.h ..\inc\\project\sunway_sdv.h \
	 ..\inc\\project\rdi_doorphone_774.h \
	 ..\inc\\project\everspring_dvrbox.h \
	 ..\inc\\project\konlika_dvrbox.h ..\inc\\project\stone_dvrbox.h \
	 ..\inc\\project\jsm_dvrbox.h ..\inc\\project\d010_cardvr.h \
	 ..\inc\\project\project_dw950.h ..\inc\\project\project_opcom.h \
	 ..\inc\\project\project_8980_6720.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) ..\inc\\memorypool.h 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) ..\fs\inc\fs_fat.h 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__MOVAPI_H=..\inc\\movapi.h 
___INC__IISAPI_H=..\inc\\iisapi.h 
___INC__ISUAPI_H=..\inc\\isuapi.h 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
# DEPEND: end include files

DebugRel\mov.o: .\src\mov.c $(___INC__GENERAL_H) ..\inc\\board.h \
	 ..\inc\\task.h  ..\inc\\rtcapi.h $(___INC__DCFAPI_H) inc\\mov.h \
	 $(___INC__MOVAPI_H) ..\inc\\mpeg4api.h $(___INC__IISAPI_H) \
	 $(___INC__ISUAPI_H) ..\inc\\iduapi.h ..\inc\\ipuapi.h \
	 $(___INC__SIUAPI_H) ..\inc\\sysapi.h ..\inc\\fsapi.h \
	 ..\fs\inc\fs_fat.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\mov.c \
	 $(CARM) -o DebugRel\mov.o
