#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I.\H -I.\SRC\WEBSERVER\Includes -I.\SRC\ROMPAGER\Includes \
	 -I.\SRC\PhraseDictionaries -I.\SRC\INTERFACE\Phase2\Includes \
	 -I.\SRC\ENGINE\Includes -I..\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I.\H -I.\SRC\WEBSERVER\Includes -I.\SRC\ROMPAGER\Includes -I.\SRC\PhraseDictionaries -I.\SRC\INTERFACE\Phase2\Includes -I.\SRC\ENGINE\Includes -I..\inc\ --no_debug --dwarf2 -O3
CARM_SRCS	= 		  .\src\engine\sources\AsBase64.c \
		  .\src\engine\sources\AsCommon.c \
		  .\src\engine\sources\AsConvrt.c \
		  .\src\engine\sources\AsCustom.c \
		  .\src\engine\sources\AsDate.c \
		  .\src\engine\sources\AsFloat.c \
		  .\src\engine\sources\AsGlobal.c \
		  .\src\engine\sources\AsLock.c \
		  .\src\engine\sources\AsMain.c \
		  .\src\engine\sources\AsMD5.c \
		  .\src\engine\sources\AsMimes.c \
		  .\src\engine\sources\AsParse.c \
		  .\src\engine\sources\AsSnmp.c \
		  .\src\engine\sources\AsVarAcc.c \
		  .\src\interface\phase2\sources\Sfil.c \
		  .\src\interface\phase2\sources\Stcp.c \
		  .\src\interface\phase2\sources\web_task.c \
		  .\src\phrasedictionaries\RpUsrDct.c \
		  .\src\remotehost\RpRemHst.c \
		  .\src\rompager\sources\IppShell.c \
		  .\src\rompager\sources\RpAccess.c \
		  .\src\rompager\sources\RpCallBk.c \
		  .\src\rompager\sources\RpData.c \
		  .\src\rompager\sources\RpForm.c \
		  .\src\rompager\sources\RpHtml.c \
		  .\src\rompager\sources\RpHttpDy.c \
		  .\src\rompager\sources\RpIpp.c \
		  .\src\rompager\sources\RpLog.c \
		  .\src\rompager\sources\RpMulti.c \
		  .\src\rompager\sources\RpPut.c \
		  .\src\rompager\sources\RpQuery.c \
		  .\src\rompager\sources\RpUrl.c \
		  .\src\rompager\sources\RpUser.c \
		  .\src\rompager\sources\Spwd.c \
		  .\src\webserver\sources\RpFile.c \
		  .\src\webserver\sources\RpFrmItm.c \
		  .\src\webserver\sources\RpHttp.c \
		  .\src\webserver\sources\RpHttpPs.c \
		  .\src\webserver\sources\RpHttpRq.c .\pages\fRpWebID.c \
		  .\pages\fSetting.c .\pages\html.c .\pages\image.c \
		  .\pages\javacode.c .\pages\obhtml.c \
		  .\pages\obimage.c .\pages\objvcode.c \
		  .\pages\RpPages.c .\pages\sLogout.c .\pages\sMain.c \
		  .\pages\sRpWebID.c .\pages\sSetting.c \
		  .\pages\wb_Menu.c .\pages\web_util.c \
		  .\pages\fMain.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\AsBase64.o Release\AsCommon.o \
		  Release\AsConvrt.o Release\AsCustom.o \
		  Release\AsDate.o Release\AsFloat.o \
		  Release\AsGlobal.o Release\AsLock.o \
		  Release\AsMain.o Release\AsMD5.o Release\AsMimes.o \
		  Release\AsParse.o Release\AsSnmp.o \
		  Release\AsVarAcc.o Release\Sfil.o Release\Stcp.o \
		  Release\web_task.o Release\RpUsrDct.o \
		  Release\RpRemHst.o Release\IppShell.o \
		  Release\RpAccess.o Release\RpCallBk.o \
		  Release\RpData.o Release\RpForm.o Release\RpHtml.o \
		  Release\RpHttpDy.o Release\RpIpp.o Release\RpLog.o \
		  Release\RpMulti.o Release\RpPut.o Release\RpQuery.o \
		  Release\RpUrl.o Release\RpUser.o Release\Spwd.o \
		  Release\RpFile.o Release\RpFrmItm.o \
		  Release\RpHttp.o Release\RpHttpPs.o \
		  Release\RpHttpRq.o Release\fRpWebID.o \
		  Release\fSetting.o Release\html.o Release\image.o \
		  Release\javacode.o Release\obhtml.o \
		  Release\obimage.o Release\objvcode.o \
		  Release\RpPages.o Release\sLogout.o Release\sMain.o \
		  Release\sRpWebID.o Release\sSetting.o \
		  Release\wb_Menu.o Release\web_util.o \
		  Release\fMain.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= web_Release.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\web.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 92
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\project.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__MEMORYPOOL_H=..\inc\\memorypool.h ..\inc\\iduapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) $(___INC__MEMORYPOOL_H) 
H_SRPWEBID_H=H\srpwebid.h SRC\ROMPAGER\Includes\rpconfig.h 
H_WEB_UTIL_H=H\web_util.h SRC\ENGINE\Includes\astypes.h H\web_flag.h 
# DEPEND: end include files

Release\AsBase64.o: .\src\engine\sources\AsBase64.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsBase64.c $(CARM) -o Release\AsBase64.o
Release\AsCommon.o: .\src\engine\sources\AsCommon.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsCommon.c $(CARM) -o Release\AsCommon.o
Release\AsConvrt.o: .\src\engine\sources\AsConvrt.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsConvrt.c $(CARM) -o Release\AsConvrt.o
Release\AsCustom.o: .\src\engine\sources\AsCustom.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsCustom.c $(CARM) -o Release\AsCustom.o
Release\AsDate.o: .\src\engine\sources\AsDate.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsDate.c $(CARM) -o Release\AsDate.o
Release\AsFloat.o: .\src\engine\sources\AsFloat.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsFloat.c $(CARM) -o Release\AsFloat.o
Release\AsGlobal.o: .\src\engine\sources\AsGlobal.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsGlobal.c $(CARM) -o Release\AsGlobal.o
Release\AsLock.o: .\src\engine\sources\AsLock.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsLock.c $(CARM) -o Release\AsLock.o
Release\AsMain.o: .\src\engine\sources\AsMain.c \
	 SRC\ENGINE\Includes\asengine.h \
	 SRC\INTERFACE\Phase2\Includes\sser.h SRC\ENGINE\Includes\asprotos.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsMain.c $(CARM) -o Release\AsMain.o
Release\AsMD5.o: .\src\engine\sources\AsMD5.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsMD5.c $(CARM) -o Release\AsMD5.o
Release\AsMimes.o: .\src\engine\sources\AsMimes.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsMimes.c $(CARM) -o Release\AsMimes.o
Release\AsParse.o: .\src\engine\sources\AsParse.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsParse.c $(CARM) -o Release\AsParse.o
Release\AsSnmp.o: .\src\engine\sources\AsSnmp.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsSnmp.c $(CARM) -o Release\AsSnmp.o
Release\AsVarAcc.o: .\src\engine\sources\AsVarAcc.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsVarAcc.c $(CARM) -o Release\AsVarAcc.o
Release\Sfil.o: .\src\interface\phase2\sources\Sfil.c \
	 SRC\ENGINE\Includes\asextern.h \
	 SRC\INTERFACE\Phase2\Includes\sfil.h \
	 SRC\INTERFACE\Phase2\Includes\sfilint.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\interface\phase2\sources\Sfil.c $(CARM) -o Release\Sfil.o
Release\Stcp.o: .\src\interface\phase2\sources\Stcp.c \
	 SRC\ENGINE\Includes\astypes.h SRC\INTERFACE\Phase2\Includes\stcp.h \
	 SRC\ROMPAGER\Includes\rpextern.h SRC\WEBSERVER\Includes\rompager.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\interface\phase2\sources\Stcp.c $(CARM) -o Release\Stcp.o
Release\web_task.o: .\src\interface\phase2\sources\web_task.c \
	 SRC\ENGINE\Includes\asengine.h SRC\ENGINE\Includes\asprotos.h \
	 $(___INC__GENERAL_H) H\wb_menu.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\interface\phase2\sources\web_task.c $(CARM) -o \
	 Release\web_task.o
Release\RpUsrDct.o: .\src\phrasedictionaries\RpUsrDct.c \
	 SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\phrasedictionaries\RpUsrDct.c $(CARM) -o Release\RpUsrDct.o
Release\RpRemHst.o: .\src\remotehost\RpRemHst.c \
	 SRC\ENGINE\Includes\asengine.h $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\remotehost\RpRemHst.c $(CARM) -o Release\RpRemHst.o
Release\IppShell.o: .\src\rompager\sources\IppShell.c \
	 SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\IppShell.c $(CARM) -o Release\IppShell.o
Release\RpAccess.o: .\src\rompager\sources\RpAccess.c \
	 SRC\ENGINE\Includes\asengine.h $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpAccess.c $(CARM) -o Release\RpAccess.o
Release\RpCallBk.o: .\src\rompager\sources\RpCallBk.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpCallBk.c $(CARM) -o Release\RpCallBk.o
Release\RpData.o: .\src\rompager\sources\RpData.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpData.c $(CARM) -o Release\RpData.o
Release\RpForm.o: .\src\rompager\sources\RpForm.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpForm.c $(CARM) -o Release\RpForm.o
Release\RpHtml.o: .\src\rompager\sources\RpHtml.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpHtml.c $(CARM) -o Release\RpHtml.o
Release\RpHttpDy.o: .\src\rompager\sources\RpHttpDy.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpHttpDy.c $(CARM) -o Release\RpHttpDy.o
Release\RpIpp.o: .\src\rompager\sources\RpIpp.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpIpp.c $(CARM) -o Release\RpIpp.o
Release\RpLog.o: .\src\rompager\sources\RpLog.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpLog.c $(CARM) -o Release\RpLog.o
Release\RpMulti.o: .\src\rompager\sources\RpMulti.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpMulti.c $(CARM) -o Release\RpMulti.o
Release\RpPut.o: .\src\rompager\sources\RpPut.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpPut.c $(CARM) -o Release\RpPut.o
Release\RpQuery.o: .\src\rompager\sources\RpQuery.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpQuery.c $(CARM) -o Release\RpQuery.o
Release\RpUrl.o: .\src\rompager\sources\RpUrl.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpUrl.c $(CARM) -o Release\RpUrl.o
Release\RpUser.o: .\src\rompager\sources\RpUser.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpUser.c $(CARM) -o Release\RpUser.o
Release\Spwd.o: .\src\rompager\sources\Spwd.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\Spwd.c $(CARM) -o Release\Spwd.o
Release\RpFile.o: .\src\webserver\sources\RpFile.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpFile.c $(CARM) -o Release\RpFile.o
Release\RpFrmItm.o: .\src\webserver\sources\RpFrmItm.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpFrmItm.c $(CARM) -o Release\RpFrmItm.o
Release\RpHttp.o: .\src\webserver\sources\RpHttp.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpHttp.c $(CARM) -o Release\RpHttp.o
Release\RpHttpPs.o: .\src\webserver\sources\RpHttpPs.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpHttpPs.c $(CARM) -o Release\RpHttpPs.o
Release\RpHttpRq.o: .\src\webserver\sources\RpHttpRq.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpHttpRq.c $(CARM) -o Release\RpHttpRq.o
Release\fRpWebID.o: .\pages\fRpWebID.c $(H_SRPWEBID_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\fRpWebID.c \
	 $(CARM) -o Release\fRpWebID.o
Release\fSetting.o: .\pages\fSetting.c H\ssetting.h H\smain.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\fSetting.c \
	 $(CARM) -o Release\fSetting.o
Release\html.o: .\pages\html.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\html.c \
	 $(CARM) -o Release\html.o
Release\image.o: .\pages\image.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\image.c \
	 $(CARM) -o Release\image.o
Release\javacode.o: .\pages\javacode.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\javacode.c \
	 $(CARM) -o Release\javacode.o
Release\obhtml.o: .\pages\obhtml.c SRC\ENGINE\Includes\asextern.h H\web_flag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\obhtml.c \
	 $(CARM) -o Release\obhtml.o
Release\obimage.o: .\pages\obimage.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\obimage.c \
	 $(CARM) -o Release\obimage.o
Release\objvcode.o: .\pages\objvcode.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\objvcode.c \
	 $(CARM) -o Release\objvcode.o
Release\RpPages.o: .\pages\RpPages.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\RpPages.c \
	 $(CARM) -o Release\RpPages.o
Release\sLogout.o: .\pages\sLogout.c SRC\ENGINE\Includes\asengine.h \
	 $(H_SRPWEBID_H) $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\sLogout.c \
	 $(CARM) -o Release\sLogout.o
Release\sMain.o: .\pages\sMain.c SRC\ENGINE\Includes\asengine.h H\wb_menu.h \
	 H\smain.h $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\sMain.c \
	 $(CARM) -o Release\sMain.o
Release\sRpWebID.o: .\pages\sRpWebID.c SRC\ENGINE\Includes\asengine.h \
	 $(H_SRPWEBID_H) $(H_WEB_UTIL_H) H\ssslcfg.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\sRpWebID.c \
	 $(CARM) -o Release\sRpWebID.o
Release\sSetting.o: .\pages\sSetting.c SRC\ENGINE\Includes\asengine.h \
	 H\wb_menu.h H\ssetting.h H\smain.h $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\sSetting.c \
	 $(CARM) -o Release\sSetting.o
Release\wb_Menu.o: .\pages\wb_Menu.c SRC\ENGINE\Includes\asengine.h \
	 SRC\ENGINE\Includes\asextern.h H\wb_menu.h $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\wb_Menu.c \
	 $(CARM) -o Release\wb_Menu.o
Release\web_util.o: .\pages\web_util.c SRC\WEBSERVER\Includes\rompager.h \
	 $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\web_util.c \
	 $(CARM) -o Release\web_util.o
Release\fMain.o: .\pages\fMain.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\fMain.c \
	 $(CARM) -o Release\fMain.o
