#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I.\H -I.\SRC\WEBSERVER\Includes -I.\SRC\ROMPAGER\Includes \
	 -I.\SRC\PhraseDictionaries -I.\SRC\INTERFACE\Phase2\Includes \
	 -I.\SRC\ENGINE\Includes -I..\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I.\H -I.\SRC\WEBSERVER\Includes -I.\SRC\ROMPAGER\Includes -I.\SRC\PhraseDictionaries -I.\SRC\INTERFACE\Phase2\Includes -I.\SRC\ENGINE\Includes -I..\inc\ -g --dwarf2
CARM_SRCS	= 		  .\src\engine\sources\AsBase64.c \
		  .\src\engine\sources\AsCommon.c \
		  .\src\engine\sources\AsConvrt.c \
		  .\src\engine\sources\AsCustom.c \
		  .\src\engine\sources\AsDate.c \
		  .\src\engine\sources\AsFloat.c \
		  .\src\engine\sources\AsGlobal.c \
		  .\src\engine\sources\AsLock.c \
		  .\src\engine\sources\AsMain.c \
		  .\src\engine\sources\AsMD5.c \
		  .\src\engine\sources\AsMimes.c \
		  .\src\engine\sources\AsParse.c \
		  .\src\engine\sources\AsSnmp.c \
		  .\src\engine\sources\AsVarAcc.c \
		  .\src\interface\phase2\sources\Sfil.c \
		  .\src\interface\phase2\sources\Stcp.c \
		  .\src\interface\phase2\sources\web_task.c \
		  .\src\phrasedictionaries\RpUsrDct.c \
		  .\src\remotehost\RpRemHst.c \
		  .\src\rompager\sources\IppShell.c \
		  .\src\rompager\sources\RpAccess.c \
		  .\src\rompager\sources\RpCallBk.c \
		  .\src\rompager\sources\RpData.c \
		  .\src\rompager\sources\RpForm.c \
		  .\src\rompager\sources\RpHtml.c \
		  .\src\rompager\sources\RpHttpDy.c \
		  .\src\rompager\sources\RpIpp.c \
		  .\src\rompager\sources\RpLog.c \
		  .\src\rompager\sources\RpMulti.c \
		  .\src\rompager\sources\RpPut.c \
		  .\src\rompager\sources\RpQuery.c \
		  .\src\rompager\sources\RpUrl.c \
		  .\src\rompager\sources\RpUser.c \
		  .\src\rompager\sources\Spwd.c \
		  .\src\webserver\sources\RpFile.c \
		  .\src\webserver\sources\RpFrmItm.c \
		  .\src\webserver\sources\RpHttp.c \
		  .\src\webserver\sources\RpHttpPs.c \
		  .\src\webserver\sources\RpHttpRq.c .\pages\fRpWebID.c \
		  .\pages\fSetting.c .\pages\html.c .\pages\image.c \
		  .\pages\javacode.c .\pages\obhtml.c \
		  .\pages\obimage.c .\pages\objvcode.c \
		  .\pages\RpPages.c .\pages\sLogout.c .\pages\sMain.c \
		  .\pages\sRpWebID.c .\pages\sSetting.c \
		  .\pages\wb_Menu.c .\pages\web_util.c \
		  .\pages\fMain.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Debug\AsBase64.o Debug\AsCommon.o Debug\AsConvrt.o \
		  Debug\AsCustom.o Debug\AsDate.o Debug\AsFloat.o \
		  Debug\AsGlobal.o Debug\AsLock.o Debug\AsMain.o \
		  Debug\AsMD5.o Debug\AsMimes.o Debug\AsParse.o \
		  Debug\AsSnmp.o Debug\AsVarAcc.o Debug\Sfil.o \
		  Debug\Stcp.o Debug\web_task.o Debug\RpUsrDct.o \
		  Debug\RpRemHst.o Debug\IppShell.o Debug\RpAccess.o \
		  Debug\RpCallBk.o Debug\RpData.o Debug\RpForm.o \
		  Debug\RpHtml.o Debug\RpHttpDy.o Debug\RpIpp.o \
		  Debug\RpLog.o Debug\RpMulti.o Debug\RpPut.o \
		  Debug\RpQuery.o Debug\RpUrl.o Debug\RpUser.o \
		  Debug\Spwd.o Debug\RpFile.o Debug\RpFrmItm.o \
		  Debug\RpHttp.o Debug\RpHttpPs.o Debug\RpHttpRq.o \
		  Debug\fRpWebID.o Debug\fSetting.o Debug\html.o \
		  Debug\image.o Debug\javacode.o Debug\obhtml.o \
		  Debug\obimage.o Debug\objvcode.o Debug\RpPages.o \
		  Debug\sLogout.o Debug\sMain.o Debug\sRpWebID.o \
		  Debug\sSetting.o Debug\wb_Menu.o Debug\web_util.o \
		  Debug\fMain.o 

CARM_CPP	=  -g --dwarf2 --cpp
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= web_Debug.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\web.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 92
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\project.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__MEMORYPOOL_H=..\inc\\memorypool.h ..\inc\\iduapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) $(___INC__MEMORYPOOL_H) 
H_SRPWEBID_H=H\srpwebid.h SRC\ROMPAGER\Includes\rpconfig.h 
H_WEB_UTIL_H=H\web_util.h SRC\ENGINE\Includes\astypes.h H\web_flag.h 
# DEPEND: end include files

Debug\AsBase64.o: .\src\engine\sources\AsBase64.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsBase64.c $(CARM) -o Debug\AsBase64.o
Debug\AsCommon.o: .\src\engine\sources\AsCommon.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsCommon.c $(CARM) -o Debug\AsCommon.o
Debug\AsConvrt.o: .\src\engine\sources\AsConvrt.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsConvrt.c $(CARM) -o Debug\AsConvrt.o
Debug\AsCustom.o: .\src\engine\sources\AsCustom.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsCustom.c $(CARM) -o Debug\AsCustom.o
Debug\AsDate.o: .\src\engine\sources\AsDate.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsDate.c $(CARM) -o Debug\AsDate.o
Debug\AsFloat.o: .\src\engine\sources\AsFloat.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsFloat.c $(CARM) -o Debug\AsFloat.o
Debug\AsGlobal.o: .\src\engine\sources\AsGlobal.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsGlobal.c $(CARM) -o Debug\AsGlobal.o
Debug\AsLock.o: .\src\engine\sources\AsLock.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsLock.c $(CARM) -o Debug\AsLock.o
Debug\AsMain.o: .\src\engine\sources\AsMain.c \
	 SRC\ENGINE\Includes\asengine.h \
	 SRC\INTERFACE\Phase2\Includes\sser.h SRC\ENGINE\Includes\asprotos.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsMain.c $(CARM) -o Debug\AsMain.o
Debug\AsMD5.o: .\src\engine\sources\AsMD5.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsMD5.c $(CARM) -o Debug\AsMD5.o
Debug\AsMimes.o: .\src\engine\sources\AsMimes.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsMimes.c $(CARM) -o Debug\AsMimes.o
Debug\AsParse.o: .\src\engine\sources\AsParse.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsParse.c $(CARM) -o Debug\AsParse.o
Debug\AsSnmp.o: .\src\engine\sources\AsSnmp.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsSnmp.c $(CARM) -o Debug\AsSnmp.o
Debug\AsVarAcc.o: .\src\engine\sources\AsVarAcc.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\engine\sources\AsVarAcc.c $(CARM) -o Debug\AsVarAcc.o
Debug\Sfil.o: .\src\interface\phase2\sources\Sfil.c \
	 SRC\ENGINE\Includes\asextern.h \
	 SRC\INTERFACE\Phase2\Includes\sfil.h \
	 SRC\INTERFACE\Phase2\Includes\sfilint.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\interface\phase2\sources\Sfil.c $(CARM) -o Debug\Sfil.o
Debug\Stcp.o: .\src\interface\phase2\sources\Stcp.c \
	 SRC\ENGINE\Includes\astypes.h SRC\INTERFACE\Phase2\Includes\stcp.h \
	 SRC\ROMPAGER\Includes\rpextern.h SRC\WEBSERVER\Includes\rompager.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\interface\phase2\sources\Stcp.c $(CARM) -o Debug\Stcp.o
Debug\web_task.o: .\src\interface\phase2\sources\web_task.c \
	 SRC\ENGINE\Includes\asengine.h SRC\ENGINE\Includes\asprotos.h \
	 $(___INC__GENERAL_H) H\wb_menu.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\interface\phase2\sources\web_task.c $(CARM) -o Debug\web_task.o
Debug\RpUsrDct.o: .\src\phrasedictionaries\RpUsrDct.c \
	 SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\phrasedictionaries\RpUsrDct.c $(CARM) -o Debug\RpUsrDct.o
Debug\RpRemHst.o: .\src\remotehost\RpRemHst.c \
	 SRC\ENGINE\Includes\asengine.h $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\remotehost\RpRemHst.c $(CARM) -o Debug\RpRemHst.o
Debug\IppShell.o: .\src\rompager\sources\IppShell.c \
	 SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\IppShell.c $(CARM) -o Debug\IppShell.o
Debug\RpAccess.o: .\src\rompager\sources\RpAccess.c \
	 SRC\ENGINE\Includes\asengine.h $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpAccess.c $(CARM) -o Debug\RpAccess.o
Debug\RpCallBk.o: .\src\rompager\sources\RpCallBk.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpCallBk.c $(CARM) -o Debug\RpCallBk.o
Debug\RpData.o: .\src\rompager\sources\RpData.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpData.c $(CARM) -o Debug\RpData.o
Debug\RpForm.o: .\src\rompager\sources\RpForm.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpForm.c $(CARM) -o Debug\RpForm.o
Debug\RpHtml.o: .\src\rompager\sources\RpHtml.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpHtml.c $(CARM) -o Debug\RpHtml.o
Debug\RpHttpDy.o: .\src\rompager\sources\RpHttpDy.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpHttpDy.c $(CARM) -o Debug\RpHttpDy.o
Debug\RpIpp.o: .\src\rompager\sources\RpIpp.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpIpp.c $(CARM) -o Debug\RpIpp.o
Debug\RpLog.o: .\src\rompager\sources\RpLog.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpLog.c $(CARM) -o Debug\RpLog.o
Debug\RpMulti.o: .\src\rompager\sources\RpMulti.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpMulti.c $(CARM) -o Debug\RpMulti.o
Debug\RpPut.o: .\src\rompager\sources\RpPut.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpPut.c $(CARM) -o Debug\RpPut.o
Debug\RpQuery.o: .\src\rompager\sources\RpQuery.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpQuery.c $(CARM) -o Debug\RpQuery.o
Debug\RpUrl.o: .\src\rompager\sources\RpUrl.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpUrl.c $(CARM) -o Debug\RpUrl.o
Debug\RpUser.o: .\src\rompager\sources\RpUser.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\RpUser.c $(CARM) -o Debug\RpUser.o
Debug\Spwd.o: .\src\rompager\sources\Spwd.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\rompager\sources\Spwd.c $(CARM) -o Debug\Spwd.o
Debug\RpFile.o: .\src\webserver\sources\RpFile.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpFile.c $(CARM) -o Debug\RpFile.o
Debug\RpFrmItm.o: .\src\webserver\sources\RpFrmItm.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpFrmItm.c $(CARM) -o Debug\RpFrmItm.o
Debug\RpHttp.o: .\src\webserver\sources\RpHttp.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpHttp.c $(CARM) -o Debug\RpHttp.o
Debug\RpHttpPs.o: .\src\webserver\sources\RpHttpPs.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpHttpPs.c $(CARM) -o Debug\RpHttpPs.o
Debug\RpHttpRq.o: .\src\webserver\sources\RpHttpRq.c \
	 SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\webserver\sources\RpHttpRq.c $(CARM) -o Debug\RpHttpRq.o
Debug\fRpWebID.o: .\pages\fRpWebID.c $(H_SRPWEBID_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\fRpWebID.c \
	 $(CARM) -o Debug\fRpWebID.o
Debug\fSetting.o: .\pages\fSetting.c H\ssetting.h H\smain.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\fSetting.c \
	 $(CARM) -o Debug\fSetting.o
Debug\html.o: .\pages\html.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\html.c \
	 $(CARM) -o Debug\html.o
Debug\image.o: .\pages\image.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\image.c \
	 $(CARM) -o Debug\image.o
Debug\javacode.o: .\pages\javacode.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\javacode.c \
	 $(CARM) -o Debug\javacode.o
Debug\obhtml.o: .\pages\obhtml.c SRC\ENGINE\Includes\asextern.h H\web_flag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\obhtml.c \
	 $(CARM) -o Debug\obhtml.o
Debug\obimage.o: .\pages\obimage.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\obimage.c \
	 $(CARM) -o Debug\obimage.o
Debug\objvcode.o: .\pages\objvcode.c SRC\ENGINE\Includes\asextern.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\objvcode.c \
	 $(CARM) -o Debug\objvcode.o
Debug\RpPages.o: .\pages\RpPages.c SRC\ENGINE\Includes\asengine.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\RpPages.c \
	 $(CARM) -o Debug\RpPages.o
Debug\sLogout.o: .\pages\sLogout.c SRC\ENGINE\Includes\asengine.h \
	 $(H_SRPWEBID_H) $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\sLogout.c \
	 $(CARM) -o Debug\sLogout.o
Debug\sMain.o: .\pages\sMain.c SRC\ENGINE\Includes\asengine.h H\wb_menu.h \
	 H\smain.h $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\sMain.c \
	 $(CARM) -o Debug\sMain.o
Debug\sRpWebID.o: .\pages\sRpWebID.c SRC\ENGINE\Includes\asengine.h \
	 $(H_SRPWEBID_H) $(H_WEB_UTIL_H) H\ssslcfg.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\sRpWebID.c \
	 $(CARM) -o Debug\sRpWebID.o
Debug\sSetting.o: .\pages\sSetting.c SRC\ENGINE\Includes\asengine.h \
	 H\wb_menu.h H\ssetting.h H\smain.h $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\sSetting.c \
	 $(CARM) -o Debug\sSetting.o
Debug\wb_Menu.o: .\pages\wb_Menu.c SRC\ENGINE\Includes\asengine.h \
	 SRC\ENGINE\Includes\asextern.h H\wb_menu.h $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\wb_Menu.c \
	 $(CARM) -o Debug\wb_Menu.o
Debug\web_util.o: .\pages\web_util.c SRC\WEBSERVER\Includes\rompager.h \
	 $(H_WEB_UTIL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\web_util.c \
	 $(CARM) -o Debug\web_util.o
Debug\fMain.o: .\pages\fMain.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\pages\fMain.c \
	 $(CARM) -o Debug\fMain.o
