#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\mars_controller\ -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\mars_controller\ -I..\inc\ -I.\inc\ --no_debug --dwarf2 -O3
CARM_SRCS	= 		  .\src\sdcusb.c .\src\sdcfs.c .\src\mmc.c \
		  .\src\sdc.c .\src\sdcerr.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\sdcusb.o Release\sdcfs.o Release\mmc.o \
		  Release\sdc.o Release\sdcerr.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= sdc_Release.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\sdc.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 6
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) ..\inc\\memorypool.h 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) ..\fs\inc\fs_fat.h 
___INC__SMCAPI_H=..\inc\\smcapi.h $(___INC__GENERAL_H) 
# DEPEND: end include files

Release\sdcusb.o: .\src\sdcusb.c $(___INC__GENERAL_H)  ..\inc\\sdcapi.h \
	 ..\inc\\usbapi.h ..\inc\\fsapi.h ..\fs\inc\fs_fat.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\sdcusb.c \
	 $(CARM) -o Release\sdcusb.o
Release\sdcfs.o: .\src\sdcfs.c $(___INC__FSAPI_H) ..\inc\\sdcapi.h \
	 $(___INC__SMCAPI_H) inc\\sdcerr.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\sdcfs.c \
	 $(CARM) -o Release\sdcfs.o
Release\mmc.o: .\src\mmc.c $(___INC__GENERAL_H)  ..\inc\\sdcapi.h \
	 ..\inc\\board.h inc\\sdc.h inc\\sdcreg.h inc\\mmc.h inc\\mmcreg.h \
	 ..\inc\\dmaapi.h ..\inc\\fsapi.h ..\fs\inc\fs_fat.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\mmc.c \
	 $(CARM) -o Release\mmc.o
Release\sdc.o: .\src\sdc.c $(___INC__GENERAL_H)  ..\inc\\sdcapi.h \
	 inc\\sdcerr.h ..\inc\\board.h inc\\sdc.h inc\\sdcreg.h \
	 ..\inc\\fsapi.h ..\fs\inc\fs_fat.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\sdc.c \
	 $(CARM) -o Release\sdc.o
Release\sdcerr.o: .\src\sdcerr.c $(___INC__GENERAL_H) inc\\sdcerr.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\sdcerr.c \
	 $(CARM) -o Release\sdcerr.o
