/*

Copyright (c) 2008 Mars Semiconductor Corp.

Module Name:

	isuapi.h

Abstract:

   	The application interface of Image Scaling Unit

Environment:

    	ARM RealView Developer Suite

Revision History:

	2005/08/26	David Tsai	Create

*/

#ifndef __ISU_API_H__
#define __ISU_API_H__

//#include    "../isu/inc/isu.h"
#define ASCII_FONT_12x12x95                             0
#define ASCII_FONT_20x20x95                             1
#define ASCII_FONT_32x40x95                             2
#define ASCII_FONT_32x48x95                             3
#define ASCII_FONT_20x20x95_25                          4
#define ASCII_FONT_20x36x95                             5
#define ASCII_FONT_20x20x95_DR900                       6
#define ASCII_FONT_32x40x95_1BIT                        7
#define ASCII_FONT_32x40x95_2BIT                        8
#define ASCII_FONT_12x12x95_2BIT                        9
#define ASCII_FONT_20x20x95_2BIT                        10
#define ASCII_FONT_20x20x95_DOUBLE_FIELD_2BIT           11
#define ASCII_FONT_20x20x95_DOUBLE_FIELD_2BIT_DR900     12
#define ASCII_FONT_20x20x95_2BIT_WITH_LIGHT             13 /* 搛顫鵀甫O顫  For Project KD Box */
#define ASCII_FONT_8x16x95_2BIT                         14
#define ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA           15
#define ASCII_FONT_16x22x95_COMMAX_2BIT                 16
#define ASCII_FONT_16x20x95_2BIT                        17
#define ASCII_FONT_20x24x95_2BIT                        18
#define ASCII_FONT_32x28x95_2BIT                        19
#define ASCII_FONT_12x16x95_2BIT                        20
#define ASCII_FONT_32x36x95_RDI_2BIT                    21 /* RDI 專用 其他project 要使用 後果自行負責 */
#define ASCII_FONT_16x20x95_RDI_2BIT                    22 /* RDI 專用 其他project 要使用 後果自行負責 */
#define ASCII_FONT_8x16x95_RDI_2BIT                     23 /* RDI 專用 其他project 要使用 後果自行負責 */
#define ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA2          24 

#if((HW_BOARD_OPTION == MR8120_TX_RDI2)|| (HW_BOARD_OPTION == MR8120_TX_RDI3) ||\
    (HW_BOARD_OPTION == MR8120_TX_RDI_AV) || (HW_BOARD_OPTION == MR8120_TX_MAYON_MWL605C) ||\
    (HW_BOARD_OPTION == MR8120_TX_GCT) || (HW_BOARD_OPTION == MR8120_TX_JIT2) ||\
    (HW_BOARD_OPTION == MR8120_TX_JESMAY_AV2) || (HW_BOARD_OPTION == MR8120_TX_FRESHCAM)||\
    (HW_BOARD_OPTION == MR8120_TX_MAYON_LW604))
#define ISU_OVERLAY_LARGE_FONT_TYPE     ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA
#define ISU_OVERLAY_XLARGE_FONT_TYPE    ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA
#define ISU_OVERLAY_SMALL_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
#elif (HW_BOARD_OPTION == MR8120_TX_SKYSUCCESS)
#define ISU_OVERLAY_LARGE_FONT_TYPE     ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA2
#define ISU_OVERLAY_XLARGE_FONT_TYPE    ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA2
#define ISU_OVERLAY_SMALL_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
#elif(HW_BOARD_OPTION == MR6730_WINEYE)
#define ISU_OVERLAY_LARGE_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
#define ISU_OVERLAY_XLARGE_FONT_TYPE    ASCII_FONT_8x16x95_2BIT
#define ISU_OVERLAY_SMALL_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
//#elif IS_COMMAX_DOORPHONE || IS_HECHI_DOORPHONE || (HW_BOARD_OPTION == MR6730_AFN) || (HW_BOARD_OPTION == MR8211_ZINWELL)
#elif IS_COMMAX_DOORPHONE || IS_HECHI_DOORPHONE || (HW_BOARD_OPTION == MR8211_ZINWELL)
#define ISU_OVERLAY_LARGE_FONT_TYPE     ASCII_FONT_16x22x95_COMMAX_2BIT
#define ISU_OVERLAY_XLARGE_FONT_TYPE    ASCII_FONT_16x22x95_COMMAX_2BIT
#define ISU_OVERLAY_SMALL_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
#elif ((HW_BOARD_OPTION == MR6730_AFN))	
	//L
	#if (CIU_OSD_METHOD_2==0)
	#if(HW_DERIV_MODEL==HW_DEVTYPE_CDVR_AFN720PSEN)
	#define ISU_OVERLAY_LARGE_FONT_TYPE    ASCII_FONT_16x20x95_2BIT
	#else
	#define ISU_OVERLAY_LARGE_FONT_TYPE    ASCII_FONT_16x22x95_COMMAX_2BIT
	#endif	
	
	#else
	#define ISU_OVERLAY_LARGE_FONT_TYPE 	ASCII_FONT_12x16x95_2BIT
	#endif	
	//XL
	#if(HW_DERIV_MODEL==HW_DEVTYPE_CDVR_AFN720PSEN)
	#define ISU_OVERLAY_XLARGE_FONT_TYPE	ASCII_FONT_32x40x95_2BIT
	#else
	#define ISU_OVERLAY_XLARGE_FONT_TYPE	ASCII_FONT_16x22x95_COMMAX_2BIT
	#endif
	//S
	#define ISU_OVERLAY_SMALL_FONT_TYPE 	ASCII_FONT_8x16x95_2BIT

#elif (HW_BOARD_OPTION == MR9670_WOAN)
#define ISU_OVERLAY_LARGE_FONT_TYPE     ASCII_FONT_16x22x95_COMMAX_2BIT
#define ISU_OVERLAY_XLARGE_FONT_TYPE    ASCII_FONT_16x22x95_COMMAX_2BIT
#define ISU_OVERLAY_SMALL_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
#elif ((HW_BOARD_OPTION == MR8120_TX_TRANWO2) || (HW_BOARD_OPTION == MR8120_TX_TRANWO_VM2505) ||\
       (HW_BOARD_OPTION  == MR8100_GCT_VM9710)|| (HW_BOARD_OPTION == MR8120_TX_TRANWO3))
#define ISU_OVERLAY_LARGE_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
#define ISU_OVERLAY_XLARGE_FONT_TYPE    ASCII_FONT_20x24x95_2BIT
#define ISU_OVERLAY_SMALL_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
#elif((HW_BOARD_OPTION == MR8120_TX_RDI) || (HW_BOARD_OPTION == MR8120_TX_RDI_CA671)||\
    (HW_BOARD_OPTION == MR8120_TX_RDI_CA672)|| (HW_BOARD_OPTION == MR8120_TX_RDI_CA532)|| (HW_BOARD_OPTION  == MR8120_TX_RDI_CA542) ||\
    (HW_BOARD_OPTION  == MR8120_TX_RDI_CL692) || (HW_BOARD_OPTION == MR8120_TX_RDI_CA652))
#define ISU_OVERLAY_LARGE_FONT_TYPE     ASCII_FONT_16x20x95_RDI_2BIT
#define ISU_OVERLAY_XLARGE_FONT_TYPE    ASCII_FONT_32x36x95_RDI_2BIT
#define ISU_OVERLAY_SMALL_FONT_TYPE     ASCII_FONT_8x16x95_RDI_2BIT
#else
#define ISU_OVERLAY_LARGE_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
#define ISU_OVERLAY_XLARGE_FONT_TYPE    ASCII_FONT_20x24x95_2BIT
#define ISU_OVERLAY_SMALL_FONT_TYPE     ASCII_FONT_8x16x95_2BIT
#endif

#define ISU_OVL_OPA                     ISU_OVL_OPA_100


#if (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_20x20x95)

#define ASCII_LARGE_FONT_WIDTH      20
#define ASCII_LARGE_FONT_HEIGHT     20
#define ISU_OVL_TYPE                ISU_OVL_TYPE_16Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_32x40x95)

#define ASCII_LARGE_FONT_WIDTH      32
#define ASCII_LARGE_FONT_HEIGHT     40
#define ISU_OVL_TYPE                ISU_OVL_TYPE_16Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_32x48x95)

#define ASCII_LARGE_FONT_WIDTH      32
#define ASCII_LARGE_FONT_HEIGHT     48
#define ISU_OVL_TYPE                ISU_OVL_TYPE_16Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_20x20x95_25)

#define ASCII_LARGE_FONT_WIDTH      20
#define ASCII_LARGE_FONT_HEIGHT     20
#define ISU_OVL_TYPE                ISU_OVL_TYPE_16Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_20x36x95)

#define ASCII_LARGE_FONT_WIDTH      20
#define ASCII_LARGE_FONT_HEIGHT     36
#define ISU_OVL_TYPE                ISU_OVL_TYPE_16Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_20x20x95_DR900)

#define ASCII_LARGE_FONT_WIDTH      20
#define ASCII_LARGE_FONT_HEIGHT     20
#define ISU_OVL_TYPE                ISU_OVL_TYPE_16Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_32x40x95_1BIT)

#define ASCII_LARGE_FONT_WIDTH      32
#define ASCII_LARGE_FONT_HEIGHT     40
#define ISU_OVL_TYPE                ISU_OVL_TYPE_1Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_32x40x95_2BIT)

#define ASCII_LARGE_FONT_WIDTH      32
#define ASCII_LARGE_FONT_HEIGHT     40
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_20x20x95_2BIT)

#define ASCII_LARGE_FONT_WIDTH      20
#define ASCII_LARGE_FONT_HEIGHT     20
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_20x20x95_DOUBLE_FIELD_2BIT)

#define ASCII_LARGE_FONT_WIDTH      20
#define ASCII_LARGE_FONT_HEIGHT     20
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_20x20x95_DOUBLE_FIELD_2BIT_DR900)

#define ASCII_LARGE_FONT_WIDTH      20
#define ASCII_LARGE_FONT_HEIGHT     20
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_20x20x95_2BIT_WITH_LIGHT)

#define ASCII_LARGE_FONT_WIDTH      20
#define ASCII_LARGE_FONT_HEIGHT     20
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_8x16x95_2BIT)

#define ASCII_LARGE_FONT_WIDTH      8
#define ASCII_LARGE_FONT_HEIGHT     16
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA)

#define ASCII_LARGE_FONT_WIDTH      64
#define ASCII_LARGE_FONT_HEIGHT     40
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_16x22x95_COMMAX_2BIT)

#define ASCII_LARGE_FONT_WIDTH      16
#define ASCII_LARGE_FONT_HEIGHT     22
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit


#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_16x20x95_2BIT)

#define ASCII_LARGE_FONT_WIDTH      16
#define ASCII_LARGE_FONT_HEIGHT     20
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_20x24x95_2BIT)

#define ASCII_LARGE_FONT_WIDTH      20
#define ASCII_LARGE_FONT_HEIGHT     24
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_32x28x95_2BIT)

#define ASCII_LARGE_FONT_WIDTH      32
#define ASCII_LARGE_FONT_HEIGHT     28
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_12x16x95_2BIT)

#define ASCII_LARGE_FONT_WIDTH      12
#define ASCII_LARGE_FONT_HEIGHT     16
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_32x36x95_RDI_2BIT)

#define ASCII_LARGE_FONT_WIDTH      32
#define ASCII_LARGE_FONT_HEIGHT     36
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_16x20x95_RDI_2BIT)

#define ASCII_LARGE_FONT_WIDTH      16
#define ASCII_LARGE_FONT_HEIGHT     20
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_8x16x95_RDI_2BIT)

#define ASCII_LARGE_FONT_WIDTH      8
#define ASCII_LARGE_FONT_HEIGHT     16
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#elif (ISU_OVERLAY_LARGE_FONT_TYPE == ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA2)

#define ASCII_LARGE_FONT_WIDTH      64
#define ASCII_LARGE_FONT_HEIGHT     40
#define ISU_OVL_TYPE                ISU_OVL_TYPE_2Bit

#endif





#if (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_20x20x95)

#define ASCII_XLARGE_FONT_WIDTH     20
#define ASCII_XLARGE_FONT_HEIGHT    20

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_32x40x95)

#define ASCII_XLARGE_FONT_WIDTH     32
#define ASCII_XLARGE_FONT_HEIGHT    40

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_32x48x95)

#define ASCII_XLARGE_FONT_WIDTH     32
#define ASCII_XLARGE_FONT_HEIGHT    48

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_20x20x95_25)

#define ASCII_XLARGE_FONT_WIDTH     20
#define ASCII_XLARGE_FONT_HEIGHT    20

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_20x36x95)

#define ASCII_XLARGE_FONT_WIDTH     20
#define ASCII_XLARGE_FONT_HEIGHT    36

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_20x20x95_DR900)

#define ASCII_XLARGE_FONT_WIDTH     20
#define ASCII_XLARGE_FONT_HEIGHT    20

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_32x40x95_1BIT)

#define ASCII_XLARGE_FONT_WIDTH     32
#define ASCII_XLARGE_FONT_HEIGHT    40

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_32x40x95_2BIT)

#define ASCII_XLARGE_FONT_WIDTH     32
#define ASCII_XLARGE_FONT_HEIGHT    40

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_20x20x95_2BIT)

#define ASCII_XLARGE_FONT_WIDTH     20
#define ASCII_XLARGE_FONT_HEIGHT    20

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_20x20x95_DOUBLE_FIELD_2BIT)

#define ASCII_XLARGE_FONT_WIDTH     20
#define ASCII_XLARGE_FONT_HEIGHT    20

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_20x20x95_DOUBLE_FIELD_2BIT_DR900)

#define ASCII_XLARGE_FONT_WIDTH     20
#define ASCII_XLARGE_FONT_HEIGHT    20

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_20x20x95_2BIT_WITH_LIGHT)

#define ASCII_XLARGE_FONT_WIDTH     20
#define ASCII_XLARGE_FONT_HEIGHT    20

#elif ((ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_8x16x95_2BIT) || (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_8x16x95_RDI_2BIT))

#define ASCII_XLARGE_FONT_WIDTH     8
#define ASCII_XLARGE_FONT_HEIGHT    16

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA)

#define ASCII_XLARGE_FONT_WIDTH     64
#define ASCII_XLARGE_FONT_HEIGHT    40

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_16x22x95_COMMAX_2BIT)

#define ASCII_XLARGE_FONT_WIDTH     16
#define ASCII_XLARGE_FONT_HEIGHT    22

#elif ((ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_16x20x95_2BIT) || (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_16x20x95_RDI_2BIT))

#define ASCII_XLARGE_FONT_WIDTH      16
#define ASCII_XLARGE_FONT_HEIGHT     20

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_20x24x95_2BIT)

#define ASCII_XLARGE_FONT_WIDTH      20
#define ASCII_XLARGE_FONT_HEIGHT     24

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_32x28x95_2BIT)

#define ASCII_XLARGE_FONT_WIDTH      32
#define ASCII_XLARGE_FONT_HEIGHT     28

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_12x16x95_2BIT)

#define ASCII_XLARGE_FONT_WIDTH      12
#define ASCII_XLARGE_FONT_HEIGHT     16

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_32x36x95_RDI_2BIT)

#define ASCII_XLARGE_FONT_WIDTH      32
#define ASCII_XLARGE_FONT_HEIGHT     36

#elif (ISU_OVERLAY_XLARGE_FONT_TYPE == ASCII_FONT_64x40x95_2BIT_WITH_ANTENNA2)

#define ASCII_XLARGE_FONT_WIDTH      64
#define ASCII_XLARGE_FONT_HEIGHT     40
#endif



//Lsk 090707 : QVGA
#if (ISU_OVERLAY_SMALL_FONT_TYPE == ASCII_FONT_12x12x95)

#define ASCII_SMALL_FONT_WIDTH      12
#define ASCII_SMALL_FONT_HEIGHT     12

#elif (ISU_OVERLAY_SMALL_FONT_TYPE == ASCII_FONT_12x12x95_2BIT)

#define ASCII_SMALL_FONT_WIDTH      12
#define ASCII_SMALL_FONT_HEIGHT     12

#elif ((ISU_OVERLAY_SMALL_FONT_TYPE == ASCII_FONT_8x16x95_2BIT) || (ISU_OVERLAY_SMALL_FONT_TYPE == ASCII_FONT_8x16x95_RDI_2BIT))

#define ASCII_SMALL_FONT_WIDTH      8
#define ASCII_SMALL_FONT_HEIGHT     16

#endif

typedef struct _ISU_Size {
	u16		w;
	u16		h;
} ISU_Size;

typedef struct _ISU_IOSize {
	u16		inw;
	u16		inh;
	u16		outw;
	u16		outh;
} ISU_IOSize;

#define ISU_FRAME_DURATION_NUM		        8
#if((HW_BOARD_OPTION==DTY_IRDVR))
#define MAX_OVERLAYSTR	100
#elif ((HW_BOARD_OPTION == GOS_DVRBOX)||(HW_BOARD_OPTION==VER100_CARDVR)||(HW_BOARD_OPTION==ELEGANT_KFCDVR)\
    ||(HW_BOARD_OPTION==SUNIN_CARDVR)||(HW_BOARD_OPTION==SUNIN1_CARDVR)||(HW_BOARD_OPTION==SEENEDGE_CARDVR)||(HW_BOARD_OPTION==MR6730_WINEYE))
#define MAX_OVERLAYSTR	128
#elif (HW_BOARD_OPTION == ITS_CARDVR)
#define MAX_OVERLAYSTR	192
#else
#define MAX_OVERLAYSTR	80
#endif

extern s32 isuPreview(s8);
extern s32 isuPreviewZoom(s8);

#if ( (CHIP_OPTION == CHIP_A1013A) || (CHIP_OPTION == CHIP_A1013B) || (CHIP_OPTION == CHIP_A1016A) || (CHIP_OPTION == CHIP_A1016B) || \
    (CHIP_OPTION == CHIP_A1018A) || (CHIP_OPTION == CHIP_A1018B) || (CHIP_OPTION == CHIP_A1020A)||\
    (CHIP_OPTION == CHIP_A1026A))
s32 isuScUpZoom(s32 zoomFactor);
#endif

/*BJ 0530 S*/
extern s32 isuCapture640x480_B2F(s32);
extern s32 isuCapturePrimary_B2F(s32 zoomFactor);
extern s32 isuCapturePrimary_B2B(s32);
extern s32 isuScalar2Thumbnail(s32);
extern s32 isuCaptureVideo(s32);
extern s32 isuVideoZoom(s32);
/*BJ 0530 E*/

extern s32 isuInit(void);
extern void isuIntHandler(void);
extern s32 isuSetIOSize(u16, u16);
extern void isuStop(void);
extern s32 isuPlayback(u8 *,u8 *,u16 , u16);/*BJ 0523 S*/
extern s32 isuPlayback_av(u8 *,u8 *,u16 , u16);   /*Peter 1109 S*/
extern s32 isuGenPauseFrame(u8 *,u8 *,u16 , u16);
extern s32 isuScalar_D2D(u8 *, u8 *, u16, u16, u16, u16);
extern s32 isuScalar_D2D_Deblock(u8 *, u8 *, u16, u16, u16, u16);
extern s32 GenerateOverlayImage(u32 *YUV422Image, char *szString, int MaxStrLen, int FontW, int FontH, int VideoW);
extern s32 GenerateOverlayImage16Bits(u32 *YUV422Image, char *szString, int MaxStrLen, int FontW, int FontH, int VideoW, u8 ASCII_flag);
extern s32 GenerateOverlayImage1Bits(u32 *YUV422Image, char *szString, int MaxStrLen, int FontW, int FontH, int VideoW, u8 ASCII_flag);
extern void ResetisuPanel(void);

extern ISU_Size isuPanel, isuPacket, isuSrcImg;
extern u32 *ScalarOverlayImage;
extern u32 ISUFrameDuration[ISU_FRAME_DURATION_NUM];
extern u32 isuFrameTime;
#if ISU_OVERLAY_ENABLE
extern u8  isuGenerateScalarOverlayImage;
#endif


#endif
