#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ --no_debug --dwarf2 -O3
CARM_SRCS	= 		  .\src\ui_setfile_project.c .\src\ui.c \
		  .\src\ui_node_project.c .\src\ui_flow_project.c \
		  .\src\ui_graph.c .\src\ui_graph_project.c \
		  .\src\ui_osd.c .\src\ui_osd_project.c \
		  .\src\ui_cmd_project.c .\src\ui_act_project.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\ui_setfile_project.o Release\ui.o \
		  Release\ui_node_project.o Release\ui_flow_project.o \
		  Release\ui_graph.o Release\ui_graph_project.o \
		  Release\ui_osd.o Release\ui_osd_project.o \
		  Release\ui_cmd_project.o Release\ui_act_project.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= ui_Release.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\ui.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 36
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\project.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__MEMORYPOOL_H=..\inc\\memorypool.h ..\inc\\iduapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) $(___INC__MEMORYPOOL_H) 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) 
INC__UI_H=inc\\ui.h $(___INC__FSAPI_H) 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\task.h ..\inc\\rtcapi.h \
	 ..\inc\\uikey.h 
___INC__ASFAPI_H=..\inc\\asfapi.h $(___INC__FSAPI_H) 
INC__UIMENU_PROJECT_H=inc\\uimenu_project.h $(___INC__UIAPI_H) $(INC__UI_H) 
___INC__I2CAPI_H=..\inc\\i2capi.h ..\inc\\rtcapi.h 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__TIMERAPI_H=..\inc\\timerapi.h $(___INC__GENERAL_H) 
INC__UI_PROJECT_H=inc\\ui_project.h ..\inc\\motiondetect_api.h 
___INC__UARTAPI_H=..\inc\\uartapi.h ..\inc\\task.h 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__ADCAPI_H=..\inc\\adcapi.h 
# DEPEND: end include files

Release\ui_setfile_project.o: .\src\ui_setfile_project.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ui_setfile_project.c $(CARM) -o Release\ui_setfile_project.o
Release\ui.o: .\src\ui.c ..\inc\\board.h ..\inc\\sysapi.h ..\inc\\spiapi.h \
	 $(___INC__ASFAPI_H) $(INC__UIMENU_PROJECT_H) ..\inc\\mpeg4api.h \
	 $(___INC__I2CAPI_H) $(___INC__SIUAPI_H) $(___INC__TIMERAPI_H) \
	 inc\\osd_draw_project.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\ui.c $(CARM) \
	 -o Release\ui.o
Release\ui_node_project.o: .\src\ui_node_project.c $(INC__UI_H) \
	 $(___INC__UIAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ui_node_project.c $(CARM) -o Release\ui_node_project.o
Release\ui_flow_project.o: .\src\ui_flow_project.c ..\inc\\board.h \
	 $(INC__UI_H) ..\inc\\sysapi.h $(___INC__UIAPI_H) ..\inc\\spiapi.h  \
	 $(___INC__SIUAPI_H) $(___INC__TIMERAPI_H) inc\\osd_draw_project.h \
	 ..\inc\\usbapi.h  ..\inc\\isuapi.h  $(___INC__DCFAPI_H) \
	 ..\inc\\aviapi.h ..\inc\\ipuapi.h ..\inc\\asfapi.h \
	 inc\\ui_project.h ..\inc\\uartapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ui_flow_project.c $(CARM) -o Release\ui_flow_project.o
Release\ui_graph.o: .\src\ui_graph.c $(___INC__GENERAL_H)  \
	 $(___INC__UIAPI_H) ..\inc\\spiapi.h $(___INC__DCFAPI_H) \
	 ..\inc\\jpegapi.h ..\inc\\fsapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\ui_graph.c \
	 $(CARM) -o Release\ui_graph.o
Release\ui_graph_project.o: .\src\ui_graph_project.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h  ..\inc\\sysapi.h $(___INC__UIAPI_H) \
	 ..\inc\\spiapi.h $(INC__UI_PROJECT_H) $(___INC__DCFAPI_H) \
	 ..\inc\\jpegapi.h inc\\ui.h ..\inc\\fsapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ui_graph_project.c $(CARM) -o Release\ui_graph_project.o
Release\ui_osd.o: .\src\ui_osd.c $(___INC__GENERAL_H)  $(___INC__UIAPI_H) \
	 inc\\osdlib.h inc\\ui.h ..\inc\\fsapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\ui_osd.c \
	 $(CARM) -o Release\ui_osd.o
Release\ui_osd_project.o: .\src\ui_osd_project.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h  ..\inc\\sysapi.h $(___INC__UIAPI_H) \
	 $(___INC__ASFAPI_H) $(___INC__SIUAPI_H) inc\\osd_draw_project.h  \
	 ..\inc\\isuapi.h $(___INC__DCFAPI_H) ..\inc\\aviapi.h \
	 inc\\osdlib_project.h ..\inc\\ciuapi.h inc\\ui.h inc\\ui_project.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ui_osd_project.c $(CARM) -o Release\ui_osd_project.o
Release\ui_cmd_project.o: .\src\ui_cmd_project.c $(___INC__GENERAL_H)  \
	 ..\inc\\sysapi.h $(___INC__UIAPI_H) $(INC__UI_PROJECT_H) \
	 ..\inc\\gpioapi.h inc\\ui.h ..\inc\\fsapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ui_cmd_project.c $(CARM) -o Release\ui_cmd_project.o
Release\ui_act_project.o: .\src\ui_act_project.c $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\sysapi.h $(___INC__UIAPI_H) \
	 $(___INC__ASFAPI_H) ..\inc\\mpeg4api.h $(___INC__SIUAPI_H)  \
	 ..\inc\\isuapi.h ..\inc\\ciuapi.h $(___INC__ADCAPI_H) \
	 inc\\ui_project.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ui_act_project.c $(CARM) -o Release\ui_act_project.o
