#ifndef WEB_UTIL_H
#define WEB_UTIL_H

#include <AsEngine.h>
#include <AsConfig.h>
#include "AsTypes.h"
#include "Web_flag.h"

#ifndef TRUE
#define TRUE  1
#endif

#ifndef FALSE
#define FALSE 0
#endif

#ifndef DISABLED
#define DISABLED 2
#define ENABLED  3
#endif

#ifdef HPF
#undef HPF
#endif
#define HPF	hprintf
#define HPF_Menu	hprintf_Menu
char* hprintf(char *format, ...);
char* hprintf_Menu(char *format, ...);

#if 0
#define MAX_PAGE_SIZE		20
#define WEB_MAX_TABLE_SIZE		20
#define WEB_CLASS_NUMBER	8

#define NEXT_BUTTON		2
#define PREV_BUTTON		3

#define NOBTN		0
#define PREVONLY	1
#define NEXTONLY		2
#define BOTHBTN		3


#define DMY_SW_VLAN_CTRL_IEEE8021Q	1
#define DMY_SW_VLAN_CTRL_PORT_BASED	2

#define PRESSPREV	1
#define PRESSNEXT	2
#define PRESSFIND	3

#define WEB_PAGE_DIVIDEFLAG		1

#define WEB_NAME_SIZE				64
#define WEB_NAME_LENGTH			33



#define INITIALFIRST	0
#define PRESSPREV	1
#define PRESSNEXT	2
#define PRESSFIND	3

#define NOBOTTON	0
#define PREVONLY	1
#define NEXTONLY		2
#define BOTHBOTTON	3

/*-----802.1v-----*/

#define WEB_8021_MAX_ENTRY 7
#define WEB_8021_MAX_PROFILE 24

/*-----loopback interface-----*/
#define WEB_MAX_VIR_IN_NAME_LEN 12

//========================  SNMP V3 page defined parameter ==============

#define Snmp_v1v2		0
#define Snmp_v1v2v3	1
#define Web_EngineID_length	64+1

#define WEB_SNMP_NAME_LEN			32+1
#define WEB_SNMP_SMALLSTR_LEN			20+1
#define WEB_SNMP_MIDSTR_LEN			32+1
#define WEB_SNMP_TRANSPORT_LEN	255+1
#define WEB_SNMP_MAXSTR_LEN	255+1

#define WEB_SNMP_SUBTREE_OIDLENGTH		128
#define WEB_SNMP_OID_DISPLAYLEN			16
#define WEB_TABLE_TYPE_INITIAL		1  // Table initial , first page
#define WEB_TABLE_TYPE_NEXT		2  // press "Next" button
#define WEB_TABLE_TYPE_PREV		3  // press "Prev" button

//========================  SNMP V3 page defined End ===================
#endif

typedef unsigned char UCHAR;

/* ----------------------------------------------------- */
/*					Web Error Code						 */
/* ----------------------------------------------------- */

typedef enum
{
	//---------------------------- General Start----------------------------------
	WEB_ERROR_INITIAL=0x0000,
	WEB_ERROR_NO_ERROR=0x0001,
	WEB_ERROR_GET_FAIL=0x0002,
	WEB_ERROR_SET_ERROR=0x0003,
	WEB_ERROR_ENTRY_NOT_EXIST=0x0004,
	WEB_ERROR_ENTRY_ALREADY_EXIST=0x0005,
	WEB_ERROR_TABLE_FULL=0x0006,
	//---------------------------- General Stop ----------------------------------
	WEB_ERROR_MIRROR_UPDATE_FAIL=0x1601,
	WEB_ERROR_MIRROR_TARGETPORT_INVALID=0x1602,
	WEB_ERROR_TRUNK_UPDATE_FAIL=0x1701,
	WEB_ERROR_TRUNK_GROUPNAME_INVALID=0x1702,
	WEB_ERROR_TRUNK_GROUPID_INVALID=0x1703,
	WEB_ERROR_TRUNK_MASTERPORT_INVALID=0x1704,
	WEB_ERROR_TRUNK_OVERLAP_GROUP=0x1705,
	WEB_ERROR_TRUNK_UNIT_GROUPNUM=0x1706,
	WEB_ERROR_TRUNK_PORT_LINK_ERROR=0x1707,
	WEB_ERROR_TRUNK_PORT_TYPE_ERROR=0x1708,
	WEB_ERROR_TRUNK_MIRROR_ERROR=0x1709,
	WEB_ERROR_IS_NOT_MASTER_PORT=0X1710,
	WEB_ERROR_TRUNK_MBA_PORT_OVERLAP=0X1711,
	WEB_ERROR_IGMP_VLAN_NOT_EXIST=0x1811,
	WEB_ERROR_IGMP_UPDATE_FAIL=0x1812,
	WEB_ERROR_IGMP_TIMER_NOT_CHANGE=0x1813,
	WEB_ERROR_STATIC_ROUTERPORT_UPDATE_FAIL=0x1821,
	WEB_ERROR_FORWARD_UNI_UPDATE_FAIL=0x1a11,
	WEB_ERROR_FORWARD_UNI_VID_NOTEXIST=0x1a12,
	WEB_ERROR_FORWARD_MULTI_UPDATE_FAIL=0x1a21,
	WEB_ERROR_FORWARD_MULTI_VID_NOTEXIST=0x1a22,
	WEB_ERROR_FILTER_UPDATE_FAIL=0x1a31,
	WEB_ERROR_FILTER_ENTRY_HAD_EXIST=0x1a32,
	WEB_ERROR_8021QVLAN_VID_ERROR=0x1b11,
	WEB_ERROR_8021QVLAN_UNTAGE_OVERLAP=0x1b12,
	WEB_ERROR_8021QVLAN_VLAN_ID_EXIST=0x1b13,
	WEB_ERROR_ROUTER_MAC_UPDATE_FAIL=0x1b31,
	WEB_ERROR_ROUTER_MAC_ENTRY_HAD_EXIST=0x1b32,
	WEB_ERROR_ROUTER_MAC_VID_NOT_EXIST=0x1b33,
	WEB_ERROR_ROUTER_MAC_ENTRY_FULL=0x1b34,
	WEB_ERROR_ROUTER_MAC_MAC_EXIST=0x1b35,
	WEB_ERROR_ROUTER_MAC_MAC_NOT_FOUND=0x1b36,
	WEB_ERROR_CFGIP_UPDATE_FAIL=0x2101,
	WEB_ERROR_CFGIP_VLAN_NOTEXIST=0x2102,
	WEB_ERROR_CFGIP_ROUTE_UPDATE_FAIL=0x2103,
	WEB_ERROR_USER_ACCOUNT_UPDATE_FAIL=0x2601,
	WEB_ERROR_USER_ACCOUNT_NEED_ADMINUSER=0x2602,
	WEB_ERROR_USER_ACCOUNT_USER_HAD_EXIST=0x2603,
	WEB_ERROR_USER_ACCOUNT_USERNAME_INVALID=0x2604,
	WEB_ERROR_USER_ACCOUNT_ERR_DEL_USER_PWD=0x2605,
	WEB_ERROR_USER_ACCOUNT_USER_TABLE_FULL=0x2606,
	WEB_ERROR_FACTORYRESET_FINISH=0x4401,
	WEB_ERROR_PING_INVALID_IPADDRESS=0x4201,
	WEB_ERROR_IPADDR_INVALID=0X5702,
	WEB_USER_PWD_NOTMACTH=0X2116,
	WEB_USER_OLDPWD_NOTMACTH=0X2117,
	WEB_DEVICE_BUSY=0X2118,
	WEB_ACL_PROFILE_ID_NOTEXIST=0X2119,
	WEB_ACL_ICMP_VALUE_ERROR=0x2120,
	WEB_ACL_IGMP_VALUE_ERROR=0x2121,
	WEB_ACLRULE_SOURPORT_VALUE_ERROR=0X2122,
	WEB_ACLRULE_DESTPORT_VALUE_ERROR=0X2123,
	WEB_ACLRULE_DSCP_VALUE_ERROR=0X2124,
	WEB_ACLRULE_P8021P_VALUE_ERROR=0X2125,
	//-----------------------------------------------------------------------
	WEB_ERROR_PORTLOCK_NOT_EXIST=0x1001,
	WEB_ERROR_PORTLOCK_NOT_ENABLE=0x1002,
	WEB_ERROR_PORTLOCK_NOT_CORRECT=0x1003,
	WEB_ERROR_IPADDR_NOT_BOOT_MODE=0x1004,
	//---------------------------- L3 Start ----------------------------------
	WEB_ERROR_L3_CFGMD5_KEYINDEX_EXIST=0x5101,
	WEB_ERROR_L3_CFGMD5_UPDATE_FAIL=0x5102,
	WEB_ERROR_L3_CFGRTRED_ENTRY_EXIST=0x5201,
	WEB_ERROR_L3_CFGRTRED_UPDATE_FAIL=0x5202,
	WEB_ERROR_L3_IGMPIF_UPDATE_FAIL=0x5301,
	WEB_ERROR_L3_IGMPIF_GET_FAIL=0x5302,
	WEB_ERROR_L3_IPIF_GET_FAIL=0x5401,
	WEB_ERROR_L3_IPIF_UPDATE_FAIL=0x5402,
	WEB_ERROR_L3_IPIF_VLAN_NOTEXIST=0x5453,
	WEB_ERROR_L3_IPIF_ENTRY_EXIST=0x5403,
	WEB_ERROR_L3_IPIF_INVALID_HOST_ADDRESS=0x5404,
	WEB_ERROR_L3_DVMRPIF_UPDATE_FAIL=0x5501,
	WEB_ERROR_L3_DVMRPIF_GET_FAIL=0x5502,
	WEB_ERROR_L3_PIMDMIF_UPDATE_FAIL=0x5601,
	WEB_ERROR_L3_PIMDMIF_GET_FAIL=0x5602,
	WEB_ERROR_L3_GLOBALCFG_UPDATE_FAIL=0x5701,
	WEB_ERROR_L3_CFGAREAID_EXIST=0x5001,
	WEB_ERROR_L3_CFGAREAID_UPDATE_FAIL=0x5002,
	WEB_ERROR_L3_INVALID_INTERFACE_NAME=0x5703,
	WEB_ERROR_L3_SECONDARY_IP_NOT_SUPPORT_BPR=0x5704,
	WEB_ERROR_L3_IGMP_ENABLE_ERROR=0X5705,
	WEB_ERROR_L3_IGMPFASTLEAVE_ENABLE_ERROR=0X5706,
	WEB_ERROR_L3_RIPV1_NOT_SUPPORT_AUTHENTICATION=0X5707,
	WEB_ERROR_L3_IPIF_ARP_ON_IPIF=0x5708,
	WEB_ERROR_L3_IPIF_SETTING_NOTE=0x5709,
	// --------------------------------- L3 End -----------------------------
	// ---------- ACL Start ------------------------------------
	WEB_ERROR_ACL_ID_EXIST=0x2105,
	WEB_ERROR_ACL_PROFILE_ID_NOTEXIST=0x2119,
	WEB_ERROR_ACL_ICMP_VALUE_INVALID=0x2120,
	WEB_ERROR_ACL_IGMP_VALUE_INVALID=0x2121,
	WEB_ERROR_ACL_RULE_SOURPORT_VALUE_INVALID=0x2122,
	WEB_ERROR_ACL_RULE_DESTPORT_VALUE_INVALID=0x2123,
	WEB_ERROR_ACL_RULE_DSCP_VALUE_INVALID=0X2124,
	WEB_ERROR_ACL_RULE_P8021P_VALUE_INVALID=0X2125,
	WEB_ERROR_ACL_SET_RULE_NOTEXIST=0x2126,
	WEB_ERROR_ACL_SET_RULE_FULL=0x2127,
	WEB_ERROR_ACL_SET_RULE_PARTIAL_FAIL=0x2128,
	WEB_ERROR_ACL_IF_ERR_NOT_MEMBER=0x2129,              /* rule port is not a member of profile */
	WEB_ERROR_ACL_IF_ERR_PORT_INCONSISTENT=0x2130,
	WEB_ERROR_ACL_IF_ERR_RULEBODY_DUPLICATED=0x2131,      /* RULE BODY is duplicated even difference access id */
	WEB_ERROR_ACL_ENTRY_NOT_OWNED_BY_ACL=0x2132,
	WEB_ERROR_ACL_METERING_FULL=0x2133,
	WEB_ERROR_ACL_NOT_CREATED_BY_ACL=0x2134,
	WEB_ERROR_SOFT_ACL_TABLE_FULL=0x2135,
	// ---------- ACL End ------------------------------------
	// ---------- SNMP V3 start ------------------------
	WEB_ERROR_AuthProtocol_PWD=0x2106,
	WEB_ERROR_PrivProtocol_PWD=0x2107,
	WEB_INVALID_HOST_ADDRESS=0x2108,
	WEB_BAD_MASK=0x2109,
	WEB_SNMP_HOST_EXIST=0X2110,
	WEB_SNMP_COMMUNITY_VIEWNAME_NOTEXIST=0x2111,
	WEB_SNMP_USER_GROUPNAME_NOT_EXIST=0x2112,
	WEB_SNMP_USER_USERNAME_EXIST=0x2113,
	WEB_SNMP_VIEW_EXIST=0X2114,
	WEB_SNMP_COMMUNITY_NAME_EXIST=0x2115,
	WEB_SET_SNMP_VIEW_FULL=0X5806,
	WEB_SET_SNMP_COMMUNITY_FULL=0X5807,
	WEB_SET_SNMP_GROUP_FULL=0X5808,
	WEB_SET_SNMP_USER_FULL=0X5809,
	WEB_SET_SNMP_HOST_FULL=0X5810,
	// ---------- SNMP V3 end ------------------------
	// ---------- FS Command start -------------------
	WEB_ERROR_FS_INVALID_DRV_NAME=0x3001,
	WEB_ERROR_FS_SAME_FILE=0x3002,
	WEB_ERROR_FS_ROOT_DISKFULL=0x3003,
	WEB_ERROR_FS_DISKFULL=0x3004,
	WEB_ERROR_FS_INVALID_DIR=0x3005,
	WEB_ERROR_FS_FILE_RO=0x3006,
	WEB_ERROR_FS_NO_STORAGE=0x3007,
	WEB_ERROR_FS_FSTYPE_ERROR=0x3008,
	WEB_ERROR_FS_ERROR_INPUT=0x3009,
	WEB_ERROR_FS_SAME_DIR=0x3010,
	WEB_ERROR_FS_NO_FILE_DIR=0x3011,
	WEB_ERROR_FS_NO_FORMAT=0x3012,
	WEB_ERROR_FS_ERROR_CHAR=0x3013,
	WEB_ERROR_FS_ERROR_FILENAME=0x3014,
	WEB_ERROR_FS_EXIST_FILE_INDIR=0x3015,
	WEB_ERROR_FS_INPUT_MEDIA_ID=0x3016,
	WEB_ERROR_FS_CF_BUSY=0x3017,
	WEB_ERROR_FS_DEVICE_BUSY=0x3018,
	// ---------- FS Command end ---------------------
	WEB_ERROR_VRRP_INVALID_IP=0x4017,
	WEB_ERROR_VRRP_ENTRY_FULL=0x4018,
	WEB_ERROR_VRRP_ROUTER_EXISTS=0x4019,
	WEB_ERROR_VRRP_SET_ERROR=0x4020,
	WEB_ERROR_VRRP_SET_IP_ERROR=0x4021,
	WEB_ERROR_VRRP_NO_ENTRY=0x4022,
	WEB_ERROR_VRRP_SET_CRITICAL_ERROR=0x4023,
	WEB_ERROR_VRRP_ENABLE_CRITICAL_ERROR=0x4024,
	WEB_ERROR_VRRP_SET_AUTH_FAIL=0x4025,
	WEB_ERROR_VRRP_CANT_CONFIG=0x4026,
	/* ----------- AAA Command start ----------------- */
	WEB_ERROR_AAA_ENTRY_NOT_EXIST=0x1d01,
	WEB_ERROR_AAA_ENTRY_ALREADY_EXIST=0x1d02,
	WEB_ERROR_AAA_EEPROM_IS_FULL=0x1d03,
	WEB_ERROR_AAA_CONSOLE_LOGIN_METHOD_LIST_NOT_EXIST=0x1d04,
	WEB_ERROR_AAA_TELNET_LOGIN_METHOD_LIST_NOT_EXIST=0x1d05,
	WEB_ERROR_AAA_SSH_LOGIN_METHOD_LIST_NOT_EXIST=0x1d06,
	WEB_ERROR_AAA_HTTP_LOGIN_METHOD_LIST_NOT_EXIST=0x1d07,
	WEB_ERROR_AAA_CONSOLE_ENABLE_METHOD_LIST_NOT_EXIST=0x1d08,
	WEB_ERROR_AAA_TELNET_ENABLE_METHOD_LIST_NOT_EXIST=0x1d09,
	WEB_ERROR_AAA_SSH_ENABLE_METHOD_LIST_NOT_EXIST=0x1d0a,
	WEB_ERROR_AAA_HTTP_ENABLE_METHOD_LIST_NOT_EXIST=0x1d0b,
	WEB_ERROR_AAA_DEFAULT_LOGIN_METHOD_LIST_CANNOT_DELETE=0x1d0c,
	WEB_ERROR_AAA_DEFAULT_ENABLE_METHOD_LIST_CANNOT_DELETE=0x1d0d,
	WEB_ERROR_AAA_FIRST_METHOD_CANNOT_EMPTY=0x1d0e,
	WEB_ERROR_AAA_USER_DEFINED_SERVER_GROUP_NOT_EXIST=0x1d0f,
	WEB_ERROR_AAA_BUILT_IN_TACACS_SERVER_GROUP_NOT_EXIST=0x1d10,
	WEB_ERROR_AAA_BUILT_IN_XTACACS_SERVER_GROUP_NOT_EXIST=0x1d11,
	WEB_ERROR_AAA_BUILT_IN_TACACS_PLUS_SERVER_GROUP_NOT_EXIST=0x1d12,
	WEB_ERROR_AAA_BUILT_IN_RADIUS_SERVER_GROUP_NOT_EXIST=0x1d13,
	WEB_ERROR_AAA_TACACS_SERVER_HOST_NOT_EXIST=0x1d14,
	WEB_ERROR_AAA_XTACACS_SERVER_HOST_NOT_EXIST=0x1d15,
	WEB_ERROR_AAA_TACACS_PLUS_SERVER_HOST_NOT_EXIST=0x1d16,
	WEB_ERROR_AAA_RADIUS_SERVER_HOST_NOT_EXIST=0x1d17,
	WEB_ERROR_AAA_ANY_SERVER_HOST_NOT_EXIST=0x1d18,
	WEB_ERROR_AAA_HOST_IN_USER_DEFINED_SERVER_GROUP_NOT_EXIST=0x1d19,
	WEB_ERROR_AAA_HOST_IN_TACACS_SERVER_GROUP_NOT_EXIST=0x1d1a,
	WEB_ERROR_AAA_HOST_IN_XTACACS_SERVER_GROUP_NOT_EXIST=0x1d1b,
	WEB_ERROR_AAA_HOST_IN_TACACS_PLUS_SERVER_GROUP_NOT_EXIST=0x1d1c,
	WEB_ERROR_AAA_HOST_IN_RADIUS_SERVER_GROUP_NOT_EXIST=0x1d1d,
	WEB_ERROR_AAA_INVALID_METHOD_NAME=0x1d1e,
	WEB_ERROR_AAA_INVALID_SERVER_GROUP_NAME=0x1d1f,
	WEB_ERROR_AAA_SPECIFIC_SERVER_HOST_NOT_EXIST=0x1d20,
	WEB_ERROR_AAA_SERVER_HOST_ALREADY_IN_SERVER_GROUP=0x1d21,
	WEB_ERROR_AAA_FULL_SERVER_HOST_IN_SERVER_GROUP=0x1d22,
	WEB_ERROR_AAA_DUPLICATE_METHOD_IN_A_METHOD_LIST=0x1d23,
	WEB_ERROR_AAA_BUILT_IN_SERVER_GROUP_ACCEPT_SERVER_HOST_WITH_SAME_PROTOCOL=0x1d24,
	WEB_ERROR_AAA_SERVER_HOST_CREATE_SUCCESS_SERVER_GROUP_ADD_FAIL=0x1d25,
	WEB_ERROR_AAA_SERVER_HOST_TABLE_FULL=0x1d26,
	WEB_ERROR_AAA_SERVER_HOST_IP_CAN_NOT_BE_LOCAL_INTERFACE=0x1d27,
	WEB_ERROR_AAA_SERVER_GROUP_TABLE_FULL=0x1d28,
	WEB_ERROR_AAA_ENTRY_ALREADY_EXISTS=0x1d29,
	/* ----------- AAA Command end ------------------- */
	/* ----------- SSL Command start ----------------- */
	WEB_ERROR_SSL_CERT_DOWNLOAD_RESULT_TFTP_FAIL=0x1e01,
	WEB_ERROR_SSL_CERT_DOWNLOAD_RESULT_DECODE_FAIL=0x1e02,
	/* ----------- SSL Command end ------------------- */
	/* ----------- 802.1x Command start -------------- */
	WEB_ERROR_1X_GET_STATUS_FAIL=0x1f01,
	WEB_ERROR_1X_GET_MODE_FAIL=0x1f02,
	WEB_ERROR_1X_STATUS_NOT_ENABLE=0x1f03,
	WEB_ERROR_1X_INVALID_MAC_ADDRESS=0x1f04,
	/* ----------- 802.1x Command end ---------------- */
	/* ----------- STP Command start ----------------- */
	WEB_ERROR_STP_NOT_MASTER=0x2000,
	WEB_ERROR_STP_FAIL=0x2001,
	WEB_ERROR_STP_SUCCESS=0x2002,
	WEB_ERROR_STP_MSTI_ID_NOT_EXIST=0x2003,
	WEB_ERROR_STP_MSTI_ID_ALREADY_EXIST=0x2004,
	WEB_ERROR_STP_MSTI_TABLE_FULL=0x2005,
	WEB_ERROR_STP_MSTI_VID_OCCUPIED_BY_OTHER_MSTI=0x2006,
	WEB_ERROR_STP_MSTI_VID_OUT_OF_RANGE=0x2007,
	WEB_ERROR_STP_MSTI_NO_BRIDGE_HELLOTIMEv=0x2008,
	WEB_ERROR_STP_MSTI_NO_PORT_HELLOTIME=0x2009,
	WEB_ERROR_STP_BRIDGE_PRIORITY_INVALID=0x200a,
	WEB_ERROR_STP_BRIDGE_PRIORITY_GRANULARITY_INVALID=0x200b,
	WEB_ERROR_STP_BRIDGE_VERSION_INVALID=0x200c,
	WEB_ERROR_STP_BRIDGE_MAXAGE_INVALID=0x200d,
	WEB_ERROR_STP_BRIDGE_MAXHOPS_INVALID=0x200e,
	WEB_ERROR_STP_BRIDGE_FWDDELAY_INVALID=0x200f,
	WEB_ERROR_STP_BRIDGE_FWDDELAY_AND_MAXAGE_INCONSISTENT=0x2010,
	WEB_ERROR_STP_BRIDGE_HELLOTIME_AND_MAXAGE_INCONSISTENT=0x2011,
	WEB_ERROR_STP_BRIDGE_TXHOLDCOUNT_INVALID=0x2012,
	WEB_ERROR_STP_BRIDGE_HAS_THE_SAME_VALUE=0x2013,
	WEB_ERROR_STP_STP_ALREADY_ENABLED=0x2014,
	WEB_ERROR_STP_STP_ALREADY_DISABLED=0x2015,
	WEB_ERROR_STP_PORT_INVALID=0x2016,
	WEB_ERROR_STP_PORT_STACKING=0x2017,
	WEB_ERROR_STP_PORT_PRIORITY_INVALID=0x2018,
	WEB_ERROR_STP_PORT_PRIORITY_GRANULARITY_INVALID=0x2019,
	WEB_ERROR_STP_PORT_HELLOTIME_INVALID=0x201a,
	WEB_ERROR_STP_PORT_PATHCOST_INVALID=0x201b,
	WEB_ERROR_STP_PORT_TRUNK_MEMBER_PORT=0x201c,
	WEB_ERROR_STP_PORT_1DPATHCOST_INVALID=0x201d,
	/* ----------- STP Command end ------------------- */
       /* ----------- IPBIND Command start --------------- */
       WEB_ERROR_IP_MAC_BINDING_PORT_SEC = 0x2201,
	WEB_ERROR_IP_MAC_BINDING_TRUNK = 0x2202,
	WEB_ERROR_IP_MAC_BINDING_IP_FAIL = 0x2203,
	WEB_ERROR_IP_MAC_BINDING_MAC_FAIL = 0x2204,
	WEB_ERROR_IP_MAC_BINDING_STATIC_MAC = 0x2205,
	WEB_ERROR_IP_MAC_BINDING_STATIC_ARP = 0x2206,
	WEB_ERROR_IP_MAC_BINDING_ACL_MASK_FAIL = 0x1f07,
	WEB_ERROR_IP_MAC_BINDING_SET_PORT_ACL_RULE_FAIL = 0x1f08,
	WEB_ERROR_IP_MAC_BINDING_ACL_RULE_FAIL = 0x1f09,
       /* ----------- IPBIND Command end ---------------- */
       /*--------------MAC Based Authentication START--------*/
        WEB_ERROR_MBA_PORTSECURITY = 0x2401,
        WEB_ERROR_MBA_AUTH_STATUS_FAIL = 0x2402,
        WEB_ERROR_MBA_FAILURE = 0x2403,
        WEB_ERROR_MBA_PORT_CONFLICT = 0x2404,
        WEB_ERROR_MBA_GUEST_VLAN_INEXISTENT = 0x2405,
        WEB_ERROR_MBA_GVRP_INFO_ERROR = 0x2406,
        WEB_ERROR_MBA_DOUBLE_VLAN_MODE_ENABLED = 0x2407,
        WEB_ERROR_MBA_VLAN_CONFLICT = 0x2408,
        WEB_ERROR_MBA_RELATIVE_VLAN_INEXISTENT = 0x2409,
	WEB_ERROR_MBA_ENTRY_EXISTENT = 0x2410,
	WEB_ERROR_MBA_TABLE_FULL = 0x2411,
	WEB_ERROR_MBA_ENTRY_INEXISTENT = 0x2412,
	WEB_ERROR_MBA_ENTRY_DELETE_FAIL = 0x2413,
	WEB_ERROR_MBA_GVRP_ENABLE = 0x2414,
	WEB_ERROR_MBA_WAU_GVLAN_ENABLE = 0x2415,
	WEB_ERROR_MBA_GVRP_WAU_GVLAN_ENABLE = 0x2416,
	WEB_ERROR_MBA_VLAN_INEXISTENT = 0x2417,
	WEB_ERROR_MBA_INVALID_PASSWORD = 0x2418,
	WEB_ERROR_GVRP_MBA_PORT = 0x2419,
	WEB_ERROR_GVRP_MBA_GUEST_VLAN_PORT = 0x241a,
	/*--------------MAC Based Authentication END--------*/
    /* ----------- MISC Command start ---------------- */
    WEB_ERROR_WAU_INTERFACE_DISBALE = 0x2301,
    WEB_ERROR_WAU_GVLAN_INCLUDE = 0x2302,
    WEB_ERROR_WAU_INCLUDE = 0x2303,
    WEB_ERROR_GVLAN_INCLUDE = 0x2304,
    WEB_ERROR_WAU_VLAN = 0x2305,
    WEB_ERROR_GVLAN_VLAN = 0x2306,
    WEB_ERROR_WAU_INTERFACE_DELETE = 0x2307,
    WEB_ERROR_WAU_ENABLE = 0x2308,
    WEB_ERROR_SNOOP_RET_CONFLICT_VLAN = 0x2309,
    WEB_ERROR_SNOOP_RET_DUPLICAT_ENTRY = 0x2310,
    WEB_ERROR_SNOOP_RET_TABLE_FULL = 0x2311,
    WEB_ERROR_SNOOP_RET_OUT_RANGE = 0x2312,
    WEB_ERROR_SNOOP_RET_OVERLAP = 0x2313,
    WEB_ERROR_SNOOP_RET_NOT_EXIST = 0x2314,
    WEB_ERROR_PORT_PARTIAL_SETTING_FAIL = 0x231a,
    WEB_ERROR_DEL_CFG_DOESNT_EXIST = 0x231b,
    WEB_ERROR_DEL_CFG_INVALID_ID = 0x231c,
    WEB_ERROR_DEL_CFG_IS_ACTIVE = 0x231d,
    WEB_ERROR_DEL_CFG_ERASE_ERROR = 0x231e,
    /* ----------- MISC Command end ---------------- */
	/* -----------------802.1V START----------------- */
	WEB_ERROR_8021V_GROUP_ID_FAIL = 0x2315,
	WEB_ERROR_8021V_GROUP_DB_FULL = 0x2316,
	WEB_ERROR_8021V_DEUPLICATE_GROUP = 0x2317,
	WEB_ERROR_8021V_NO_GROUP_ENTRY = 0x2318,
	WEB_ERROR_8021V_INEXITENT_ENTRY = 0x2319,
	WEB_ERROR_8021V_PROTOCOL_SIZE_FULL = 0x2320,
	WEB_ERROR_8021V_PROTOCOL_EXISTED = 0x2321,
	WEB_ERROR_8021V_PROTOCOL_INEXISTENT = 0x2322,
	WEB_ERROR_8021V_PROTOCOL_INVALID = 0x2323,
	WEB_ERROR_8021V_GROUP_ID_EMPTY = 0x2324,
	WEB_ERROR_8021V_VLAN_NOT_EXIST = 0x2325,
	WEB_ERROR_8021V_VLAN_IS_PROTOCOL_VLAN = 0x2326,
    WEB_ERROR_8021V_LLC_ENTRY_FULL = 0x2327,
    WEB_ERROR_8021V_LLC_USERDEF_ENTRY_FULL = 0x2328,
    WEB_ERROR_8021V_LLC_DEFSEL_ENTRY_FULL = 0x2329,
	/* -----------------802.1V END------------------- */
	/* --------------------MLD Snooping start------------------- */
    WEB_ERROR_MLD_VLAN_NAME_ERROR = 0x2500,
	WEB_ERROR_MLD_VLAN_NOT_EXIT = 0x2501,
	WEB_ERROR_MLD_CANNOT_CHANGE = 0x2502,
	WEB_ERROR_MLD_MLD_ENABLED = 0x2503,
	WEB_ERROR_MLD_SET_FASTDONE = 0x2504,
	WEB_ERROR_MLD_TRUNK_FAILED = 0x2505,
	WEB_ERROR_MLD_PORT_NOT_EXIST = 0x2506,
	WEB_ERROR_MLD_ROUTER_PORT_EXIST = 0x2507,
	WEB_ERROR_MLD_ROUTER_PORT_NOT_VLAN_MEMBER = 0x2508,
	WEB_ERROR_8021V_OVERLAPPED = 0x2509,
	/* --------------------MLD Snooping end--------------------- */
    /* --------------------check trunk start------------------- */
    WEB_ERROR_CHECK_TRUNK_PORTLIST_FAIL = 0x2701,
    /* --------------------check trunk start------------------- */
    /* --------------------loopback interface start------------------- */
    WEB_ERROR_VIR_IN_NAME_EXIST = 0x2801,
    WEB_ERROR_VIR_IN_NO_IP_EXIST = 0x2802,
    WEB_ERROR_VIR_IN_INV_ADDR = 0x2803,
    WEB_ERROR_VIR_IN_SYS_NOT_DEL = 0x2804,
    WEB_ERROR_VIR_IN_NAME_NOT_EXIST = 0x2805,
    WEB_ERROR_VIR_IN_DEL_FAIL = 0x2806,
    /* --------------------loopback interface end------------------- */
    /* --------------------limit multicast range start------------------- */
    WEB_ERROR_MCAST_DEL_ATTA_PORT = 0x2901,
    /* --------------------limit multicast range end------------------- */
    /* --------------------delete firmware start------------------- */
    WEB_ERROR_DEL_FIRM_LAST_CANNOT_DEL = 0x3101,
    WEB_ERROR_DEL_FIRM_INVALID_IMAGE = 0x3102,
    WEB_ERROR_DEL_FIRM_CANNOT_DEL_BOOT = 0x3103,
    /* --------------------delete firmware end------------------- */

	/* --------------------TFTP message start--------------------*/
	WEB_ERROR_TFTP_WRITTINNG = 0x3201,
	WEB_ERROR_TFTP_NOT_EXIST = 0x3202,
	/* --------------------TFTP message end--------------------*/
    /* --------------------check trunk message start--------------------*/
	WEB_ERROR_TRAFFIC_CONTROL_CHECK_TRUNK_FAIL = 0x3301,
	WEB_ERROR_LBD_CHECK_TRUNK_FAIL = 0x3302,
	WEB_ERROR_BANDWIDTH_CONTROL_CHECK_TRUNK_FAIL = 0x3303,
	WEB_ERROR_8021Q_CHECK_TRUNK_FAIL = 0x3304,
	WEB_ERROR_MIRROR_OVERLAP_CHECK_TRUNK_FAIL = 0x3305,
	WEB_ERROR_MIRROR_CHECK_TRUNK_FAIL = 0x3306,
	WEB_ERROR_TRAFFIC_SEG_CHECK_TRUNK_FAIL = 0x3307,
	WEB_ERROR_PORT_CHECK_TRUNK_FAIL = 0x3308,
	WEB_ERROR_SEC_PORT_OVERLAP_CHECK_TRUNK_FAIL = 0x3309,
	WEB_ERROR_VLAN_CHECK_TRUNK_FAIL = 0x330a,
	WEB_ERROR_STP_CHECK_TRUNK_FAIL = 0x330b,
	WEB_ERROR_ADDRESS_BINDING_CHECK_TRUNK_FAIL = 0x330c,
	WEB_ERROR_MULTICAST_FILTER_CHECK_TRUNK_FAIL = 0x330d,
	WEB_ERROR_DHCP_FILTER_CHECK_TRUNK_FAIL = 0x330e,
	WEB_ERROR_LACP_CHECK_VLAN_FAIL = 0x330f,
    WEB_ERROR_8021V_CHECK_TRUNK_FAIL = 0x3310,
    WEB_ERROR_MBA_CHECK_TRUNK_FAIL = 0x3311,
	/* --------------------check trunk message end--------------------*/
	/* --------------------check port security message start--------------------*/
	WEB_ERROR_CHECK_IPB_PORTLIST_FAIL = 0x3401,
	/* --------------------check port security message end--------------------*/
	/* --------------------DHCP server message start--------------------*/
    WEB_ERROR_DHCP_INIT_FAIL = 0x3501,
    WEB_ERROR_DHCP_ENTRY_ALREADY_EXIST = 0x3502,
    WEB_ERROR_DHCP_ENTRY_NOT_FOUND = 0x3503,
    WEB_ERROR_DHCP_TABLE_FULL = 0x3504,
    WEB_ERROR_DHCP_INVALID_INPUT = 0x3505,
    WEB_ERROR_DHCP_INVALID_POOL_NAME = 0x3506,
    WEB_ERROR_DHCP_NETWORK_OVERLAP = 0x3507,
    WEB_ERROR_DHCP_POOL_NOT_FOUND = 0x3508,
    WEB_ERROR_DHCP_INVALID_PING_PACKET = 0x3509,
    WEB_ERROR_DHCP_INVALID_PING_TIMEOUT = 0x350a,
    WEB_ERROR_DHCP_INVALID_EXCLUDE_ADDR = 0x350b,
    WEB_ERROR_DHCP_INVALID_NETWORK = 0x350c,
    WEB_ERROR_DHCP_INVALID_DOMAIN_NAME = 0x350d,
    WEB_ERROR_DHCP_INVALID_NETBIOS_NODE_TYPE = 0x350e,
    WEB_ERROR_DHCP_INVALID_NEXT_SERVER = 0x350f,
    WEB_ERROR_DHCP_INVALID_BOOT_FILE = 0x3510,
    WEB_ERROR_DHCP_INVALID_LEASE_TIME = 0x3511,
    WEB_ERROR_DHCP_INVALID_DEFAULT_ROUTER = 0x3512,
    WEB_ERROR_DHCP_INVALID_DNS_SERVER = 0x3513,
    WEB_ERROR_DHCP_INVALID_NETBIOS_NAME_SERVER = 0x3514,
    WEB_ERROR_DHCP_INVALID_MANUAL_BINDING_IP = 0x3515,
    WEB_ERROR_DHCP_INVALID_MANUAL_BINDING_HARDWARE_ADDR = 0x3516,
    WEB_ERROR_DHCP_DUPLICATE_MANUAL_BINDING_IP = 0x3517,
    WEB_ERROR_DHCP_DUPLICATE_MANUAL_BINDING_HARDWARE_ADDR = 0x3518,
    WEB_ERROR_DHCP_DHCP_RELAY_IS_ENABLED = 0x3519,
    WEB_ERROR_DHCP_DHCP_SERVER_IS_ENABLED = 0x351a,
    WEB_ERROR_DHCP_UNKNOW_ERR = 0x3520,
	/* --------------------DHCP server message end--------------------*/
    /* --------------------IPIF message start-------------------- */
    WEB_ERROR_IPIF_SEC_EXIST = 0x3601,
    /* --------------------IPIF message end-------------------- */
    /* --------------------IMP message start-------------------- */
    WEB_ERROR_IMP_NOT_ENOUGHT_PROFILES = 0x3701,
    WEB_ERROR_IMP_NOT_ENOUGHT_ENTRIES = 0X3702
    /* --------------------IMP message end-------------------- */

}WEB_ERROR_VALUE;               //Added by Vic Yu 2002-09/26 ,Error Message defined

typedef struct _WEB_ERROR_TABLE {
	WEB_ERROR_VALUE	IndexCode;
	char 				ErrorMeg[300];
} WEB_ERROR_TABLE;

char *ErrorMegMapping( WEB_ERROR_VALUE );

char *html_SetBuffer(char *data);
char *html_AppendBufferFormat(char *, ...);
// ------------------- Define the WEB Global Attribute ------
// This table use to mapping the index-Name association
//------------------------------------------------------------
typedef struct _WEB_MAPPING_TABLE {
	int index;
	char aliasName[64];
} WEB_MAPPING_TABLE;


// Parse string parameter in html url ,use "%" be key word ,string parameter must be defined after integer
// parameter ,and still be separated by "," .
// Added by Vic Yu 2003-02/21

#define WEB_URLSTRPARAM_COUNTER		5
#define WEB_URLSTRPARAM_LENGTH		32

#endif


Unsigned8 html_RpWebID_GetAccessRight(void *theTaskDataPtr, Signed16Ptr theIndexValuesPtr);//2004/6/8 02:31¤U¤È iris chu 04443 modify
void sWeb_DisplayString_Reword(char* pString, char* pResult);

