#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ -g --dwarf2 -O1
CARM_SRCS	= 		  .\src\ascii_font_16x22x95_Commax_2bit.c \
		  .\src\ascii_font_8x16x95_2bit.c \
		  .\src\ascii_font_20x20x95_double_field_2bit_DR900.c \
		  .\src\ascii_font_20x20x95_double_field_2bit.c \
		  .\src\ascii_font_20x20x95_2bit.c \
		  .\src\ascii_font_12x12x95_2bit.c \
		  .\src\ascii_font_32x40x95_2bit.c \
		  .\src\ascii_font_32x40x95_1bit.c \
		  .\src\ascii_font_20x20x95_DR900.c \
		  .\src\ascii_font_12x12x95.c \
		  .\src\ascii_font_20x36x95.c \
		  .\src\ascii_font_20x20x95_25.c \
		  .\src\ascii_font_32x48x95.c \
		  .\src\ascii_font_32x40x95.c \
		  .\src\ascii_font_20x20x95_2.c \
		  .\src\ascii_font_20x20x95_1.c \
		  .\src\ascii_font_20x20x95_0.c \
		  .\src\ascii_font_20x20x95.c .\src\isu.c \
		  .\src\ascii_font_64x40x95_2bit_with_antenna.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  DebugRel\ascii_font_16x22x95_Commax_2bit.o \
		  DebugRel\ascii_font_8x16x95_2bit.o \
		  DebugRel\ascii_font_20x20x95_double_field_2bit_DR900.o \
		  DebugRel\ascii_font_20x20x95_double_field_2bit.o \
		  DebugRel\ascii_font_20x20x95_2bit.o \
		  DebugRel\ascii_font_12x12x95_2bit.o \
		  DebugRel\ascii_font_32x40x95_2bit.o \
		  DebugRel\ascii_font_32x40x95_1bit.o \
		  DebugRel\ascii_font_20x20x95_DR900.o \
		  DebugRel\ascii_font_12x12x95.o \
		  DebugRel\ascii_font_20x36x95.o \
		  DebugRel\ascii_font_20x20x95_25.o \
		  DebugRel\ascii_font_32x48x95.o \
		  DebugRel\ascii_font_32x40x95.o \
		  DebugRel\ascii_font_20x20x95_2.o \
		  DebugRel\ascii_font_20x20x95_1.o \
		  DebugRel\ascii_font_20x20x95_0.o \
		  DebugRel\ascii_font_20x20x95.o DebugRel\isu.o \
		  DebugRel\ascii_font_64x40x95_2bit_with_antenna.o 

CARM_CPP	=  -g --dwarf2 --cpp -O1
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2 -O1
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp -O1
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= isu_DebugRel.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\isu.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 13
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\application.h \
	 ..\inc\\project.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h 
INC__ISU_H=inc\\isu.h inc\\isureg.h inc\\ascii_font_20x20x95.h \
	 inc\\ascii_font_32x40x95.h inc\\ascii_font_32x48x95.h \
	 inc\\ascii_font_20x36x95.h inc\\ascii_font_32x40x95_1bit.h \
	 inc\\ascii_font_32x40x95_2bit.h inc\\ascii_font_20x20x95_2bit.h \
	 inc\\ascii_font_20x20x95_2bit_with_light.h \
	 inc\\ascii_font_8x16x95_2bit.h \
	 inc\\ascii_font_64x40x95_2bit_with_antenna.h \
	 inc\\ascii_font_12x12x95.h inc\\ascii_font_12x12x95_2bit.h 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__TIMERAPI_H=..\inc\\timerapi.h $(___INC__GENERAL_H) 
___INC__FSAPI_H=..\inc\\fsapi.h 
___INC__ASFAPI_H=..\inc\\asfapi.h $(___INC__FSAPI_H) 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\uikey.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GLOBALVARIABLE_H=..\inc\\globalvariable.h $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\task.h ..\inc\\mp4api.h \
	 $(___INC__ASFAPI_H) ..\inc\\aviapi.h ..\inc\\mpeg4api.h \
	 ..\inc\\isuapi.h ..\inc\\iduapi.h ..\inc\\gpioapi.h \
	 $(___INC__SIUAPI_H) ..\inc\\sysapi.h $(___INC__OSAPI_H) \
	 ..\inc\\rtcapi.h ..\inc\\i2capi.h $(___INC__UIAPI_H) \
	 ..\inc\\memorypool.h ..\inc\\iisapi.h 
# DEPEND: end include files

DebugRel\ascii_font_16x22x95_Commax_2bit.o: \
	 .\src\ascii_font_16x22x95_Commax_2bit.c $(___INC__GENERAL_H) \
	 ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_16x22x95_Commax_2bit.c $(CARM) -o \
	 DebugRel\ascii_font_16x22x95_Commax_2bit.o
DebugRel\ascii_font_8x16x95_2bit.o: .\src\ascii_font_8x16x95_2bit.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_8x16x95_2bit.c $(CARM) -o \
	 DebugRel\ascii_font_8x16x95_2bit.o
DebugRel\ascii_font_20x20x95_double_field_2bit_DR900.o: \
	 .\src\ascii_font_20x20x95_double_field_2bit_DR900.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x20x95_double_field_2bit_DR900.c $(CARM) -o \
	 DebugRel\ascii_font_20x20x95_double_field_2bit_DR900.o
DebugRel\ascii_font_20x20x95_double_field_2bit.o: \
	 .\src\ascii_font_20x20x95_double_field_2bit.c $(___INC__GENERAL_H) \
	 ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x20x95_double_field_2bit.c $(CARM) -o \
	 DebugRel\ascii_font_20x20x95_double_field_2bit.o
DebugRel\ascii_font_20x20x95_2bit.o: .\src\ascii_font_20x20x95_2bit.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x20x95_2bit.c $(CARM) -o \
	 DebugRel\ascii_font_20x20x95_2bit.o
DebugRel\ascii_font_12x12x95_2bit.o: .\src\ascii_font_12x12x95_2bit.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_12x12x95_2bit.c $(CARM) -o \
	 DebugRel\ascii_font_12x12x95_2bit.o
DebugRel\ascii_font_32x40x95_2bit.o: .\src\ascii_font_32x40x95_2bit.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_32x40x95_2bit.c $(CARM) -o \
	 DebugRel\ascii_font_32x40x95_2bit.o
DebugRel\ascii_font_32x40x95_1bit.o: .\src\ascii_font_32x40x95_1bit.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_32x40x95_1bit.c $(CARM) -o \
	 DebugRel\ascii_font_32x40x95_1bit.o
DebugRel\ascii_font_20x20x95_DR900.o: .\src\ascii_font_20x20x95_DR900.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x20x95_DR900.c $(CARM) -o \
	 DebugRel\ascii_font_20x20x95_DR900.o
DebugRel\ascii_font_12x12x95.o: .\src\ascii_font_12x12x95.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_12x12x95.c $(CARM) -o DebugRel\ascii_font_12x12x95.o
DebugRel\ascii_font_20x36x95.o: .\src\ascii_font_20x36x95.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x36x95.c $(CARM) -o DebugRel\ascii_font_20x36x95.o
DebugRel\ascii_font_20x20x95_25.o: .\src\ascii_font_20x20x95_25.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x20x95_25.c $(CARM) -o \
	 DebugRel\ascii_font_20x20x95_25.o
DebugRel\ascii_font_32x48x95.o: .\src\ascii_font_32x48x95.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_32x48x95.c $(CARM) -o DebugRel\ascii_font_32x48x95.o
DebugRel\ascii_font_32x40x95.o: .\src\ascii_font_32x40x95.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_32x40x95.c $(CARM) -o DebugRel\ascii_font_32x40x95.o
DebugRel\ascii_font_20x20x95_2.o: .\src\ascii_font_20x20x95_2.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x20x95_2.c $(CARM) -o \
	 DebugRel\ascii_font_20x20x95_2.o
DebugRel\ascii_font_20x20x95_1.o: .\src\ascii_font_20x20x95_1.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x20x95_1.c $(CARM) -o \
	 DebugRel\ascii_font_20x20x95_1.o
DebugRel\ascii_font_20x20x95_0.o: .\src\ascii_font_20x20x95_0.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x20x95_0.c $(CARM) -o \
	 DebugRel\ascii_font_20x20x95_0.o
DebugRel\ascii_font_20x20x95.o: .\src\ascii_font_20x20x95.c \
	 $(___INC__GENERAL_H) ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_20x20x95.c $(CARM) -o DebugRel\ascii_font_20x20x95.o
DebugRel\isu.o: .\src\isu.c $(INC__ISU_H) ..\inc\\jpegapi.h \
	 $(___INC__TIMERAPI_H)  ..\inc\\osapi.h ..\inc\\memorypool.h \
	 ..\inc\\iduapi.h ..\inc\\mpeg4api.h ..\inc\\isuapi.h \
	 ..\inc\\board.h ..\inc\\siuapi.h ..\inc\\iisapi.h ..\inc\\asfapi.h \
	 ..\inc\\uiapi.h ..\inc\\task.h ..\inc\\rtcapi.h \
	 ..\inc\\globalvariable.h ..\inc\\mp4api.h ..\inc\\aviapi.h \
	 ..\inc\\gpioapi.h ..\inc\\sysapi.h ..\inc\\i2capi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\isu.c \
	 $(CARM) -o DebugRel\isu.o
DebugRel\ascii_font_64x40x95_2bit_with_antenna.o: \
	 .\src\ascii_font_64x40x95_2bit_with_antenna.c $(___INC__GENERAL_H) \
	 ..\inc\\isuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ascii_font_64x40x95_2bit_with_antenna.c $(CARM) -o \
	 DebugRel\ascii_font_64x40x95_2bit_with_antenna.o
