#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I.\app\cli\ -I.\host\hal\SSV6030\ -I.\host\hal\ -I.\ \
	 -I.\include\lwip\ -I.\app\netapp\udhcp\ -I.\app\netapp\ \
	 -I.\netstack_wrapper\icomm_lwIP\ -I..\inc\ \
	 -I.\app\netapp\httpserver_raw\ -I.\include\priv\ -I.\include\ \
	 -I.\os_wrapper\MicroC\ -I.\priv\hw\ -I.\include\priv\regs\ \
	 -I.\platform\mars\ -I.\ap\ -I.\ap\common\ -I.\ap\crypto\ \
	 -I.\app\netmgr\ -I.\core\ -I.\drv\ -I.\drv\spi\ -I.\firmware\ \
	 -I..\inc\os\ -I.\tcpip\lwip-1.4.0\src\include\lwip\ \
	 -I.\tcpip\lwip-1.4.0\src\include\ -I.\tcpip\lwip-1.4.0\src\netif\ \
	 -I.\tcpip\lwip-1.4.0\ports\icomm\include\ -I.\host\ \
	 -I.\tcpip\lwip-1.4.0\src\include\ipv4\ -I.\netapp\udhcp\ \
	 -I.\netapp\ -I.\app\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= --gnu -I.\app\cli\ -I.\host\hal\SSV6030\ -I.\host\hal\ -I.\ -I.\include\lwip\ -I.\app\netapp\udhcp\ -I.\app\netapp\ -I.\netstack_wrapper\icomm_lwIP\ -I..\inc\ -I.\app\netapp\httpserver_raw\ -I.\include\priv\ -I.\include\ -I.\os_wrapper\MicroC\ -I.\priv\hw\ -I.\include\priv\regs\ -I.\include\priv\regs\ -I.\platform\mars\ -I.\ap\ -I.\ap\common\ -I.\ap\crypto\ -I.\app\netmgr\ -I.\core\ -I.\drv\ -I.\drv\spi\ -I.\firmware\ -I..\inc\os\ -I.\tcpip\lwip-1.4.0\src\include\lwip\ -I.\tcpip\lwip-1.4.0\src\include\ -I.\tcpip\lwip-1.4.0\src\netif\ -I.\tcpip\lwip-1.4.0\ports\icomm\include\ -I.\host\ -I.\tcpip\lwip-1.4.0\src\include\ipv4\ -I.\netapp\udhcp\ -I.\netapp\ -I.\app\ -g --dwarf2 --pointer_alignment=1 -O1
CARM_SRCS	= 		  .\custom_cfg.c .\tutk_P2P\icomm_P2P_server.c \
		  .\app\netapp\udhcp\time.c \
		  .\app\netapp\udhcp\static_leases.c \
		  .\app\netapp\udhcp\socket.c .\app\netapp\udhcp\read.c \
		  .\app\netapp\udhcp\packet.c \
		  .\app\netapp\udhcp\leases.c \
		  .\app\netapp\udhcp\files.c .\app\netapp\udhcp\dhcpd.c \
		  .\app\netapp\udhcp\common.c \
		  .\app\netapp\udhcp\arpping.c \
		  .\netstack_wrapper\icomm_lwIP\netstack.c \
		  .\ssv_frame.c .\init.c .\macaddr.c \
		  .\app\cli\cli.c .\app\cli\cmds\cli_cmd.c \
		  .\app\cli\cmds\cli_cmd_net.c \
		  .\app\cli\cmds\cli_cmd_rf_test.c \
		  .\app\cli\cmds\cli_cmd_sim.c \
		  .\app\cli\cmds\cli_cmd_soc.c \
		  .\app\cli\cmds\cli_cmd_sys.c \
		  .\app\cli\cmds\cli_cmd_wifi.c .\app\netapp\net_app.c \
		  .\app\netapp\httpserver_raw\fs.c \
		  .\app\netapp\httpserver_raw\httpd.c \
		  .\app\netapp\httpserver_raw\httpd_cgi_ssi.c \
		  .\app\netapp\ping\ping.c \
		  .\app\netmgr\smartconfig\airkiss\AirKiss.c \
		  .\app\netmgr\smartconfig\airkiss\AirKissInFw.c \
		  .\app\netmgr\smartconfig\icomm\SmartLink.c \
		  .\os_wrapper\microc\rtos.c .\platform\mars\porting.c \
		  .\platform\mars\spi.c \
		  .\tcpip\lwip-1.4.0\ports\icomm\sys_arch.c \
		  .\tcpip\lwip-1.4.0\src\api\api_lib.c \
		  .\tcpip\lwip-1.4.0\src\api\api_msg.c \
		  .\tcpip\lwip-1.4.0\src\api\err.c \
		  .\tcpip\lwip-1.4.0\src\api\netbuf.c \
		  .\tcpip\lwip-1.4.0\src\api\netdb.c \
		  .\tcpip\lwip-1.4.0\src\api\netifapi.c \
		  .\tcpip\lwip-1.4.0\src\api\sockets.c \
		  .\tcpip\lwip-1.4.0\src\api\tcpip.c \
		  .\tcpip\lwip-1.4.0\src\core\ipv4\autoip.c \
		  .\tcpip\lwip-1.4.0\src\core\ipv4\icmp.c \
		  .\tcpip\lwip-1.4.0\src\core\ipv4\igmp.c \
		  .\tcpip\lwip-1.4.0\src\core\ipv4\ip_frag.c \
		  .\tcpip\lwip-1.4.0\src\core\ipv4\ip4.c \
		  .\tcpip\lwip-1.4.0\src\core\ipv4\ip4_addr.c \
		  .\tcpip\lwip-1.4.0\src\core\snmp\asn1_dec.c \
		  .\tcpip\lwip-1.4.0\src\core\snmp\asn1_enc.c \
		  .\tcpip\lwip-1.4.0\src\core\snmp\mib_structs.c \
		  .\tcpip\lwip-1.4.0\src\core\snmp\mib2.c \
		  .\tcpip\lwip-1.4.0\src\core\snmp\msg_in.c \
		  .\tcpip\lwip-1.4.0\src\core\snmp\msg_out.c \
		  .\tcpip\lwip-1.4.0\src\core\def.c \
		  .\tcpip\lwip-1.4.0\src\core\dhcp.c \
		  .\tcpip\lwip-1.4.0\src\core\dns.c \
		  .\tcpip\lwip-1.4.0\src\core\inet_chksum.c \
		  .\tcpip\lwip-1.4.0\src\core\lwip_init.c \
		  .\tcpip\lwip-1.4.0\src\core\lwip_pbuf.c \
		  .\tcpip\lwip-1.4.0\src\core\lwip_timers.c \
		  .\tcpip\lwip-1.4.0\src\core\mem.c \
		  .\tcpip\lwip-1.4.0\src\core\memp.c \
		  .\tcpip\lwip-1.4.0\src\core\netif.c \
		  .\tcpip\lwip-1.4.0\src\core\raw.c \
		  .\tcpip\lwip-1.4.0\src\core\stats.c \
		  .\tcpip\lwip-1.4.0\src\core\sys.c \
		  .\tcpip\lwip-1.4.0\src\core\tcp.c \
		  .\tcpip\lwip-1.4.0\src\core\tcp_in.c \
		  .\tcpip\lwip-1.4.0\src\core\tcp_out.c \
		  .\tcpip\lwip-1.4.0\src\core\udp.c \
		  .\tcpip\lwip-1.4.0\src\netif\etharp.c \
		  .\tcpip\lwip-1.4.0\src\netif\ethernetif.c \
		  .\tcpip\lwip-1.4.0\src\netif\slipif.c \
		  .\tcpip\lwip-1.4.0\src\netif\ppp\md5.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  DebugRel\custom_cfg.o DebugRel\icomm_P2P_server.o \
		  DebugRel\time.o DebugRel\static_leases.o \
		  DebugRel\socket.o DebugRel\read.o DebugRel\packet.o \
		  DebugRel\leases.o DebugRel\files.o DebugRel\dhcpd.o \
		  DebugRel\common.o DebugRel\arpping.o \
		  DebugRel\netstack.o DebugRel\ssv_frame.o \
		  DebugRel\init.o DebugRel\macaddr.o DebugRel\cli.o \
		  DebugRel\cli_cmd.o DebugRel\cli_cmd_net.o \
		  DebugRel\cli_cmd_rf_test.o DebugRel\cli_cmd_sim.o \
		  DebugRel\cli_cmd_soc.o DebugRel\cli_cmd_sys.o \
		  DebugRel\cli_cmd_wifi.o DebugRel\net_app.o \
		  DebugRel\fs.o DebugRel\httpd.o \
		  DebugRel\httpd_cgi_ssi.o DebugRel\ping.o \
		  DebugRel\AirKiss.o DebugRel\AirKissInFw.o \
		  DebugRel\SmartLink.o DebugRel\rtos.o \
		  DebugRel\porting.o DebugRel\spi.o \
		  DebugRel\sys_arch.o DebugRel\api_lib.o \
		  DebugRel\api_msg.o DebugRel\err.o DebugRel\netbuf.o \
		  DebugRel\netdb.o DebugRel\netifapi.o \
		  DebugRel\sockets.o DebugRel\tcpip.o \
		  DebugRel\autoip.o DebugRel\icmp.o DebugRel\igmp.o \
		  DebugRel\ip_frag.o DebugRel\ip4.o \
		  DebugRel\ip4_addr.o DebugRel\asn1_dec.o \
		  DebugRel\asn1_enc.o DebugRel\mib_structs.o \
		  DebugRel\mib2.o DebugRel\msg_in.o \
		  DebugRel\msg_out.o DebugRel\def.o DebugRel\dhcp.o \
		  DebugRel\dns.o DebugRel\inet_chksum.o \
		  DebugRel\lwip_init.o DebugRel\lwip_pbuf.o \
		  DebugRel\lwip_timers.o DebugRel\mem.o \
		  DebugRel\memp.o DebugRel\netif.o DebugRel\raw.o \
		  DebugRel\stats.o DebugRel\sys.o DebugRel\tcp.o \
		  DebugRel\tcp_in.o DebugRel\tcp_out.o DebugRel\udp.o \
		  DebugRel\etharp.o DebugRel\ethernetif.o \
		  DebugRel\slipif.o DebugRel\md5.o 

CARM_CPP	=  -g --dwarf2 --cpp -O1
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2 -O1
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp -O1
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= host_DebugRel.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Release\..\..\lib\host.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 28
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\application.h \
	 ..\inc\\project.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\ip_addr.h \
	 tcpip\lwip-1.4.0\src\include\\ipv4\lwip\ip4_addr.h 
___INC__LWIPAPI_H=..\inc\\lwipapi.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\uikey.h ..\inc\\rfiuapi.h 
___INC__SYSAPI_H=..\inc\\sysapi.h 
___INC__FSAPI_H=..\inc\\fsapi.h 
___INC__ASFAPI_H=..\inc\\asfapi.h $(___INC__FSAPI_H) 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GLOBALVARIABLE_H=..\inc\\globalvariable.h $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\task.h ..\inc\\mp4api.h \
	 $(___INC__ASFAPI_H) ..\inc\\aviapi.h ..\inc\\mpeg4api.h \
	 ..\inc\\isuapi.h ..\inc\\iduapi.h ..\inc\\gpioapi.h \
	 $(___INC__SIUAPI_H) $(___INC__SYSAPI_H) $(___INC__OSAPI_H) \
	 ..\inc\\rtcapi.h ..\inc\\i2capi.h $(___INC__UIAPI_H) \
	 ..\inc\\memorypool.h ..\inc\\iisapi.h 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__TIMERAPI_H=..\inc\\timerapi.h $(___INC__GENERAL_H) 
___UI_INC_UI_H=..\ui\inc\ui.h $(___INC__FSAPI_H) ..\inc\\rtcapi.h \
	 $(___INC__UIAPI_H) 
___UI_INC_UI_PROJECT_H=..\ui\inc\ui_project.h ..\inc\\motiondetect_api.h \
	 ..\inc\\rtcapi.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SOCKETS_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\sockets.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\inet6.h 
APP_NETAPP__UDHCP_UDHCP_COMMON_H=app\netapp\\udhcp\udhcp_common.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SOCKETS_H) \
	 app\\netmgr\net_mgr.h include\\os_wrapper.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DEBUG_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\debug.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\arch.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\opt.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DEBUG_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INIT_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\init.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_API_MSG_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\api_msg.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\igmp.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\ip.h \
	 tcpip\lwip-1.4.0\src\include\\ipv4\lwip\ip4.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_UDP_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\udp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DHCP_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\dhcp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_UDP_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_AUTOIP_H= \
	tcpip\lwip-1.4.0\src\include\ipv4\\lwip\autoip.h \
	 tcpip\lwip-1.4.0\src\include\\netif\etharp.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIFAPI_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\netifapi.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DHCP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_AUTOIP_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_API_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\api.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netbuf.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\sys.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\sys_arch.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\netif.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCPIP_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\tcpip.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_API_MSG_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIFAPI_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_API_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\timers.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__NETIF_ETHERNETIF_H= \
	tcpip\lwip-1.4.0\src\include\\netif\ethernetif.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_STD_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\memp_std.h \
	 tcpip\lwip-1.4.0\src\include\lwip\\lwippools.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\memp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_STD_H) \
	 tcpip\lwip-1.4.0\src\include\lwip\\mem.h 
APP_NETAPP_HTTPSERVER_RAW_HTTP_FS_H=app\netapp\httpserver_raw\http_fs.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) 
APP_NETAPP_HTTPSERVER_RAW_FSDATA_H=app\netapp\httpserver_raw\fsdata.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 app\netapp\httpserver_raw\\http_fs.h 
APP_NETAPP_HTTPSERVER_RAW__FSDATA_H=app\netapp\httpserver_raw\\fsdata.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) 
APP_NETAPP_HTTPSERVER_RAW_FSDATA_C=app\netapp\httpserver_raw\fsdata.c \
	 app\netapp\httpserver_raw\\http_fs.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(APP_NETAPP_HTTPSERVER_RAW__FSDATA_H) 
APP_NETAPP_HTTPSERVER_RAW_HTTPD_H=app\netapp\httpserver_raw\httpd.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\usr_data.h 
APP_NETAPP_HTTPSERVER_RAW__HTTPD_H=app\netapp\httpserver_raw\\httpd.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\usr_data.h 
APP_NETAPP_HTTPSERVER_RAW_HTTPD_STRUCTS_H= \
	app\netapp\httpserver_raw\httpd_structs.h \
	 $(APP_NETAPP_HTTPSERVER_RAW__HTTPD_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\stats.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_RAW_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\raw.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INET_CHKSUM_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\inet_chksum.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) 
PLATFORM_MARS__PORTING_H=platform\mars\\porting.h ..\inc\\task.h 
___INC__UARTAPI_H=..\inc\\uartapi.h ..\inc\\task.h 
DRV__SSV_DRV_CONFIG_H=drv\\ssv_drv_config.h $(PLATFORM_MARS__PORTING_H) 
DRV__SSV_DRV_H=drv\\ssv_drv.h $(DRV__SSV_DRV_CONFIG_H) 
TCPIP_LWIP-1_4_0_PORTS_ICOMM_INCLUDE__ARCH_CC_H= \
	tcpip\lwip-1.4.0\ports\icomm\include\\arch\cc.h \
	 $(PLATFORM_MARS__PORTING_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DNS_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\dns.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__IPV6_LWIP_MLD6_H= \
	tcpip\lwip-1.4.0\src\include\\ipv6\lwip\mld6.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETDB_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\netdb.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\inet.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SOCKETS_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__NETIF_PPP_OE_H= \
	tcpip\lwip-1.4.0\src\include\\netif\ppp_oe.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\netif\etharp.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_IP_FRAG_H= \
	tcpip\lwip-1.4.0\src\include\ipv4\\lwip\ip_frag.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_ICMP_H= \
	tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCP_IMPL_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_ICMP_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_ASN1_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\snmp_asn1.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_STRUCTS_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\snmp_structs.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_MSG_H= \
	tcpip\lwip-1.4.0\src\include\\lwip\snmp_msg.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_STRUCTS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__IPV6_LWIP_ND6_H= \
	tcpip\lwip-1.4.0\src\include\\ipv6\lwip\nd6.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__IPV6_LWIP_IP6_FRAG_H= \
	tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_frag.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__IPV6_LWIP_DHCP6_H= \
	tcpip\lwip-1.4.0\src\include\\ipv6\lwip\dhcp6.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__IPV6_LWIP_ICMP6_H= \
	tcpip\lwip-1.4.0\src\include\\ipv6\lwip\icmp6.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h 
TCPIP_LWIP-1_4_0_SRC_INCLUDE__NETIF_SLIPIF_H= \
	tcpip\lwip-1.4.0\src\include\\netif\slipif.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) 
TCPIP_LWIP-1_4_0_SRC_NETIF_PPP_PPP_IMPL_H= \
	tcpip\lwip-1.4.0\src\netif\ppp\ppp_impl.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\sio.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\timers.h 
# DEPEND: end include files

DebugRel\custom_cfg.o: .\custom_cfg.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\custom_cfg.c \
	 $(CARM) -o DebugRel\custom_cfg.o
DebugRel\icomm_P2P_server.o: .\tutk_P2P\icomm_P2P_server.c \
	 ..\inc\\tutkiotcapi.h ..\inc\\tutkavapi.h ..\inc\\gpiapi.h \
	 $(___INC__LWIPAPI_H) $(___INC__GLOBALVARIABLE_H) \
	 $(___INC__DCFAPI_H)  ..\inc\\p2pserver_api.h   \
	 ..\inc\\encrptyapi.h ..\inc\\timerapi.h ..\ui\inc\ui.h \
	 ..\ui\inc\ui_project.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tutk_P2P\icomm_P2P_server.c $(CARM) -o DebugRel\icomm_P2P_server.o
DebugRel\time.o: .\app\netapp\udhcp\time.c $(APP_NETAPP__UDHCP_UDHCP_COMMON_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\time.c $(CARM) -o DebugRel\time.o
DebugRel\static_leases.o: .\app\netapp\udhcp\static_leases.c \
	 $(APP_NETAPP__UDHCP_UDHCP_COMMON_H) app\netapp\\udhcp\dhcpd.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\static_leases.c $(CARM) -o \
	 DebugRel\static_leases.o
DebugRel\socket.o: .\app\netapp\udhcp\socket.c \
	 $(APP_NETAPP__UDHCP_UDHCP_COMMON_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\socket.c $(CARM) -o DebugRel\socket.o
DebugRel\read.o: .\app\netapp\udhcp\read.c $(APP_NETAPP__UDHCP_UDHCP_COMMON_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\read.c $(CARM) -o DebugRel\read.o
DebugRel\packet.o: .\app\netapp\udhcp\packet.c \
	 $(APP_NETAPP__UDHCP_UDHCP_COMMON_H) app\netapp\\udhcp\dhcpd.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\packet.c $(CARM) -o DebugRel\packet.o
DebugRel\leases.o: .\app\netapp\udhcp\leases.c \
	 $(APP_NETAPP__UDHCP_UDHCP_COMMON_H) app\netapp\\udhcp\dhcpd.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\leases.c $(CARM) -o DebugRel\leases.o
DebugRel\files.o: .\app\netapp\udhcp\files.c \
	 $(APP_NETAPP__UDHCP_UDHCP_COMMON_H) app\netapp\\udhcp\dhcpd.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\files.c $(CARM) -o DebugRel\files.o
DebugRel\dhcpd.o: .\app\netapp\udhcp\dhcpd.c \
	 $(APP_NETAPP__UDHCP_UDHCP_COMMON_H) app\netapp\\udhcp\dhcpd.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\sys_arch.h \
	 app\netapp\\udhcp\dhcpc.h include\\rtos.h include\priv\\msgevt.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\dhcpd.c $(CARM) -o DebugRel\dhcpd.o
DebugRel\common.o: .\app\netapp\udhcp\common.c \
	 $(APP_NETAPP__UDHCP_UDHCP_COMMON_H) include\priv\\log.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\common.c $(CARM) -o DebugRel\common.o
DebugRel\arpping.o: .\app\netapp\udhcp\arpping.c \
	 $(APP_NETAPP__UDHCP_UDHCP_COMMON_H) app\netapp\\udhcp\dhcpd.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\udhcp\arpping.c $(CARM) -o DebugRel\arpping.o
DebugRel\netstack.o: .\netstack_wrapper\icomm_lwIP\netstack.c \
	 $(APP_NETAPP__UDHCP_UDHCP_COMMON_H) app\netapp\\udhcp\dhcpd.h \
	 app\netapp\\udhcp\dhcpc.h include\\rtos.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INIT_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__NETIF_ETHERNETIF_H) \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\sys_arch.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcpip.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\api_msg.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\sys.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\igmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\api.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netifapi.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\dhcp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\udp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip.h \
	 tcpip\lwip-1.4.0\src\include\\ipv4\lwip\ip4.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\autoip.h \
	 tcpip\lwip-1.4.0\src\include\\netif\etharp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\timers.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\netstack_wrapper\icomm_lwIP\netstack.c $(CARM) -o \
	 DebugRel\netstack.o
DebugRel\ssv_frame.o: .\ssv_frame.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h include\priv\\ssv_lib.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\ssv_frame.c \
	 $(CARM) -o DebugRel\ssv_frame.o
DebugRel\init.o: .\init.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\init.c $(CARM) \
	 -o DebugRel\init.o
DebugRel\macaddr.o: .\macaddr.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\macaddr.c \
	 $(CARM) -o DebugRel\macaddr.o
DebugRel\cli.o: .\app\cli\cli.c app\cli\cli.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\app\cli\cli.c \
	 $(CARM) -o DebugRel\cli.o
DebugRel\cli_cmd.o: .\app\cli\cmds\cli_cmd.c app\cli\cmds\cli_cmd.h \
	 app\cli\cmds\cli_cmd_soc.h app\cli\cmds\cli_cmd_net.h \
	 app\cli\cmds\cli_cmd_wifi.h app\cli\cmds\cli_cmd_sim.h \
	 app\cli\cmds\cli_cmd_sys.h app\cli\cmds\cli_cmd_rf_test.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\cli\cmds\cli_cmd.c $(CARM) -o DebugRel\cli_cmd.o
DebugRel\cli_cmd_net.o: .\app\cli\cmds\cli_cmd_net.c \
	 app\cli\cmds\cli_cmd_net.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\cli\cmds\cli_cmd_net.c $(CARM) -o DebugRel\cli_cmd_net.o
DebugRel\cli_cmd_rf_test.o: .\app\cli\cmds\cli_cmd_rf_test.c \
	 app\cli\cmds\cli_cmd_rf_test.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\cli\cmds\cli_cmd_rf_test.c $(CARM) -o \
	 DebugRel\cli_cmd_rf_test.o
DebugRel\cli_cmd_sim.o: .\app\cli\cmds\cli_cmd_sim.c \
	 app\cli\cmds\cli_cmd_sim.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\cli\cmds\cli_cmd_sim.c $(CARM) -o DebugRel\cli_cmd_sim.o
DebugRel\cli_cmd_soc.o: .\app\cli\cmds\cli_cmd_soc.c app\cli\cmds\cli_cmd.h \
	 app\cli\cmds\cli_cmd_soc.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\cli\cmds\cli_cmd_soc.c $(CARM) -o DebugRel\cli_cmd_soc.o
DebugRel\cli_cmd_sys.o: .\app\cli\cmds\cli_cmd_sys.c \
	 app\cli\cmds\cli_cmd_sys.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\cli\cmds\cli_cmd_sys.c $(CARM) -o DebugRel\cli_cmd_sys.o
DebugRel\cli_cmd_wifi.o: .\app\cli\cmds\cli_cmd_wifi.c \
	 app\cli\cmds\cli_cmd_net.h app\cli\cmds\cli_cmd_wifi.h \
	 include\priv\\ssv_dev.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\cli\cmds\cli_cmd_wifi.c $(CARM) -o DebugRel\cli_cmd_wifi.o
DebugRel\net_app.o: .\app\netapp\net_app.c app\netapp\net_app.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\net_app.c $(CARM) -o DebugRel\net_app.o
DebugRel\fs.o: .\app\netapp\httpserver_raw\fs.c \
	 $(APP_NETAPP_HTTPSERVER_RAW_HTTP_FS_H)   \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 app\netapp\httpserver_raw\fsdata.h \
	 app\netapp\httpserver_raw\\http_fs.h \
	 app\netapp\httpserver_raw\fsdata.c \
	 app\netapp\httpserver_raw\\fsdata.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\httpserver_raw\fs.c $(CARM) -o DebugRel\fs.o
DebugRel\httpd.o: .\app\netapp\httpserver_raw\httpd.c \
	 $(APP_NETAPP_HTTPSERVER_RAW_HTTP_FS_H)   \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 app\netapp\httpserver_raw\httpd.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\usr_data.h \
	 app\netapp\httpserver_raw\httpd_structs.h \
	 app\netapp\httpserver_raw\\httpd.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\httpserver_raw\httpd.c $(CARM) -o DebugRel\httpd.o
DebugRel\httpd_cgi_ssi.o: .\app\netapp\httpserver_raw\httpd_cgi_ssi.c \
	 $(APP_NETAPP_HTTPSERVER_RAW_HTTP_FS_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 app\netapp\httpserver_raw\httpd.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\usr_data.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\httpserver_raw\httpd_cgi_ssi.c $(CARM) -o \
	 DebugRel\httpd_cgi_ssi.o
DebugRel\ping.o: .\app\netapp\ping\ping.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SOCKETS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\timers.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h  app\netapp\ping\ping.h   \
	 tcpip\lwip-1.4.0\src\include\\lwip\opt.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netif.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\raw.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\inet_chksum.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netapp\ping\ping.c $(CARM) -o DebugRel\ping.o
DebugRel\AirKiss.o: .\app\netmgr\smartconfig\airkiss\AirKiss.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netmgr\smartconfig\airkiss\AirKiss.c $(CARM) -o \
	 DebugRel\AirKiss.o
DebugRel\AirKissInFw.o: .\app\netmgr\smartconfig\airkiss\AirKissInFw.c
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netmgr\smartconfig\airkiss\AirKissInFw.c $(CARM) -o \
	 DebugRel\AirKissInFw.o
DebugRel\SmartLink.o: .\app\netmgr\smartconfig\icomm\SmartLink.c \
	 include\\rtos.h $(PLATFORM_MARS__PORTING_H) \
	 app\netmgr\smartconfig\icomm\core\smartconf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\app\netmgr\smartconfig\icomm\SmartLink.c $(CARM) -o \
	 DebugRel\SmartLink.o
DebugRel\rtos.o: .\os_wrapper\microc\rtos.c include\\rtos.h \
	 ..\inc\os\\os_cfg.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\os_wrapper\microc\rtos.c $(CARM) -o DebugRel\rtos.o
DebugRel\porting.o: .\platform\mars\porting.c $(___INC__UARTAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\platform\mars\porting.c $(CARM) -o DebugRel\porting.o
DebugRel\spi.o: .\platform\mars\spi.c ..\inc\\board.h ..\inc\\gpioapi.h \
	 include\priv\\msgevt.h $(DRV__SSV_DRV_H) drv\spi\\spi_def.h \
	 drv\spi\\spi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\platform\mars\spi.c $(CARM) -o DebugRel\spi.o
DebugRel\sys_arch.o: .\tcpip\lwip-1.4.0\ports\icomm\sys_arch.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 $(TCPIP_LWIP-1_4_0_PORTS_ICOMM_INCLUDE__ARCH_CC_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\ports\icomm\sys_arch.c $(CARM) -o \
	 DebugRel\sys_arch.o
DebugRel\api_lib.o: .\tcpip\lwip-1.4.0\src\api\api_lib.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCPIP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h  \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\raw.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\api\api_lib.c $(CARM) -o DebugRel\api_lib.o
DebugRel\api_msg.o: .\tcpip\lwip-1.4.0\src\api\api_msg.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCPIP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h    \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\raw.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\dns.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\mld6.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\api\api_msg.c $(CARM) -o DebugRel\api_msg.o
DebugRel\err.o: .\tcpip\lwip-1.4.0\src\api\err.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\api\err.c $(CARM) -o DebugRel\err.o
DebugRel\netbuf.o: .\tcpip\lwip-1.4.0\src\api\netbuf.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\netbuf.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\api\netbuf.c $(CARM) -o DebugRel\netbuf.o
DebugRel\netdb.o: .\tcpip\lwip-1.4.0\src\api\netdb.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_API_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DNS_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\sockets.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\inet.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netdb.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\api\netdb.c $(CARM) -o DebugRel\netdb.o
DebugRel\netifapi.o: .\tcpip\lwip-1.4.0\src\api\netifapi.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCPIP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\api\netifapi.c $(CARM) -o DebugRel\netifapi.o
DebugRel\sockets.o: .\tcpip\lwip-1.4.0\src\api\sockets.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SOCKETS_H) \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\inet.h  \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h   \
	 tcpip\lwip-1.4.0\src\include\\lwip\opt.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\sys_arch.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcpip.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\api_msg.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\sys.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\igmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netif.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\api.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netifapi.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\dhcp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\udp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip.h \
	 tcpip\lwip-1.4.0\src\include\\ipv4\lwip\ip4.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\autoip.h \
	 tcpip\lwip-1.4.0\src\include\\netif\etharp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\timers.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\raw.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\inet_chksum.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\api\sockets.c $(CARM) -o DebugRel\sockets.o
DebugRel\tcpip.o: .\tcpip\lwip-1.4.0\src\api\tcpip.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INIT_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__NETIF_ETHERNETIF_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip_addr.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\sys_arch.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcpip.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\api_msg.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\sys.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\igmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\api.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netifapi.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\dhcp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\udp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip.h \
	 tcpip\lwip-1.4.0\src\include\\ipv4\lwip\ip4.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\autoip.h \
	 tcpip\lwip-1.4.0\src\include\\netif\etharp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\timers.h \
	 tcpip\lwip-1.4.0\src\include\\netif\ppp_oe.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\api\tcpip.c $(CARM) -o DebugRel\tcpip.o
DebugRel\autoip.o: .\tcpip\lwip-1.4.0\src\core\ipv4\autoip.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_UDP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_AUTOIP_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\ipv4\autoip.c $(CARM) -o \
	 DebugRel\autoip.o
DebugRel\icmp.o: .\tcpip\lwip-1.4.0\src\core\ipv4\icmp.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_ICMP_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\opt.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\inet_chksum.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\ipv4\icmp.c $(CARM) -o DebugRel\icmp.o
DebugRel\igmp.o: .\tcpip\lwip-1.4.0\src\core\ipv4\igmp.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\igmp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_UDP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INET_CHKSUM_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\ipv4\igmp.c $(CARM) -o DebugRel\igmp.o
DebugRel\ip_frag.o: .\tcpip\lwip-1.4.0\src\core\ipv4\ip_frag.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_ICMP_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h  \
	 tcpip\lwip-1.4.0\src\include\\lwip\opt.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\inet_chksum.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\ip_frag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\ipv4\ip_frag.c $(CARM) -o \
	 DebugRel\ip_frag.o
DebugRel\ip4.o: .\tcpip\lwip-1.4.0\src\core\ipv4\ip4.c \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\igmp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DHCP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_AUTOIP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H)  \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INET_CHKSUM_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h   \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\perf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\sys.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netif.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\raw.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\ip_frag.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\ipv4\ip4.c $(CARM) -o DebugRel\ip4.o
DebugRel\ip4_addr.o: .\tcpip\lwip-1.4.0\src\core\ipv4\ip4_addr.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\ipv4\ip4_addr.c $(CARM) -o \
	 DebugRel\ip4_addr.o
DebugRel\asn1_dec.o: .\tcpip\lwip-1.4.0\src\core\snmp\asn1_dec.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_ASN1_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\snmp\asn1_dec.c $(CARM) -o \
	 DebugRel\asn1_dec.o
DebugRel\asn1_enc.o: .\tcpip\lwip-1.4.0\src\core\snmp\asn1_enc.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_ASN1_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\snmp\asn1_enc.c $(CARM) -o \
	 DebugRel\asn1_enc.o
DebugRel\mib_structs.o: .\tcpip\lwip-1.4.0\src\core\snmp\mib_structs.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_STRUCTS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\snmp\mib_structs.c $(CARM) -o \
	 DebugRel\mib_structs.o
DebugRel\mib2.o: .\tcpip\lwip-1.4.0\src\core\snmp\mib2.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_UDP_H) \
	 tcpip\lwip-1.4.0\src\include\\netif\etharp.h   \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_ASN1_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_STRUCTS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip_addr.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\sys.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netif.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\ip_frag.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\snmp\mib2.c $(CARM) -o DebugRel\mib2.o
DebugRel\msg_in.o: .\tcpip\lwip-1.4.0\src\core\snmp\msg_in.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_UDP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_ASN1_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp_structs.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp_msg.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\snmp\msg_in.c $(CARM) -o \
	 DebugRel\msg_in.o
DebugRel\msg_out.o: .\tcpip\lwip-1.4.0\src\core\snmp\msg_out.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_UDP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SNMP_ASN1_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp_structs.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp_msg.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\snmp\msg_out.c $(CARM) -o \
	 DebugRel\msg_out.o
DebugRel\def.o: .\tcpip\lwip-1.4.0\src\core\def.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\def.c $(CARM) -o DebugRel\def.o
DebugRel\dhcp.o: .\tcpip\lwip-1.4.0\src\core\dhcp.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DHCP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_AUTOIP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DNS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\dhcp.c $(CARM) -o DebugRel\dhcp.o
DebugRel\dns.o: .\tcpip\lwip-1.4.0\src\core\dns.c \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_UDP_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DNS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\dns.c $(CARM) -o DebugRel\dns.o
DebugRel\inet_chksum.o: .\tcpip\lwip-1.4.0\src\core\inet_chksum.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INET_CHKSUM_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\inet_chksum.c $(CARM) -o \
	 DebugRel\inet_chksum.o
DebugRel\lwip_init.o: .\tcpip\lwip-1.4.0\src\core\lwip_init.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SOCKETS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INIT_H)  \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H)       \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\sys_arch.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcpip.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\api_msg.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\sys.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\igmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netif.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\api.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netifapi.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\dhcp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\udp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip.h \
	 tcpip\lwip-1.4.0\src\include\\ipv4\lwip\ip4.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\autoip.h \
	 tcpip\lwip-1.4.0\src\include\\netif\etharp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\timers.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\raw.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\dns.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\mld6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp_structs.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp_msg.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\nd6.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\lwip_init.c $(CARM) -o \
	 DebugRel\lwip_init.o
DebugRel\lwip_pbuf.o: .\tcpip\lwip-1.4.0\src\core\lwip_pbuf.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCPIP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H)   \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\perf.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\inet_chksum.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\lwip_pbuf.c $(CARM) -o \
	 DebugRel\lwip_pbuf.o
DebugRel\lwip_timers.o: .\tcpip\lwip-1.4.0\src\core\lwip_timers.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCPIP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_MEMP_H)       \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\dns.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\mld6.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\ip_frag.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\nd6.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_frag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\lwip_timers.c $(CARM) -o \
	 DebugRel\lwip_timers.o
DebugRel\mem.o: .\tcpip\lwip-1.4.0\src\core\mem.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\mem.c $(CARM) -o DebugRel\mem.o
DebugRel\memp.o: .\tcpip\lwip-1.4.0\src\core\memp.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCPIP_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\usr_data.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H)          \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\raw.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\dns.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\mld6.h \
	 tcpip\lwip-1.4.0\src\include\\netif\ppp_oe.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\ip_frag.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp_structs.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp_msg.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\nd6.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_frag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\memp.c $(CARM) -o DebugRel\memp.o
DebugRel\netif.o: .\tcpip\lwip-1.4.0\src\core\netif.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCPIP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h   \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\mld6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\dhcp6.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\netif.c $(CARM) -o DebugRel\netif.o
DebugRel\raw.o: .\tcpip\lwip-1.4.0\src\core\raw.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_NETIF_H) \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_RAW_H) \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\perf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\raw.c $(CARM) -o DebugRel\raw.o
DebugRel\stats.o: .\tcpip\lwip-1.4.0\src\core\stats.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\stats.c $(CARM) -o DebugRel\stats.o
DebugRel\sys.o: .\tcpip\lwip-1.4.0\src\core\sys.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_OPT_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\sys.c $(CARM) -o DebugRel\sys.o
DebugRel\tcp.o: .\tcpip\lwip-1.4.0\src\core\tcp.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_TCP_IMPL_H)  \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\nd6.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\tcp.c $(CARM) -o DebugRel\tcp.o
DebugRel\tcp_in.o: .\tcpip\lwip-1.4.0\src\core\tcp_in.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INET_CHKSUM_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h  \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\perf.h  \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\sys.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netif.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\nd6.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\tcp_in.c $(CARM) -o DebugRel\tcp_in.o
DebugRel\tcp_out.o: .\tcpip\lwip-1.4.0\src\core\tcp_out.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_INET_CHKSUM_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h  \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\err.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\sys.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\netif.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\ip.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp.h \
	 tcpip\lwip-1.4.0\src\include\ipv4\\lwip\icmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\tcp_impl.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\tcp_out.c $(CARM) -o DebugRel\tcp_out.o
DebugRel\udp.o: .\tcpip\lwip-1.4.0\src\core\udp.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DHCP_H) \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_ICMP_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\perf.h  \
	 tcpip\lwip-1.4.0\src\include\\lwip\opt.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6_addr.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\inet_chksum.h \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\icmp6.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\core\udp.c $(CARM) -o DebugRel\udp.o
DebugRel\etharp.o: .\tcpip\lwip-1.4.0\src\netif\etharp.c \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_IP_ADDR_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_DHCP_H) \
	 tcpip\lwip-1.4.0\src\include\\ipv6\lwip\ip6.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE_IPV4__LWIP_AUTOIP_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H)  \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\opt.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\bpstruct.h \
	 tcpip\lwip-1.4.0\ports\icomm\include\\arch\epstruct.h \
	 tcpip\lwip-1.4.0\src\include\\netif\ppp_oe.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\netif\etharp.c $(CARM) -o DebugRel\etharp.o
DebugRel\ethernetif.o: .\tcpip\lwip-1.4.0\src\netif\ethernetif.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 tcpip\lwip-1.4.0\src\include\\lwip\mem.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__NETIF_ETHERNETIF_H) \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__NETIF_PPP_OE_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\netif\ethernetif.c $(CARM) -o \
	 DebugRel\ethernetif.o
DebugRel\slipif.o: .\tcpip\lwip-1.4.0\src\netif\slipif.c \
	 tcpip\lwip-1.4.0\src\include\\lwip\def.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_SYS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\lwip_pbuf.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__LWIP_STATS_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\snmp.h \
	 $(TCPIP_LWIP-1_4_0_SRC_INCLUDE__NETIF_SLIPIF_H) \
	 tcpip\lwip-1.4.0\src\include\\lwip\sio.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\netif\slipif.c $(CARM) -o DebugRel\slipif.o
DebugRel\md5.o: .\tcpip\lwip-1.4.0\src\netif\ppp\md5.c \
	 $(TCPIP_LWIP-1_4_0_SRC_NETIF_PPP_PPP_IMPL_H) \
	 tcpip\lwip-1.4.0\src\netif\ppp\pppdebug.h \
	 tcpip\lwip-1.4.0\src\netif\ppp\md5.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tcpip\lwip-1.4.0\src\netif\ppp\md5.c $(CARM) -o DebugRel\md5.o
