#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ --no_debug --dwarf2 -O3
CARM_SRCS	= 		  .\src\sys.c .\src\sys_project.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Release\sys.o Release\sys_project.o 

CARM_CPP	=  --no_debug --dwarf2 --cpp -O3
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb --no_debug --dwarf2 -O3
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb --no_debug --dwarf2 --cpp -O3
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= sys_release_Release.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Release\..\..\lib\release\sys_release.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 64
#   Selected list: ..\ui\inc\ui.h ..\ui\inc\osd_draw_api.h \
	 ..\timer\inc\timer.h ..\board\inc\intreg.h \
	 ..\mpeg4\inc\mp4ratecontrol.h ..\siu\inc\siureg.h 
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\project.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) ..\inc\\memorypool.h 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__RTCAPI_H=..\inc\\rtcapi.h 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\task.h $(___INC__RTCAPI_H) 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__ISUAPI_H=..\inc\\isuapi.h 
___INC__ASFAPI_H=..\inc\\asfapi.h $(___INC__FSAPI_H) 
___INC__MOVAPI_H=..\inc\\movapi.h 
___INC__TIMERAPI_H=..\inc\\timerapi.h 
___INC__MPEG4API_H=..\inc\\mpeg4api.h ..\mpeg4\inc\mpeg4.h 
___INC__IISAPI_H=..\inc\\iisapi.h 
___INC__ADCAPI_H=..\inc\\adcapi.h 
___INC__UARTAPI_H=..\inc\\uartapi.h ..\inc\\task.h 
___INC__SMCAPI_H=..\inc\\smcapi.h $(___INC__GENERAL_H) 
___INC__GPSAPI_H=..\inc\\gpsapi.h $(___INC__GENERAL_H) ..\inc\\board.h 
# DEPEND: end include files

Release\sys.o: .\src\sys.c inc\\sys.h ..\inc\\sysapi.h $(___INC__SIUAPI_H) \
	 $(___INC__UIAPI_H) $(___INC__DCFAPI_H) ..\inc\\ipuapi.h \
	 $(___INC__ISUAPI_H) ..\inc\\iduapi.h ..\inc\\jpegapi.h \
	 ..\inc\\mp4api.h $(___INC__ASFAPI_H) $(___INC__MOVAPI_H) \
	 $(___INC__TIMERAPI_H) ..\inc\\usbapi.h ..\inc\\aviapi.h \
	 $(___INC__MPEG4API_H) $(___INC__IISAPI_H) ..\inc\\ispapi.h \
	 ..\inc\\gpioapi.h $(___INC__ADCAPI_H)  ..\inc\\clockswitchapi.h \
	 ..\inc\\awbapi.h ..\sdc\inc\sdcreg.h ..\spi\inc\spireg.h \
	 ..\smc\inc\smcreg.h $(___INC__SMCAPI_H) ..\idu\inc\idureg.h \
	 ..\inc\\spiapi.h  ..\inc\\board.h ..\inc\\uartapi.h ..\inc\\gpsapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\sys.c \
	 $(CARM) -o Release\sys.o
Release\sys_project.o: .\src\sys_project.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\sys_project.c $(CARM) -o Release\sys_project.o
