#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I.\include\tutk_p2p -I.\include\netif -I.\include\lwip \
	 -I.\include\arch -I.\gpi\inc\ -I..\inc\ -I..\inc\os\ -I.\include\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I.\include\tutk_p2p -I.\include\netif -I.\include\lwip -I.\include\arch -I.\gpi\inc\ -I..\inc\ -I..\inc\os\ -I.\include\ -g --dwarf2 --pointer_alignment=1 -O1
CARM_SRCS	= 		  CloudService.c jsmn.c .\netif\ppp\md5.c \
		  tutk_p2p\p2p_server.c .\rtsp\rtp.c .\rtsp\sdp.c \
		  .\rtsp\rtcp.c .\rtsp\rtsp_method.c \
		  .\rtsp\handler_rtsp.c .\core\dns_clinet.c \
		  LwIPEntry.c .\core\dhcp.c .\core\inet.c \
		  .\core\mem.c .\core\memp.c .\core\netif.c \
		  .\core\pbuf.c .\core\raw.c .\core\stats.c \
		  .\core\sys.c .\core\tcp.c .\core\tcp_in.c \
		  .\core\tcp_out.c .\core\udp.c .\core\snmp\msg_out.c \
		  .\core\snmp\asn1_dec.c .\core\snmp\asn1_enc.c \
		  .\core\snmp\mib2.c .\core\snmp\mib_structs.c \
		  .\core\snmp\msg_in.c .\arch\sys_arch.c \
		  .\api\tcpip.c .\api\api_lib.c .\api\api_msg.c \
		  .\api\err.c .\api\sockets.c .\netif\etharp.c \
		  .\netif\ethernetif.c .\netif\loopif.c \
		  .\netif\slipif.c .\tools\converter.c \
		  .\tools\search.c .\tools\stringExtAPI.c \
		  .\http\handler_http.c .\core\ipv4\icmp.c \
		  .\core\ipv4\ip.c .\core\ipv4\ip_addr.c \
		  .\core\ipv4\ip_frag.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  DebugRel\CloudService.o DebugRel\jsmn.o \
		  DebugRel\md5.o DebugRel\p2p_server.o DebugRel\rtp.o \
		  DebugRel\sdp.o DebugRel\rtcp.o \
		  DebugRel\rtsp_method.o DebugRel\handler_rtsp.o \
		  DebugRel\dns_clinet.o DebugRel\LwIPEntry.o \
		  DebugRel\dhcp.o DebugRel\inet.o DebugRel\mem.o \
		  DebugRel\memp.o DebugRel\netif.o DebugRel\pbuf.o \
		  DebugRel\raw.o DebugRel\stats.o DebugRel\sys.o \
		  DebugRel\tcp.o DebugRel\tcp_in.o DebugRel\tcp_out.o \
		  DebugRel\udp.o DebugRel\msg_out.o \
		  DebugRel\asn1_dec.o DebugRel\asn1_enc.o \
		  DebugRel\mib2.o DebugRel\mib_structs.o \
		  DebugRel\msg_in.o DebugRel\sys_arch.o \
		  DebugRel\tcpip.o DebugRel\api_lib.o \
		  DebugRel\api_msg.o DebugRel\err.o \
		  DebugRel\sockets.o DebugRel\etharp.o \
		  DebugRel\ethernetif.o DebugRel\loopif.o \
		  DebugRel\slipif.o DebugRel\converter.o \
		  DebugRel\search.o DebugRel\stringExtAPI.o \
		  DebugRel\handler_http.o DebugRel\icmp.o \
		  DebugRel\ip.o DebugRel\ip_addr.o DebugRel\ip_frag.o 

CARM_CPP	=  -g --dwarf2 --cpp -O1
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2 -O1
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp -O1
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= Lwip_DebugRel.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Debug\..\..\lib\Lwip.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 59
#   Selected list: ..\lwip\include\lwip\rtp.h ..\lwip\include\lwip\rtsp.h \
	 ..\lwip\include\lwip\sdp.h ..\lwip\include\lwip\net.h \
	 ..\lwip\include\lwip\rtp.h ..\lwip\include\lwip\rtsp.h \
	 ..\lwip\include\lwip\rtcp.h ..\lwip\include\lwip\net.h \
	 ..\lwip\include\lwip\rtp.h ..\lwip\include\lwip\rtsp.h \
	 ..\lwip\include\lwip\sdp.h ..\lwip\include\lwip\api.h \
	 ..\lwip\include\lwip\tcpip.h ..\lwip\include\lwip\api.h \
	 ..\lwip\include\lwip\net.h ..\lwip\include\lwip\rtp.h \
	 ..\lwip\include\lwip\rtsp.h ..\lwip\include\lwip\dns_clinet.h \
	 ..\lwip\tools\stringextapi.h ..\lwip\tools\search.h \
	 ..\lwip\tools\converter.h ..\lwip\include\lwip\tcpip.h \
	 ..\lwip\include\lwip\api.h ..\lwip\tools\stringextapi.h \
	 ..\lwip\tools\search.h ..\lwip\tools\converter.h \
	 ..\lwip\include\lwip\dns_clinet.h .\lwip\lwipsys.h .\lwip\def.h \
	 .\arch\cc.h .\arch\sys_arch.h ..\gpi\inc\net.h ..\gpi\inc\gpi.h \
	 ..\lwip\include\lwip\tcpip.h ..\lwip\include\lwip\api.h \
	 ..\lwip\include\lwip\dns_clinet.h ..\lwip\tools\stringextapi.h \
	 ..\lwip\tools\search.h ..\lwip\tools\converter.h 
INCLUDE_TUTK_P2P_MR8200DEF_HOMEAUTOMATION_H= \
	include\tutk_p2p\mr8200def_homeautomation.h \
	 include\tutk_p2p\avioctrldefs.h 
INCLUDE__LWIP_OPT_H=include\\lwip\opt.h include\\arch\lwipopts.h \
	 include\\lwip\debug.h 
INCLUDE__LWIP_LWIPSYS_H=include\\lwip\lwipsys.h include\\arch\sys_arch.h 
INCLUDE__LWIP_IP_H=include\\lwip\ip.h include\\lwip\arch.h \
	 include\\lwip\def.h 
INCLUDE__LWIP_RAW_H=include\\lwip\raw.h include\\lwip\inet.h 
INCLUDE__LWIP_TCP_H=include\\lwip\tcp.h include\\lwip\icmp.h 
INCLUDE__LWIP_API_H=include\\lwip\api.h include\\lwip\pbuf.h \
	 $(INCLUDE__LWIP_LWIPSYS_H) $(INCLUDE__LWIP_IP_H) \
	 $(INCLUDE__LWIP_RAW_H) include\\lwip\udp.h $(INCLUDE__LWIP_TCP_H) \
	 include\\lwip\err.h 
INCLUDE__LWIP_STATS_H=include\\lwip\stats.h include\\lwip\memp.h 
INCLUDE__LWIP_TCPIP_H=include\\lwip\tcpip.h include\\lwip\api_msg.h 
INCLUDE__LWIP_NETIF_H=include\\lwip\netif.h include\\lwip\dhcp.h 
NETIF_PPP_PPP_H=netif\ppp\ppp.h $(INCLUDE__LWIP_OPT_H) include\\lwip\sio.h \
	 $(INCLUDE__LWIP_API_H) include\\lwip\sockets.h \
	 $(INCLUDE__LWIP_STATS_H) include\\lwip\mem.h \
	 $(INCLUDE__LWIP_TCPIP_H) $(INCLUDE__LWIP_NETIF_H) 
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\application.h \
	 ..\inc\\project.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\uikey.h ..\inc\\rfiuapi.h 
___INC__SYSAPI_H=..\inc\\sysapi.h 
___INC__FSAPI_H=..\inc\\fsapi.h 
___INC__ASFAPI_H=..\inc\\asfapi.h $(___INC__FSAPI_H) 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GLOBALVARIABLE_H=..\inc\\globalvariable.h $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\task.h ..\inc\\mp4api.h \
	 $(___INC__ASFAPI_H) ..\inc\\aviapi.h ..\inc\\mpeg4api.h \
	 ..\inc\\isuapi.h ..\inc\\iduapi.h ..\inc\\gpioapi.h \
	 $(___INC__SIUAPI_H) $(___INC__SYSAPI_H) $(___INC__OSAPI_H) \
	 ..\inc\\rtcapi.h ..\inc\\i2capi.h $(___INC__UIAPI_H) \
	 ..\inc\\memorypool.h ..\inc\\iisapi.h 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__TIMERAPI_H=..\inc\\timerapi.h $(___INC__GENERAL_H) 
___UI_INC_UI_H=..\ui\inc\ui.h $(___INC__FSAPI_H) ..\inc\\rtcapi.h \
	 $(___INC__UIAPI_H) 
___UI_INC_UI_PROJECT_H=..\ui\inc\ui_project.h ..\inc\\motiondetect_api.h \
	 ..\inc\\rtcapi.h 
INCLUDE_LWIP_API_H=include\lwip\api.h $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\pbuf.h $(INCLUDE__LWIP_LWIPSYS_H) \
	 $(INCLUDE__LWIP_IP_H) $(INCLUDE__LWIP_RAW_H) include\\lwip\udp.h \
	 $(INCLUDE__LWIP_TCP_H) include\\lwip\err.h 
INCLUDE__NETIF_ETHARP_H=include\\netif\etharp.h include\\lwip\pbuf.h \
	 include\\lwip\ip_addr.h $(INCLUDE__LWIP_NETIF_H) \
	 $(INCLUDE__LWIP_IP_H) include\\arch\bpstruct.h \
	 include\\arch\epstruct.h 
INCLUDE__LWIP_SNMP_H=include\\lwip\snmp.h $(INCLUDE__LWIP_NETIF_H) \
	 include\\lwip\udp.h 
___INC_OS__UCOS_II_H=..\inc\os\\ucos_ii.h ..\inc\os\\os_cfg.h 
INCLUDE__ARCH_CC_H=include\\arch\cc.h include\arch\cpu.h \
	 ..\inc\os\\os_cpu.h $(___INC_OS__UCOS_II_H) 
INCLUDE__LWIP_SNMP_ASN1_H=include\\lwip\snmp_asn1.h $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__ARCH_CC_H) include\\lwip\err.h include\\lwip\pbuf.h \
	 $(INCLUDE__LWIP_SNMP_H) 
INCLUDE__LWIP_SNMP_STRUCTS_H=include\\lwip\snmp_structs.h 
INCLUDE__LWIP_SNMP_MSG_H=include\\lwip\snmp_msg.h $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__ARCH_CC_H) $(INCLUDE__LWIP_SNMP_H) \
	 $(INCLUDE__LWIP_SNMP_STRUCTS_H) 
INCLUDE__LWIP_IP_FRAG_H=include\\lwip\ip_frag.h $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\err.h include\\lwip\pbuf.h $(INCLUDE__LWIP_NETIF_H) \
	 include\\lwip\ip_addr.h 
INCLUDE__NETIF_LOOPIF_H=include\\netif\loopif.h $(INCLUDE__LWIP_NETIF_H) 
INCLUDE__NETIF_SLIPIF_H=include\\netif\slipif.h $(INCLUDE__LWIP_NETIF_H) 
# DEPEND: end include files

DebugRel\CloudService.o: CloudService.c include\\jsmn.h \
	 $(INCLUDE_TUTK_P2P_MR8200DEF_HOMEAUTOMATION_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c CloudService.c \
	 $(CARM) -o DebugRel\CloudService.o
DebugRel\jsmn.o: jsmn.c include\\jsmn.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c jsmn.c $(CARM) -o \
	 DebugRel\jsmn.o
DebugRel\md5.o: .\netif\ppp\md5.c $(NETIF_PPP_PPP_H) netif\ppp\md5.h \
	 netif\ppp\pppdebug.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\netif\ppp\md5.c \
	 $(CARM) -o DebugRel\md5.o
DebugRel\p2p_server.o: tutk_p2p\p2p_server.c include\\jsmn.h \
	 $(INCLUDE_TUTK_P2P_MR8200DEF_HOMEAUTOMATION_H) \
	 ..\inc\\tutkiotcapi.h ..\inc\\tutkavapi.h \
	 include\tutk_p2p\avframeinfo.h ..\inc\\gpiapi.h ..\inc\\lwipapi.h \
	 $(___INC__GLOBALVARIABLE_H) $(___INC__DCFAPI_H)  \
	 ..\inc\\p2pserver_api.h   ..\inc\\encrptyapi.h ..\inc\\timerapi.h \
	 ..\ui\inc\ui.h ..\ui\inc\ui_project.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 tutk_p2p\p2p_server.c $(CARM) -o DebugRel\p2p_server.o
DebugRel\rtp.o: .\rtsp\rtp.c $(___INC__GENERAL_H) ..\inc\\mpeg4api.h \
	 ..\inc\\iisapi.h ..\inc\\task.h $(___INC__UIAPI_H) \
	 include\lwip\rtp.h $(INCLUDE_LWIP_API_H) include\lwip\net.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\rtsp\rtp.c \
	 $(CARM) -o DebugRel\rtp.o
DebugRel\sdp.o: .\rtsp\sdp.c $(___INC__GENERAL_H) ..\inc\\mpeg4api.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\rtsp\sdp.c \
	 $(CARM) -o DebugRel\sdp.o
DebugRel\rtcp.o: .\rtsp\rtcp.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\rtsp\rtcp.c \
	 $(CARM) -o DebugRel\rtcp.o
DebugRel\rtsp_method.o: .\rtsp\rtsp_method.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\rtsp\rtsp_method.c $(CARM) -o DebugRel\rtsp_method.o
DebugRel\handler_rtsp.o: .\rtsp\handler_rtsp.c $(___INC_OS__UCOS_II_H) \
	 $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\rtsp\handler_rtsp.c $(CARM) -o DebugRel\handler_rtsp.o
DebugRel\dns_clinet.o: .\core\dns_clinet.c ..\inc\os\\os_cpu.h \
	 $(___INC_OS__UCOS_II_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\dns_clinet.c $(CARM) -o DebugRel\dns_clinet.o
DebugRel\LwIPEntry.o: LwIPEntry.c $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\pbuf.h $(INCLUDE__LWIP_LWIPSYS_H) \
	 include\\lwip\mem.h include\\lwip\memp.h $(INCLUDE__LWIP_TCPIP_H) \
	 $(___INC__GENERAL_H) ..\inc\\gpiapi.h $(___INC__UIAPI_H) \
	 $(___INC__SYSAPI_H) ..\inc\\rtcapi.h ..\inc\\p2pserver_api.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c LwIPEntry.c \
	 $(CARM) -o DebugRel\LwIPEntry.o
DebugRel\dhcp.o: .\core\dhcp.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\inet.h \
	 include\\lwip\udp.h include\\lwip\mem.h $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__NETIF_ETHARP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\dhcp.c \
	 $(CARM) -o DebugRel\dhcp.o
DebugRel\inet.o: .\core\inet.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\arch.h \
	 include\\lwip\def.h include\\lwip\inet.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\inet.c \
	 $(CARM) -o DebugRel\inet.o
DebugRel\mem.o: .\core\mem.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\arch.h \
	 include\\lwip\def.h include\\lwip\mem.h $(INCLUDE__LWIP_STATS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\mem.c \
	 $(CARM) -o DebugRel\mem.o
DebugRel\memp.o: .\core\memp.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_API_H) $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__LWIP_TCPIP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\memp.c \
	 $(CARM) -o DebugRel\memp.o
DebugRel\netif.o: .\core\netif.c include\\lwip\def.h \
	 include\\lwip\ip_addr.h $(INCLUDE__LWIP_TCP_H) \
	 $(INCLUDE__LWIP_SNMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\netif.c \
	 $(CARM) -o DebugRel\netif.o
DebugRel\pbuf.o: .\core\pbuf.c $(INCLUDE__LWIP_OPT_H) include\\lwip\pbuf.h \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\def.h include\\lwip\mem.h \
	 $(INCLUDE__LWIP_STATS_H) include\\arch\perf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\pbuf.c \
	 $(CARM) -o DebugRel\pbuf.o
DebugRel\raw.o: .\core\raw.c include\\lwip\def.h include\\lwip\ip_addr.h \
	 $(INCLUDE__LWIP_RAW_H) $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__LWIP_SNMP_H) include\\arch\perf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\raw.c \
	 $(CARM) -o DebugRel\raw.o
DebugRel\stats.o: .\core\stats.c $(INCLUDE__LWIP_OPT_H) include\\lwip\def.h \
	 include\\lwip\mem.h $(INCLUDE__LWIP_STATS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\stats.c \
	 $(CARM) -o DebugRel\stats.o
DebugRel\sys.o: .\core\sys.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\def.h include\\lwip\memp.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\sys.c \
	 $(CARM) -o DebugRel\sys.o
DebugRel\tcp.o: .\core\tcp.c include\\lwip\def.h $(INCLUDE__LWIP_TCP_H) \
	 include\\lwip\mem.h include\\lwip\memp.h $(INCLUDE__LWIP_SNMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\tcp.c \
	 $(CARM) -o DebugRel\tcp.o
DebugRel\tcp_in.o: .\core\tcp_in.c include\\lwip\def.h \
	 include\\lwip\ip_addr.h include\\lwip\inet.h \
	 $(INCLUDE__LWIP_TCP_H) include\\lwip\mem.h \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H) include\\arch\perf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\tcp_in.c \
	 $(CARM) -o DebugRel\tcp_in.o
DebugRel\tcp_out.o: .\core\tcp_out.c $(INCLUDE__LWIP_LWIPSYS_H) \
	 include\\lwip\def.h include\\lwip\ip_addr.h include\\lwip\inet.h \
	 $(INCLUDE__LWIP_TCP_H) include\\lwip\mem.h \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\tcp_out.c \
	 $(CARM) -o DebugRel\tcp_out.o
DebugRel\udp.o: .\core\udp.c include\\lwip\def.h include\\lwip\ip_addr.h \
	 include\\lwip\inet.h include\\lwip\icmp.h $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__LWIP_SNMP_H) include\\arch\perf.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\udp.c \
	 $(CARM) -o DebugRel\udp.o
DebugRel\msg_out.o: .\core\snmp\msg_out.c $(INCLUDE__LWIP_SNMP_ASN1_H)  \
	 include\\lwip\snmp_msg.h include\\lwip\snmp_structs.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\msg_out.c $(CARM) -o DebugRel\msg_out.o
DebugRel\asn1_dec.o: .\core\snmp\asn1_dec.c $(INCLUDE__LWIP_SNMP_ASN1_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\asn1_dec.c $(CARM) -o DebugRel\asn1_dec.o
DebugRel\asn1_enc.o: .\core\snmp\asn1_enc.c $(INCLUDE__LWIP_SNMP_ASN1_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\asn1_enc.c $(CARM) -o DebugRel\asn1_enc.o
DebugRel\mib2.o: .\core\snmp\mib2.c $(INCLUDE__LWIP_TCP_H) \
	 $(INCLUDE__NETIF_ETHARP_H)  $(INCLUDE__LWIP_SNMP_STRUCTS_H)  \
	 include\\lwip\opt.h include\\arch\cc.h include\arch\cpu.h \
	 ..\inc\os\\os_cpu.h ..\inc\os\\ucos_ii.h ..\inc\os\\os_cfg.h \
	 include\\lwip\err.h include\\lwip\snmp.h include\\lwip\snmp_asn1.h \
	 include\\lwip\ip_frag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\snmp\mib2.c \
	 $(CARM) -o DebugRel\mib2.o
DebugRel\mib_structs.o: .\core\snmp\mib_structs.c $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\mem.h $(INCLUDE__LWIP_SNMP_STRUCTS_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\mib_structs.c $(CARM) -o DebugRel\mib_structs.o
DebugRel\msg_in.o: .\core\snmp\msg_in.c include\\lwip\ip_addr.h \
	 include\\lwip\mem.h $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__LWIP_SNMP_ASN1_H)  include\\lwip\snmp_msg.h \
	 include\\lwip\snmp_structs.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\snmp\msg_in.c $(CARM) -o DebugRel\msg_in.o
DebugRel\sys_arch.o: .\arch\sys_arch.c $(___INC_OS__UCOS_II_H) ..\inc\\task.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\arch\sys_arch.c \
	 $(CARM) -o DebugRel\sys_arch.o
DebugRel\tcpip.o: .\api\tcpip.c $(INCLUDE__LWIP_LWIPSYS_H) \
	 $(INCLUDE__LWIP_IP_H) include\\lwip\udp.h $(INCLUDE__LWIP_TCP_H) \
	 include\\lwip\memp.h $(INCLUDE__LWIP_TCPIP_H) \
	 $(INCLUDE__LWIP_IP_FRAG_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\tcpip.c \
	 $(CARM) -o DebugRel\tcpip.o
DebugRel\api_lib.o: .\api\api_lib.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_API_H) include\\lwip\memp.h include\\lwip\api_msg.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\api_lib.c \
	 $(CARM) -o DebugRel\api_lib.o
DebugRel\api_msg.o: .\api\api_msg.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\arch.h \
	 include\\lwip\memp.h $(INCLUDE__LWIP_TCPIP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\api_msg.c \
	 $(CARM) -o DebugRel\api_msg.o
DebugRel\err.o: .\api\err.c include\\lwip\err.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\err.c \
	 $(CARM) -o DebugRel\err.o
DebugRel\sockets.o: .\api\sockets.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_API_H) include\\lwip\sockets.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\api\sockets.c \
	 $(CARM) -o DebugRel\sockets.o
DebugRel\etharp.o: .\netif\etharp.c $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\inet.h $(INCLUDE__LWIP_STATS_H) \
	 $(INCLUDE__NETIF_ETHARP_H)  include\\lwip\udp.h include\\lwip\snmp.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\netif\etharp.c \
	 $(CARM) -o DebugRel\etharp.o
DebugRel\ethernetif.o: .\netif\ethernetif.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__ARCH_CC_H) $(INCLUDE__LWIP_LWIPSYS_H) \
	 include\\lwip\mem.h $(___INC__GENERAL_H) ..\inc\\task.h \
	 $(___INC__UIAPI_H) ..\inc\\board.h $(INCLUDE__NETIF_ETHARP_H) \
	 include\\netif\dm9000.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\netif\ethernetif.c $(CARM) -o DebugRel\ethernetif.o
DebugRel\loopif.o: .\netif\loopif.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_IP_H) $(INCLUDE__LWIP_TCP_H) include\\lwip\mem.h \
	 $(INCLUDE__NETIF_LOOPIF_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\netif\loopif.c \
	 $(CARM) -o DebugRel\loopif.o
DebugRel\slipif.o: .\netif\slipif.c $(INCLUDE__LWIP_OPT_H) \
	 include\\lwip\sio.h include\\lwip\pbuf.h \
	 $(INCLUDE__LWIP_LWIPSYS_H) include\\lwip\def.h \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__NETIF_SLIPIF_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\netif\slipif.c \
	 $(CARM) -o DebugRel\slipif.o
DebugRel\converter.o: .\tools\converter.c $(___INC_OS__UCOS_II_H) \
	 tools\converter.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tools\converter.c $(CARM) -o DebugRel\converter.o
DebugRel\search.o: .\tools\search.c $(___INC_OS__UCOS_II_H) tools\search.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\tools\search.c \
	 $(CARM) -o DebugRel\search.o
DebugRel\stringExtAPI.o: .\tools\stringExtAPI.c $(___INC_OS__UCOS_II_H) \
	 tools\stringextapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\tools\stringExtAPI.c $(CARM) -o DebugRel\stringExtAPI.o
DebugRel\handler_http.o: .\http\handler_http.c $(___INC_OS__UCOS_II_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\http\handler_http.c $(CARM) -o DebugRel\handler_http.o
DebugRel\icmp.o: .\core\ipv4\icmp.c $(INCLUDE__LWIP_OPT_H) \
	 $(INCLUDE__LWIP_IP_H) include\\lwip\inet.h include\\lwip\icmp.h \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\ipv4\icmp.c \
	 $(CARM) -o DebugRel\icmp.o
DebugRel\ip.o: .\core\ipv4\ip.c $(INCLUDE__LWIP_IP_H) \
	 $(INCLUDE__LWIP_RAW_H) $(INCLUDE__LWIP_TCP_H) include\\lwip\mem.h \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H) \
	 include\\arch\perf.h  include\\lwip\opt.h include\\lwip\pbuf.h \
	 include\\lwip\ip_addr.h include\\lwip\err.h include\\lwip\ip_frag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\core\ipv4\ip.c \
	 $(CARM) -o DebugRel\ip.o
DebugRel\ip_addr.o: .\core\ipv4\ip_addr.c include\\lwip\ip_addr.h \
	 include\\lwip\inet.h $(INCLUDE__LWIP_NETIF_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\ipv4\ip_addr.c $(CARM) -o DebugRel\ip_addr.o
DebugRel\ip_frag.o: .\core\ipv4\ip_frag.c $(INCLUDE__LWIP_IP_H) \
	 $(INCLUDE__LWIP_STATS_H) $(INCLUDE__LWIP_SNMP_H)  \
	 include\\lwip\opt.h include\\lwip\pbuf.h include\\lwip\ip_addr.h \
	 include\\lwip\err.h include\\lwip\ip_frag.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\core\ipv4\ip_frag.c $(CARM) -o DebugRel\ip_frag.o
