#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\mars_controller\ -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\mars_controller\ -I..\inc\ -I.\inc\ -g --dwarf2
CARM_SRCS	= 		  .\src\GlobalVariable.c .\src\core_util.c \
		  .\src\core_state.c .\src\core_portme.c \
		  .\src\core_matrix.c .\src\core_main.c \
		  .\src\core_list_join.c .\src\mcpu.c .\src\mmu.c \
		  .\src\ClockSwitch.c .\src\MemoryPool.c .\src\main.c \
		  .\src\main_task_project.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  Debug\GlobalVariable.o Debug\core_util.o \
		  Debug\core_state.o Debug\core_portme.o \
		  Debug\core_matrix.o Debug\core_main.o \
		  Debug\core_list_join.o Debug\mcpu.o Debug\mmu.o \
		  Debug\ClockSwitch.o Debug\MemoryPool.o Debug\main.o \
		  Debug\main_task_project.o 

CARM_CPP	=  -g --dwarf2 --cpp
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= main_Debug.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Release\..\..\lib\main.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 48
#   Selected list: .\fs\fs_api.h 
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h ..\inc\\project.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h 
___INC__FSAPI_H=..\inc\\fsapi.h 
___INC__ASFAPI_H=..\inc\\asfapi.h $(___INC__FSAPI_H) 
___INC__SIUAPI_H=..\inc\\siuapi.h ..\inc\\motiondetect_api.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\uikey.h 
___INC__GLOBALVARIABLE_H=..\inc\\globalvariable.h $(___INC__GENERAL_H) \
	 ..\inc\\board.h ..\inc\\task.h ..\inc\\mp4api.h \
	 $(___INC__ASFAPI_H) ..\inc\\aviapi.h ..\inc\\mpeg4api.h \
	 ..\inc\\isuapi.h ..\inc\\iduapi.h ..\inc\\gpioapi.h \
	 $(___INC__SIUAPI_H) ..\inc\\sysapi.h $(___INC__OSAPI_H) \
	 ..\inc\\rtcapi.h ..\inc\\i2capi.h $(___INC__UIAPI_H) \
	 ..\inc\\memorypool.h ..\inc\\iisapi.h 
___INC__IMA_ADPCM_API_H=..\inc\\ima_adpcm_api.h 
INC__MMU_H=inc\\mmu.h $(___INC__GENERAL_H) ..\inc\\mmuapi.h 
___INC__SMCAPI_H=..\inc\\smcapi.h $(___INC__GENERAL_H) 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
___INC__VIDEOCODECAPI_H=..\inc\\videocodecapi.h ..\inc\\mpeg4api.h 
___INC__H264API_H=..\inc\\h264api.h $(___INC__VIDEOCODECAPI_H) 
___INC__TIMERAPI_H=..\inc\\timerapi.h $(___INC__GENERAL_H) 
___INC__UARTAPI_H=..\inc\\uartapi.h ..\inc\\task.h 
___INC__ADCAPI_H=..\inc\\adcapi.h 
___INC__HIAPI_H=..\inc\\hiapi.h $(___INC__GENERAL_H) 
___UI_INC_UI_H=..\ui\inc\ui.h $(___INC__FSAPI_H) ..\inc\\rtcapi.h \
	 $(___INC__UIAPI_H) 
# DEPEND: end include files

Debug\GlobalVariable.o: .\src\GlobalVariable.c $(___INC__GLOBALVARIABLE_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\GlobalVariable.c $(CARM) -o Debug\GlobalVariable.o
Debug\core_util.o: .\src\core_util.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\core_util.c \
	 $(CARM) -o Debug\core_util.o
Debug\core_state.o: .\src\core_state.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\core_state.c \
	 $(CARM) -o Debug\core_state.o
Debug\core_portme.o: .\src\core_portme.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\core_portme.c $(CARM) -o Debug\core_portme.o
Debug\core_matrix.o: .\src\core_matrix.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\core_matrix.c $(CARM) -o Debug\core_matrix.o
Debug\core_main.o: .\src\core_main.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\core_main.c \
	 $(CARM) -o Debug\core_main.o
Debug\core_list_join.o: .\src\core_list_join.c $(___INC__GENERAL_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\core_list_join.c $(CARM) -o Debug\core_list_join.o
Debug\mcpu.o: .\src\mcpu.c $(___INC__GENERAL_H) ..\inc\\board.h \
	 inc\\mcpureg.h $(___INC__IMA_ADPCM_API_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\mcpu.c \
	 $(CARM) -o Debug\mcpu.o
Debug\mmu.o: .\src\mmu.c ..\inc\\board.h $(INC__MMU_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\mmu.c \
	 $(CARM) -o Debug\mmu.o
Debug\ClockSwitch.o: .\src\ClockSwitch.c $(___INC__GENERAL_H) ..\inc\\board.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\ClockSwitch.c $(CARM) -o Debug\ClockSwitch.o
Debug\MemoryPool.o: .\src\MemoryPool.c ..\inc\\iduapi.h ..\inc\\iisapi.h \
	 ..\inc\\isuapi.h $(___INC__SIUAPI_H) ..\inc\\sysapi.h \
	 $(___INC__IMA_ADPCM_API_H) ..\inc\\mmuapi.h $(___INC__SMCAPI_H) \
	 ..\inc\\rfiuapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\MemoryPool.c \
	 $(CARM) -o Debug\MemoryPool.o
Debug\main.o: .\src\main.c ..\inc\\iduapi.h ..\inc\\board.h \
	 ..\inc\\iisapi.h $(___INC__ASFAPI_H) ..\inc\\mp4api.h \
	 ..\inc\\aviapi.h ..\inc\\isuapi.h ..\inc\\gpioapi.h \
	 $(___INC__SIUAPI_H) ..\inc\\sysapi.h ..\inc\\i2capi.h \
	 $(___INC__IMA_ADPCM_API_H) $(___INC__SMCAPI_H) ..\inc\\rfiuapi.h \
	 inc\\main.h ..\inc\\stmemapi.h ..\inc\\intapi.h ..\inc\\debugapi.h \
	 $(___INC__DCFAPI_H) ..\inc\\dpofapi.h $(___INC__H264API_H) \
	 ..\inc\\jpegapi.h ..\inc\\ipuapi.h  ..\inc\\cfapi.h \
	 ..\inc\\ciuapi.h ..\inc\\mcpuapi.h ..\inc\\usbapi.h \
	 $(___INC__UARTAPI_H) $(___INC__ADCAPI_H)   ..\gpio\inc\ir_ppm.h \
	 inc\\cachereg.h ..\inc\\rtcapi.h ..\inc\\uiapi.h \
	 ..\inc\\timerapi.h ..\inc\\hiapi.h ..\ui\inc\ui.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\main.c \
	 $(CARM) -o Debug\main.o
Debug\main_task_project.o: .\src\main_task_project.c ..\inc\\iduapi.h \
	 ..\inc\\board.h ..\inc\\iisapi.h ..\inc\\mpeg4api.h \
	 $(___INC__ASFAPI_H) ..\inc\\mp4api.h ..\inc\\aviapi.h \
	 ..\inc\\isuapi.h ..\inc\\gpioapi.h $(___INC__SIUAPI_H) \
	 ..\inc\\sysapi.h ..\inc\\i2capi.h $(___INC__SMCAPI_H) \
	 ..\inc\\rfiuapi.h inc\\main.h ..\inc\\stmemapi.h ..\inc\\intapi.h \
	 ..\inc\\debugapi.h $(___INC__DCFAPI_H) ..\inc\\dpofapi.h \
	 ..\inc\\jpegapi.h ..\inc\\ipuapi.h  ..\inc\\mcpuapi.h \
	 ..\inc\\usbapi.h $(___INC__UARTAPI_H) $(___INC__ADCAPI_H)   \
	 ..\gpio\inc\ir_ppm.h ..\inc\\spiapi.h ..\inc\\webapi.h \
	 ..\inc\\rtcapi.h ..\inc\\uiapi.h ..\inc\\timerapi.h \
	 ..\inc\\hiapi.h ..\ui\inc\ui.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\main_task_project.c $(CARM) -o Debug\main_task_project.o
