#
# Warning: This Makefile is generated by the genmake program from the template:
#	gen_arx.mk - template for ARM compiler to build executables
#	It is advised that you not modify this by hand. If you want
#	to add something, you can change the gen_arx.mk template.
#	Copyright (c) ARM Ltd. 2002
#

TARGET		= ARM
INC_PATHS	= -I..\inc\ -I.\inc\

# CFLAGS is the default flags rule. Others are added below
CFLAGS		= -g $(INC_PATHS)
CFLAGS_SRCS	= 
CFLAGS_COMP		= $(CC) -c $(CFLAGS)
CFLAGS_OBJS	= 


CARM	= -I..\inc\ -I.\inc\ -g --dwarf2 -O1
CARM_SRCS	= 		  .\src\smcmap_Adv.c .\src\smcfs_Normal.c \
		  .\src\smcfs_Adv.c .\src\smc_9002_Adv.c \
		  .\src\smc_9002_Normal.c .\src\smcusb.c \
		  .\src\smcwc.c .\src\smcmap_Normal.c \
		  .\src\smc_9001_Normal.c 
CARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM) -o $$OBJ
CARM_OBJS	= 		  DebugRel\smcmap_Adv.o DebugRel\smcfs_Normal.o \
		  DebugRel\smcfs_Adv.o DebugRel\smc_9002_Adv.o \
		  DebugRel\smc_9002_Normal.o DebugRel\smcusb.o \
		  DebugRel\smcwc.o DebugRel\smcmap_Normal.o \
		  DebugRel\smc_9001_Normal.o 

CARM_CPP	=  -g --dwarf2 --cpp -O1
CARM_CPP_SRCS	= 
CARM_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CARM_CPP) -o $$OBJ
CARM_CPP_OBJS	= 

CTHUMB	=  --thumb -g --dwarf2 -O1
CTHUMB_SRCS	= 
CTHUMB_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB) -o $$OBJ
CTHUMB_OBJS	= 

CTHUMB_CPP	=  --thumb -g --dwarf2 --cpp -O1
CTHUMB_CPP_SRCS	= 
CTHUMB_CPP_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c $$SRC $(CTHUMB_CPP) -o $$OBJ
CTHUMB_CPP_OBJS	= 

AARM	=  -g --dwarf2
AARM_SRCS	= 
AARM_COMP	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armasm $(AARM) -o $$OBJ $$SRC
AARM_OBJS	= 

#FLAGS end here (put all flag groups above this line)

EXTHDRS		=
HDRS		=
LDFLAGS		=

# LIB_DEP is list of dependents for library build ($OBJS for example)
LIB_DEP		=
# LIB_ARGS is argument line for librarian
LIB_ARGS	=  --create

# LIBS are system libraries as name
LIBS		=  

CC		= cl$(TARGET)
LINKER		= $(CC)
LIBRARIAN	= c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armar 
MAKENAME	= smc_release_DebugRel.mk
PRINT		= pr
PROGRAM		= none
BUILD_LIB	= Release\..\..\lib\release\smc_release.lib
POST_BUILD	=
ALL_DEP		= $(BUILD_LIB) $(POST_BUILD)

OBJS		= $(CFLAGS_OBJS) $(CARM_OBJS) $(CARM_CPP_OBJS) $(CTHUMB_OBJS) \
	 $(CTHUMB_CPP_OBJS) $(AARM_OBJS) 
SRCS		= $(CFLAGS_SRCS) $(CARM_SRCS) $(CARM_CPP_SRCS) $(CTHUMB_SRCS) \
	 $(CTHUMB_CPP_SRCS) $(AARM_SRCS) 

# depend is for dependant rules that should not be linked in
DEPEND	=
O_DEPEND	= 

COMP_LINE	= $(CFLAGS_COMP)

# .c.o is default compile line if not explicitly defined

.c.o :
	$(COMP_LINE) $*.c

# all is first target 
all:		$(ALL_DEP)
		@+echo --- Build-all done ---

#LINK: next one is the link command
$(PROGRAM):     $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LINKER) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)

#BUILD_LIB: this is only valid if filled in at macro point
$(BUILD_LIB):	$(LIB_DEP) $(OBJS) $(DEPEND) $(O_DEPEND) $(MAKENAME)
		$(LIBRARIAN) $(LIB_ARGS) $(BUILD_LIB) $(OBJS)

clean:
		+for %d in ($(OBJS) $(PROGRAM) $(BUILD_LIB)) do if exist %d del %d
rebuild:	clean all
depend:;	upddep $(MAKENAME)
index:;	ctags -wx $(HDRS) $(SRCS)
print:;	$(PRINT) $(HDRS) $(SRCS)
program:	$(PROGRAM)
tags:		$(HDRS) $(SRCS); ctags $(HDRS) $(SRCS)

# DEPEND: include files below
# Dependency summaries:
# System includes suppressed
# Missing files: 21
___INC__SYSOPT_H=..\inc\\sysopt.h ..\inc\\sysoptdef.h 
___INC__OSAPI_H=..\inc\\osapi.h 
___INC__GENERAL_H=..\inc\\general.h $(___INC__SYSOPT_H) ..\inc\\awbdef.h \
	 $(___INC__OSAPI_H) ..\inc\\memorypool.h 
___INC__SMCAPI_H=..\inc\\smcapi.h $(___INC__GENERAL_H) 
INC__SMCWC_H=inc\\smcwc.h $(___INC__SMCAPI_H) 
___INC__FSAPI_H=..\inc\\fsapi.h $(___INC__SYSOPT_H) ..\fs\inc\fs_fat.h 
___INC__UIAPI_H=..\inc\\uiapi.h ..\inc\\task.h 
___INC__DCFAPI_H=..\inc\\dcfapi.h ..\inc\\sdcapi.h 
INC__SMCECCSW_H=inc\\smceccsw.h $(___INC__GENERAL_H) 
# DEPEND: end include files

DebugRel\smcmap_Adv.o: .\src\smcmap_Adv.c ..\inc\\board.h inc\\smc.h \
	 inc\\smcreg.h $(INC__SMCWC_H) $(___INC__FSAPI_H) ..\inc\\ispapi.h \
	 $(___INC__UIAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\smcmap_Adv.c \
	 $(CARM) -o DebugRel\smcmap_Adv.o
DebugRel\smcfs_Normal.o: .\src\smcfs_Normal.c $(INC__SMCWC_H) \
	 $(___INC__FSAPI_H) $(___INC__UIAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\smcfs_Normal.c $(CARM) -o DebugRel\smcfs_Normal.o
DebugRel\smcfs_Adv.o: .\src\smcfs_Adv.c $(INC__SMCWC_H) $(___INC__FSAPI_H) \
	 $(___INC__UIAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\smcfs_Adv.c \
	 $(CARM) -o DebugRel\smcfs_Adv.o
DebugRel\smc_9002_Adv.o: .\src\smc_9002_Adv.c ..\inc\\board.h inc\\smc.h \
	 inc\\smcreg.h $(INC__SMCWC_H) $(___INC__FSAPI_H) ..\inc\\dmaapi.h \
	 ..\inc\\rtcapi.h $(___INC__DCFAPI_H)  ..\inc\\gpioapi.h \
	 inc\\smceccsw.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\smc_9002_Adv.c $(CARM) -o DebugRel\smc_9002_Adv.o
DebugRel\smc_9002_Normal.o: .\src\smc_9002_Normal.c ..\inc\\board.h \
	 inc\\smc.h inc\\smcreg.h $(INC__SMCWC_H) $(___INC__FSAPI_H) \
	 ..\inc\\dmaapi.h ..\inc\\rtcapi.h $(___INC__DCFAPI_H)  \
	 ..\sys\inc\sys.h inc\\smceccsw.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\smc_9002_Normal.c $(CARM) -o DebugRel\smc_9002_Normal.o
DebugRel\smcusb.o: .\src\smcusb.c $(___INC__SMCAPI_H) $(___INC__FSAPI_H) \
	 ..\inc\\usbapi.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\smcusb.c \
	 $(CARM) -o DebugRel\smcusb.o
DebugRel\smcwc.o: .\src\smcwc.c ..\inc\\board.h inc\\smc.h inc\\smcreg.h \
	 $(INC__SMCWC_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c .\src\smcwc.c \
	 $(CARM) -o DebugRel\smcwc.o
DebugRel\smcmap_Normal.o: .\src\smcmap_Normal.c ..\inc\\board.h inc\\smc.h \
	 inc\\smcreg.h $(INC__SMCWC_H) $(___INC__FSAPI_H) ..\inc\\ispapi.h \
	 $(___INC__UIAPI_H)
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\smcmap_Normal.c $(CARM) -o DebugRel\smcmap_Normal.o
DebugRel\smc_9001_Normal.o: .\src\smc_9001_Normal.c ..\inc\\board.h \
	 inc\\smc.h inc\\smcreg.h $(INC__SMCWC_H) $(___INC__FSAPI_H) \
	 ..\inc\\rtcapi.h $(___INC__DCFAPI_H) ..\sys\inc\sys.h
	c:\progra~1\arm\rvct\programs\2.1\328\win_32~1\armcc -c \
	 .\src\smc_9001_Normal.c $(CARM) -o DebugRel\smc_9001_Normal.o
